### ISSUE TITLE
configurable errors on lookup

### ISSUE THREAD

**Issue by lindem** [offirgolan/ember-cp-validations#101]
right now, if a validator is not to be found in the container, cp-validations issue a warning. Is there any plan to make this an exception (like, a real error), possibly via environment? 

My rationale is that a validator not being found is clearly "a piece of software not working as you expect it" (because then, the validation **passes** automatically). Thoughts?

**Comment by offirgolan** [comment]
:+1: I agree with making this throw an error instead of a warning.
