### ISSUE TITLE
debounced validations does not work

### ISSUE THREAD

**Issue by steffenbrem** [offirgolan/ember-cp-validations#102]
The debounce is not really debouncing because of the following code: https://github.com/offirgolan/ember-cp-validations/blob/master/addon/validations/factory.js#L250

You cannot pass an anonymous function as the debounce method, but it should rather pass in a reference of a function (http://emberjs.com/api/classes/Ember.run.html#method_debounce).

**Comment by offirgolan** [comment]
:+1:  Ill issue out a fix for this soon

**Comment by steffenbrem** [comment]
Thanks @offirgolan quick fix! :+1:

**Comment by offirgolan** [comment]
No problem! v2.2.1 has been release to npm :smile_cat:. Thanks for pointing this out
