### ISSUE TITLE
Email validation doesn't require top level domain

### ISSUE THREAD

**Issue by mguida22** [offirgolan/ember-cp-validations#105]
The email validation only requires that one character exists after the `@` symbol. This allows for email addresses such as `a@b` or `foo@bar` to be marked as valid. A live demo of this can be seen by trying either of the examples on the project demo page.

http://offirgolan.github.io/ember-cp-validations/

**Comment by offirgolan** [comment]
Thanks for opening an issue! :smile: 

The regex used to match email addresses follows the [W3C HTML5 spec](https://www.w3.org/TR/html5/forms.html#valid-e-mail-address). If you require a more strict email validation, I would either pass in a new regex or create a new validator that extends the `format` validator and overwrite `regularExpressions.email`. 

If this becomes a bigger issue, I'll take a closer look into it.

**Comment by mguida22** [comment]
Thanks for the reply! That sounds good to me!
