### ISSUE TITLE
Several validation mixins on one model.

### ISSUE THREAD

**Issue by Sinled** [offirgolan/ember-cp-validations#108]
Hi, at first thanks for this handy validation plugin.

I have a small issue, i need possibility to add several validation mixins to one model:

```js
const ValidationsTeamCount = buildValidations({
  teamMaxCount: validator('number', {
    gte: 1,
  }),
});

const ValidationsTime = buildValidations({
  availableFrom: validator('presence', true),
  availableTill: validator('presence', true),
});

export default Model.extend(
  ValidationsTime,
  ValidationsTeamCount, {
});
```

Currently it is not working, may be i am doing something wrong?

**Comment by offirgolan** [comment]
Unfortunately this isn't currently possible nor do I think it will be supported. You can do the following instead: 

```js
var Time = {};
var TeamCount = {};

const Validations = buildValidations(Ember.merge(Time, TeamCount));

export default DS.Model.extend(Validations, {});
```

Where Time and TeamCount hold your validator rules

**Comment by Sinled** [comment]
Thanks, i'll try this, it's better than nothing :)
