### ISSUE TITLE
Validating form submissions without model

### ISSUE THREAD

**Issue by artmees** [offirgolan/ember-cp-validations#109]
sorry I'm new to ember... and I'm not sure if this possible/correct or not ?
but is it possible to validate forms only for submission without having the component backed with some model...
for example (login page) that require the user to insert his email and password ( need only to validate the form )

here is the code used
```js
// components/sign-in.js
import Ember from 'ember';

export default Ember.Component.extend({
  authentications: Ember.inject.service(),
  actions: {
    signIn() {
      let credentials = this.getProperties('email', 'password', 'remember_me');
      this.get('authentications').signIn(credentials);
    }
  }
});
```
and here is the template code
```hbs
<!-- templates/components/sign-in.hbs -->
<form {{action 'signIn' on='submit'}}>
  <label for='email'>Email</label>
  {{input id='email' placeholder='em@i.l' type='email' value=email}}
  <label for='password'>Password</label>
  {{input id='password' placeholder='Pa$$w0rd' type='password' value=password}}
  <label for='remember_me'>Remember Me</label>
  {{input id='remember_me' type='checkbox' checked=remember_me}}
  <button type='submit'>Sign In</button>
</form>
```
I don't have a controller or any model for this login... and I need to add validations for the component itself ( and the previous code is already authenticating correctly )...

and if it's also possible to show errors on the field that was wrong ( after the 401 response is received )

**Comment by offirgolan** [comment]
Your validated component will look something like this

```js
// components/sign-in.js
import Ember from 'ember';
import { buildValidations, validator } from 'ember-cp-validations';

const Validations = buildValidations({...});

export default Ember.Component.extend(Validations, {
  // ...
});
```

From there you are welcome to use the [validated-input component](https://github.com/offirgolan/ember-cp-validations/blob/master/tests/dummy/app/components/validated-input.js) that is used in the demo app (make sure you checkout the [associated template file](https://github.com/offirgolan/ember-cp-validations/blob/master/tests/dummy/app/templates/components/validated-input.hbs)).

Your form will have the following:

```hbs
{{validated-input model=this valuePath='email' placeholder='Email'}}
{{validated-input model=this valuePath='password' placeholder='Password'}}
{{validated-input model=this valuePath='remember_me' placeholder='Remember Me'}}
```

Hope that helps :smile_cat:

**Comment by artmees** [comment]
but how do I disable the submit button when the form is invalid ?

**Comment by artmees** [comment]
to help others stumbling in the same issue ( and also validate the solution )... here is the full code

```js
import Ember from 'ember';
import { buildValidations, validator } from 'ember-cp-validations';

const Validations = buildValidations({
  email: [
    validator('presence', true),
    validator('format', { type: 'email' })
  ],
  password: [
    validator('presence', true),
    validator('length', { min: 3 })
  ]
});

export default Ember.Component.extend(Validations, {
  authentications: Ember.inject.service(),
  actions: {
    signIn() {
      let credentials = this.getProperties('email', 'password', 'remember_me');
      this.get('authentications').signIn(credentials);
    }
  }
});
```

and here is the template ( with sign in disabled unless the form is valid )
```hbs
<form {{action 'signIn' on='submit'}}>
  {{validated-input model=this valuePath='email' placeholder='em@i.l'}}
  {{validated-input model=this valuePath='password' placeholder='Pa$$w0rd' type='password'}}
  <label for='remember_me'>Remember Me</label>
  {{input id='remember_me' type='checkbox' checked=remember_me}}
  <button type='submit' disabled={{this.validations.isInvalid}}>Sign In</button>
</form>
```
given that you add the `validated-input` component and component template ( mentioned earlier )

**Comment by offirgolan** [comment]
Glad you were able to figure it out :smile_cat: 

For the submit button, you can also use the [v-get helper](http://offirgolan.github.io/ember-cp-validations/docs/modules/Templating.html)

```hbs
<button type='submit' disabled={{v-get this 'isInvalid'}}>Sign In</button>
```

**Comment by zion03** [comment]
I have the same login form, but I trying perform logic like in demo [http://offirgolan.github.io/ember-cp-validations/](url) so in "signIn" action  I try to validate component using:

> "validateSync"  and "validate"

 but validate works only when I fill input.

Shortly - I want validate component onclick, not only on changing field

**Comment by zion03** [comment]
Solved, just need to set ` this.set('didValidate', true); ` after validation, it's not well documented.

**Comment by stephanebruckert** [comment]
None of the solutions here would work but I just found a way of doing this: 

https://stackoverflow.com/questions/43680911/how-to-validate-checkbox-selectbox-and-radiobutton-in-ember-cp-validations
