### ISSUE TITLE
document how to handle server errors

### ISSUE THREAD

**Issue by blimmer** [offirgolan/ember-cp-validations#110]
I recently ran into a case where the client couldn't handle the validation error (MFA token). Is there a way to push that error into the validation errors array? Or, should I handle that separately (outside of cp-validations).

**Comment by offirgolan** [comment]
Can I get a little bit more details? Where is this token stored? Where is the error actually coming from and stored? Is this coming from an ember-data model or an ember object?

**Comment by blimmer** [comment]
Yep, sorry, I should have provided more information about this before opening the issue.

In order for a user to log in to our site, they need to provide a multifactor authentication token. So, the validations that can be calculated client side look like this:

```javascript
let Validations = buildValidations({
  email: {
    validators: [
      validator('presence', true),
      validator('format', {
        type: 'email',
      }),
    ]
  },
  password: {
    validators: [
      validator('presence', true),
      validator('length', {
        min: 6,
        max: 255,
      })
    ]
  },
  token: {
    validators: [
      validator('presence', true),
      validator('length', {
        is: 6,
      })
    ]
  },
});

export default DS.Model.extend(Validations, {
  ...
});
```

However, there's no way that the client could ever know whether or not the MFA token was correct (the server is the one who validates that). In that case, I want to be able to invalidate the `User` model until they try a different token.

The way we ended up solving it was something like this:
```javascript
// in the validations block
  token: {
    validators: [
        ... presence, length ...
      validator(function(value, options, model) {
        if (model.get('tokenIsServerValid')) {
          return true;
        }
        return options.message;
      }, {
        dependentKeys: ['tokenIsServerValid'],
        message: 'invalid MFA token',
      }),
    ]
  }


// in the user model definition
  tokenIsServerValid: Ember.computed('token', {
    get() {
      return true;
    },
    set(key, value) {
      return value;
    },
  }),

// in the rejected sign in attempt action
this.set('user.tokenIsServerValid', false);
```

So, we invalidate the computed property when the server tells us to (by setting a property on the `User`), but anytime the user changes the `token` value, we reset the value. This works, but is there another way that you would've handled this? Or are we on the right track?

**Comment by offirgolan** [comment]
I see. That's pretty much how I would handle that. I don't really see any other way :smile_cat:

**Comment by blimmer** [comment]
OK cool, just wanted to see if you had any other thoughts. Do you think this would be work a docs PR? I tried searching issues and docs for how to handle server-generated errors and came up dry.

**Comment by offirgolan** [comment]
Hmmm I dont really think it's necessary, since the validator you described is simply a custom validator with a dependent key on the model. If more questions like these arise in the future, I can put up a new section in the docs for some "advanced" examples. 

Maybe a good idea would be to open up an issue in the mean time with some examples on how to solve so more complex validations and I can create a doc from that :smile:
