### ISSUE TITLE
templating sample for has many validation

### ISSUE THREAD

**Issue by thiyagu06** [offirgolan/ember-cp-validations#114]
Can you provide the template sample for has many validation?

**Comment by offirgolan** [comment]
Im not sure I follow exactly what you're asking for, can you elaborate a little more?

**Comment by thiyagu06** [comment]
I have asked how to use has many validation.. Now I found the same in your documentation.so closing this issue now. Regret the inconvenience

**Comment by thiyagu06** [comment]
What changes to be done if I want to handle server side error. I mean to
handle DS.errors??

**Comment by offirgolan** [comment]
See #110 :smile_cat:
