### ISSUE TITLE
How to handleDS.errors?

### ISSUE THREAD

**Issue by thiyagu06** [offirgolan/ember-cp-validations#118]
Is there any code need be wriiten if server throws 422 errors.The one which is mentioned in the below link.

http://emberjs.com/api/data/classes/DS.Errors.html

**Comment by offirgolan** [comment]
You can do something like this

```js
const Validations = buildValidations({
  foo: validator(function(value, options, model, attribute) {
    if (model.get('errors').has(attribute)) {
      return model.get(`errors.${attribute}.messages.firstObject`);
    }
    return true;
  }, { dependentKeys: ['errors.foo.messages.[]']})
});
```

**Comment by thiyagu06** [comment]
Do I need to use this for each attributes in the model?

**Comment by thiyagu06** [comment]
it is not working for embedded belongs to and has many relationships..

**Comment by offirgolan** [comment]
You have to put your validations on the model that has the errors. You cant validate `child` on `model.child` if that makes sense...

On a side note: @blimmer is this the sort of issue you have been facing as well? Would it help to have a `validator('ds-error')` that handles the dependentKeys and spits out the last error for the given attribute?

**Comment by blimmer** [comment]
@offirgolan that would be helpful - it would be especially helpful if it could identify the model property and mark that invalid (e.g. on a user form, highlight what is invalid like birthdate).

**Comment by offirgolan** [comment]
@thiyagu06 `v2.5.0` has been released with a new DS Error validator :smile_cat:
