### ISSUE TITLE
v-get helper

### ISSUE THREAD

**Issue by offirgolan** [offirgolan/ember-cp-validations#12]
Create a general helper to access properties on the validation object.

- `(v-get model 'username' 'isValid')`
- `(v-get model 'isInvalid')`
- `{{v-get model 'username' 'message'}}`
- `{{#each (v-get model 'messages') as |message|}} {{/each}}`

**Comment by offirgolan** [comment]
I think this helper should just be available for Ember >= 2.0. This way it can just be a wrapper around the implementation for the `get` helper introduced in Ember 2.0. 

```javascript
export default Ember.Helper.helper(function(params, hash) {
  // manipulate params 
  // ..
  return Ember.Templates.helpers.get.apply(this, arguments)
});
````

After some playing around, I dont know if this is possible. Before, you can access already defined helpers via `Ember.Handlebars.helpers`. From the docs, it notes that all current helpers are under Ember.Templates but that namespace doesnt exist from within the app. @rwjblue any suggestion here?

**Comment by rwjblue** [comment]
The `Ember.Templates.helpers` namespace is only used to allow us to group documentation, it is not a "real" thing. In general, you cannot invoke helpers as you used to be able to.

---

My suggestion would be add an AST transformation to transform:

```
{{#if (v-get model 'username.isInvalid')}}
{{/if}}
```

Into:

```
{{#if model.validations.attrs.username.isInvalid}}
{{/if}}
```

This allows us to have nice things, but keep the simplicity in the end.

**Comment by rwjblue** [comment]
This intrigued me, so I implemented a first draft of it in JSBin: http://rwjblue.jsbin.com/rujeji/edit?html,js

You can take a peek at ember-gestures to see how to incorporate this into the node-land precompilation for a project:

* https://github.com/runspired/ember-gestures/blob/7986508eb167adc547571e6e6d0aecf791fe9253/index.js#L17-L25
* https://github.com/runspired/ember-gestures/blob/7986508eb167adc547571e6e6d0aecf791fe9253/htmlbars-plugins/touch-action.js

**Comment by stefanpenner** [comment]
> My suggestion would be add an AST transformation to transform:

Ah, this totally slipped my mind!

**Comment by offirgolan** [comment]
This is great! Thanks for the redirection and the first draft. Ill work on this more when I get the chance

**Comment by blimmer** [comment]
This is really cool. Thanks for the tip @rwjblue

**Comment by offirgolan** [comment]
Alright so after some tinkering, I was able to get almost everything we need.

```handlebars
{{model.validations.attrs.username.isInvalid}}<br>
{{v-get model 'username' 'isInvalid'}}
{{#unless (v-get model 'isValid')}}
   v-get: NOT VALID
{{/unless}}
```

This works great when all params are strings but when they are streams or references, this breaks down

```handlebars
// model.attr = 'username'
{{v-get model model.attr 'isValid'}}
```

JSBin: http://jsbin.com/walukeniju/2/edit?html,js,output

**Comment by offirgolan** [comment]
Another possibility can just be [ember-get-helper](https://github.com/jmurphyau/ember-get-helper/blob/master/addon/helpers/get-glimmer.js)

**Comment by offirgolan** [comment]
OR one other possibility is to use the already created `get` helper and do an AST transformation to create subexpressions to get to the the correct validation object we need

JSBin: http://jsbin.com/fafesujeyu/1/edit?html,js,output

**Comment by rwjblue** [comment]
Ya, if all the sections are not static strings (you would detect this by seeing a PathExpression in one of the params), then you would replace the 'v-get' subexpression with the 'get' helper that is baked into 2.0 (or folks could use ember-get-helper for 1.x support).

    // model.attr = 'username'
    {{v-get model model.attr 'isValid'}}

Becomes:

    {{get (get model.validations.attrs model.attr) 'isInvalid'}}

It is clearly not as pretty (and is more work than the static version), but it shouldn't be fundamentally harder to do (and IMHO it is less common).

**Comment by blimmer** [comment]
I'd really like to see a solution that's 1.x and 2.x compatible. Many of us have a while to go before we are 2.x compliant.

**Comment by rwjblue** [comment]
AST Transforms work from 1.10.

**Comment by offirgolan** [comment]
This gets a little more complicated when the last param is also a PathExpression

`{{v-get model model.attr someObj.child.prop}}`
`{{get (get (get (get model 'validations') 'attrs') model.attr) (get this someObj.child.prop)}}`

@blimmer @stefanpenner if you think this is worth implementing let me know and ill work on this.

**Comment by rwjblue** [comment]
> This gets a little more complicated when the last param is also a PathExpression

Yes, but it is still very much PAYGO (pay as you go) in that the more complicated you make your `{{v-get}}` invocation the more complicated/costly it becomes.  I think this is probably still fine...

I'm personally :+1: on this path...

---

I do want to make `get` helper aware of paths which would solve some of this crazy nesting, but doesn't help folks right away.

So:

```handlebars
{{v-get model attrName 'isInvalid'}}
```

Could become:

```handlebars
(get model (concat 'validations.attrs' '.' attrName '.'  'isInvalid'))
```

Which seems much simpler to me...

**Comment by offirgolan** [comment]
> (get model (concat 'validations.attrs' '.' attrName '.'  'isInvalid'))

I like this a lot more. Let me play around with this and get an example jsbin working.

**Comment by rwjblue** [comment]
> > (get model (concat 'validations.attrs' '.' attrName '.' 'isInvalid'))
>
> I like this a lot more. Let me play around with this and get an example jsbin working.

Just to note, I am saying I want to fix `get` to allow this.  As of 2.0/2.1 you cannot use a `.` in the second argument to `get`.  https://github.com/emberjs/ember.js/issues/12263 is open for tracking that.

**Comment by offirgolan** [comment]
Oh I see. Yeah I tried including a string with `.` but it just errored. As for now, Ill just play around with the nested gets

**Comment by rwjblue** [comment]
https://github.com/emberjs/ember.js/pull/12323 should fix the nested path issue I mentioned above, and should be in 2.1.0.

**Comment by offirgolan** [comment]
At this point, it would be better to go with the nested `get` helper instead of using concat. That way we can support 1.10 - canary (with the ember-get-helper polyfill)

**Comment by offirgolan** [comment]
@rwjblue this actually wasnt too hard to implement. I was able to create a version that fits all of our use cases. 

http://jsbin.com/yakice/3/edit?html,js,output

**Comment by rwjblue** [comment]
@offirgolan - Looks great! 


I think we still need to handle hash params example also:

```handlebars
{{validation-error-printer errors=(v-get model 'username')}}
```

**Comment by offirgolan** [comment]
Good point. Ill keep hacking away at this.

**Comment by offirgolan** [comment]
@rwjblue here's a version with hash params working:

http://jsbin.com/yakice/4/edit?html,js,output

Ill work on getting this into the addon. :smile:

**Comment by rwjblue** [comment]
:+1:

**Comment by rwjblue** [comment]
Side note: these AST transforms are kinda fun :smiley_cat:

**Comment by offirgolan** [comment]
Agreed. This was pretty fun to work with

**Comment by offirgolan** [comment]
#26 is merged. Closing :joy_cat:
