### ISSUE TITLE
Broken link in your docs page

### ISSUE THREAD

**Issue by ChrizzDF** [offirgolan/ember-cp-validations#121]
Hi @offirgolan,

I just noticed that on your docs page (http://offirgolan.github.io/ember-cp-validations/docs/modules/Home.html), the link to your demo app refers to "http://offirgolan.github.io/" but actually the demo is available under "http://offirgolan.github.io/ember-cp-validations".

Thanks for this awesome package, I really appreciate it! =)

**Comment by offirgolan** [comment]
Thanks for pointing this out! Link is fixed now :+1:
