### ISSUE TITLE
Email uniqueness validation question

### ISSUE THREAD

**Issue by kbalyasnikov** [offirgolan/ember-cp-validations#125]
Hi!

Thanks for awesome library! I have searched for open and closed issues but haven't found answer to my questions. 

1) How can i call custom (or any other) validator only if another validators on the same property are passed? 

For example i have "email" property with "presence" and "format" validators attached. Those two works great. After that i add "unique-email" validator, but it's get called in parallel with first two validators and gets incorrect email as input. It would be great if "unique-email" validators get called only if previous passed.

[Proposal] Add option like "failFast" at property level. If it's true then validation of property stops after first failed validator. Or add an option to specify dependency on another validator attached to same property.

2) [Maybe proposal] Can "debounce" be attached to validator in addition to property itself. This makes sense for remote validations like one described above.

**Comment by offirgolan** [comment]
1) Im really not sure if this would work but you can give it a shot

```js
const Validations = buildValidations({
  email: [
    validator('presence', true),
    validator('format', { type: 'email' }),
    validator('unique-email', {
      disabled() {
        return this.get('model.validations.attrs.email.isInvalid');
      },
      dependentKeys: ['validations.attrs.email.isInvalid']
    }),
  ]
});
```

It's not very pretty but with the current implementation, Im not really sure if this sort of thing would be simple to do. Let me know how this works out for you and if it doesnt, ill spend some more time on this :smile: 

2) Im not really sure I understand what you mean but options can be placed on the entire attribute or single validators. See [defaultOptions](http://offirgolan.github.io/ember-cp-validations/docs/modules/Advanced%20Usage.html)

```js
const Validations = buildValidations({
  email: [
    validator('format', { type: 'email', debounce: 500 })
  ]
});

const Validations = buildValidations({
  email: { 
    debounce: 500,
    validators: [
     validator('format', { type: 'email'})
    ]
  }
});
```

**Comment by kbalyasnikov** [comment]
1) Sorry, this solution doesn't work. "model.validations.attrs.email" is not populated until all property validators gets executed. The only workaround i found is to check in unique-email validator if email is valid before sending request to server.
2) That's what i wanted, thanks! Works like a charm!

**Comment by offirgolan** [comment]
I see. Another solution would be to extend the `format` validator

```js
import Format from './format';

export default Format.extend({
   validate() {
  	let isEmail = this._super(...arguments);
    
    if(isEmail === true) {
     // do uniqueness check
    } else {
      return isEmail; // this will be the returned message
  }
})
```

**Comment by basz** [comment]
thank you for an awesome library!

how would I extend format as that doesn't seem to be exposed in the sources?

I noticed you do `import Format from './format';`, does that mean I should copy format.js to the folder where 'unique-email.js' lives?

**Comment by offirgolan** [comment]
@basz you dont need to copy over the `format` validator. The addon imports all validators to `app/validators` at runtime which allows you to do what I mentioned above :smile:

**Comment by basz** [comment]
thank you - I got it to work. For anyone this is my take on it

```
import Ember from 'ember';
import FormatValidator from './format';

const {
  get,
  isNone,
  isEmpty
} = Ember;

export default FormatValidator.extend({
  queryBus: Ember.inject.service('cqrs/query/auth/user'),
  validate(value, options /*, model, attribute*/ ) {
    options.type = 'email';

    if (!isNone(this.regularExpressions[options.type]) && isNone(options.regex)) {
      options.regex = this.regularExpressions[options.type];
    }

    let isEmail = this._super(...arguments);

    if (isEmail === true) {
      // do uniqueness check
      return this.get('queryBus').emailAddressIsRegisteredQuery(value).then(result => {
        return result === true ? "The email address is already in use." : true;
      });
    } else {
      return isEmail; // this will be the returned message
    }
  }
});
```

**Comment by offirgolan** [comment]
:+1: thanks for sharing! 

May I ask what this block is for?

```js
if (!isNone(this.regularExpressions[options.type]) && isNone(options.regex)) {
  options.regex = this.regularExpressions[options.type];
}
```

**Comment by basz** [comment]
That’s copied from 

node_modules/ember-cp-validations/app/validators/format.js

I did that because options.regex must be set at validate() time, but somehow the following did;t work

```
buildOptions(options = {}, defaultOptions = {}) {
    options.type = ‘email’;

    return this._super(options, defaultOptions);
  },
```

**Comment by offirgolan** [comment]
Hmmmmm, thats not good. Ill take a closer look at why that is when I have some time.

**Comment by basz** [comment]
don't. I solved it. I think the problem arose from my initial call to return `this._super` with `...arguments` instead of the mutated options.

That snippet actually works now.

**Comment by offirgolan** [comment]
Ah okay cool! Thanks for the update :smile_cat:

**Comment by basz** [comment]
```
import Ember from 'ember';
import FormatValidator from './format';

export default FormatValidator.extend({
  queryBus: Ember.inject.service('cqrs/query/auth/user'),
  buildOptions(options = {}, defaultOptions = {}) {
    options.type = 'email';

    return this._super(options, defaultOptions);
  },
  validate(value /*, options, model, attribute */ ) {
    let isEmail = this._super(...arguments);

    if (isEmail === true) {
      // do uniqueness check
      return this.get('queryBus').emailAddressIsRegisteredQuery(value).then(result => {
        return result === true ? "The email address is already in use." : true;
      });
    } else {
      return isEmail; // this will be the returned message
    }
  }
});
```

**Comment by offirgolan** [comment]
:+1: thank you :smile:

**Comment by offirgolan** [comment]
Im assuming this issue to be resolved so im gonna go ahead and close it. Feel free to reopen if you need more help on the matter.
