### ISSUE TITLE
Build validations dynamically

### ISSUE THREAD

**Issue by HenryVonfire** [offirgolan/ember-cp-validations#126]
Is it possible to build the validations of a model dynamically? I would like to provide some validations from the server.

**Comment by offirgolan** [comment]
Can you elaborate by what you mean on 'providing some validations from the server'?

**Comment by HenryVonfire** [comment]
If I'm not mistaken, with `ember-cp-validations` the model validations need to be defined statically but for some models I would to be the server the one giving the parameters to validate these models in the client. The only possible way that occurs to me to achieve this with `ember-cp-validations` is to extend `ember objects` with the validations sent from the server and copy the models into them but that doesn't seem right. Isn't it possible to add/remove/edit existing validations of models?

**Comment by offirgolan** [comment]
If you're using Ember.Object and not DS.Model, you can easily do this.

```js
export default Ember.Route.extend({
  model(params) {
  	return this.store.query('validation', params)
  },
  
  setupController(controller, validations) { 
    const Validations = buildValidations(validations); // build your validations here with the returned payload
    let modelClass = Ember.Object.extend(Ember.getOwner(this).ownerInjection(), Validations);
    controller.set('model', modelClass.create());
  }
});
```

If you are using DS.Model, this is currently not supported. There have been some talks about creating a flow to generate validations from the server but I havent had the chance to work on that. Maybe @stefanpenner can shed some light here

**Comment by stefanpenner** [comment]
@offirgolan what you describe sounds accurate.

**Comment by HenryVonfire** [comment]
That was the idea I was mentioning, using an `Ember.Object`, extend it with validations and fill it with the properties of a `DS.Model` record but I was hoping there was a better solution for this 😩.

Anyway, thanks for the help and your time 😊

**Comment by stefanpenner** [comment]
I'm not sure why that wouldn't also work with a DS.Model. That being said, if you are constantly building new validations for each instance of a model, you will suffer performance issues similar to other validation libraries, whereas by-default this library is very performant.

You should share some examples of the validations you received from the server and the models they are applied to. I suspect in many cases, a custom validator could be used rather then having to creation random validations on the fly.

**Comment by HenryVonfire** [comment]
Is not that there are too many changes in the validations but we want to have the feature of changing them in the server and these changes being reflected automatically in the client. It's just for maintenance purposes. Maybe it isn't worth?

**Comment by offirgolan** [comment]
Opened up a discussion on this (#129)
