### ISSUE TITLE
How to use this library?

### ISSUE THREAD

**Issue by nicozimmermann94** [offirgolan/ember-cp-validations#128]
Hello, maybe I am blind or very stupid, but I cannot find a way to actually USE this library.
I watched the talk video and had a look at the demo file, but I cannot find anything about how to check if the validation works or how to display errors in a form (for example).
I got how to implement the rules in the model but what now?
Maybe this is a very stupid issue.

**Comment by offirgolan** [comment]
Check out the [Validations docs](http://offirgolan.github.io/ember-cp-validations/docs/modules/Validations.html). 

> All validations can be accessed via the validations object created on your model/object. Each attribute also has its own validation which has the same properties. An attribute validation can be accessed via `validations.attrs.<ATTRIBUTE>` which will return a [ResultCollection](http://offirgolan.github.io/ember-cp-validations/docs/classes/ResultCollection.html).

For example, if you have a User model and you want to see if username is valid, you can do something like this

`user.get('validations.attrs.username.isValid')`

If you have some more specific questions, feel free to add them here and I can answer as best as I can :smile_cat:

**Comment by nicozimmermann94** [comment]
Thank you very much.

**Comment by offirgolan** [comment]
Updated docs :smile_cat:
