### ISSUE TITLE
Support for Server Side Validations

### ISSUE THREAD

**Issue by offirgolan** [offirgolan/ember-cp-validations#129]
I know @stefanpenner and I talked about this in the early stages of this library, but I was hoping to get a discussion going to talk about the implementation of this. 

Ill start this thread off by just throwing some ideas :bulb: 

```js
const Validations = buildValidationsFromServer({
  perInstance: false // if to make the getValidations call for each instance
  getValidations() {
    return this.store.query('user-validations', {foo: 'bar'});
  },
  normalize(validations) {
    // called after getValidations promise resolves
    // create the same structure here required by buildValidations
    // maybe provides some helpers here to do this
    let rules = {};
    for(let attr in validations) {
      // ...
    }
    return rules;
  }
});
```

My idea is to keep this object on the proto, then once the first object is instantiated, execute the getValidations promise (this will give us access to the container, store, etc). Once that is resolved and normalized, create the Validations object on the instance. We can provide something like `model.get('validations.isReady')` or `model.get('validations.ready').then(...)` 

cc @rwjblue @blimmer

**Comment by offirgolan** [comment]
After discussion with Stef, it was concluded that most use cases can be solved with the current implementation. If a specific use case comes up, ill reopen this issue.

**Comment by danshapir** [comment]
I'm really in favor of that feature! We need exactly that. All our validation rules are coming from the server.

To be honest, i don't mind having the valdations static on a model, but have the rules dynamic.

I'll elaborate:
Let's assume we have a mail property. That property has some regex validation on it. I want that regex to come from the server. How is that do able?

**Comment by offirgolan** [comment]
You can simply do something like this: 

```js
validator('format', {
  type: 'email',
  regex() {
    return this.get('model.<path_to_regex>');
  }
})

**Comment by danshapir** [comment]
You assume i have the regex on my model. My intentions are to have all the validations downloaded from the server kept in one place.

Like getting a huge json from the server with the validation rules and the equivalent i18n key, saving them in one place and then using your solution. Just without keeping the regex itself in the model

**Comment by danshapir** [comment]
@offirgolan ?

**Comment by danshapir** [comment]
So basically having the initializer doing an Ajax call, getting all the validations and then reopening all the models and injecting them in through the function validation syntax? Sounds good!

**Comment by offirgolan** [comment]
Yeah that should work. Let me know if you run into any major hurtles.

**Comment by zardaloop** [comment]
@offirgolan  assuming that I have a object like this 
```
data:{
   field1:{ phoneNumber:null, validator: validator('format', { type: 'email' })},
   field2:{phoneNumber:null, validator: validator('format', { type: 'email' }) }
}
```
and I want to pass this into a component and inside the component deal with the validation. 

`{{my-component data= data }}`

then inside my-component's js file I have something like this 

> /components/my-component.js

```
import Ember from 'ember';
import { validator, buildValidations } from 'ember-cp-validations';

export default Ember.Component.extend({
  data: null,
  didReceiveAttrs() {
    var validations = {};
    this.set('temp', this.get('fields'));
    var data= this.get('data');
    for (var property in data) {
      if (data.hasOwnProperty(property)) {
        if(items[property].validator){
        validations['data.'+ property + '.selectedValue'] = data[property].validator;
        }
      }
    }
    const Validations = buildValidations(validations);
    // How do I inject the validations ? 
  }
});
```
How do I inject this validations back ?do I just need to say data.reopen(validations) ?

**Comment by offirgolan** [comment]
@zardaloop after you build your validations, I think your best bet is to place it on some temporary object.

```js
const Validations = buildValidations(validations);
const validatableModel = Ember.Object.extend(Validations).create(Ember.getOwner(this).ownerInjection(), { data: data });
this.set('_model', validatableModel);

// usage
this.get('_model.validations.isValid');
this.get('_model.validations.attrs.data.foo.bar.isValid');
```

This allows you to dynamically create validations on an object that targets `data.foo.bar` and not have to rely on `reopen`.

**Comment by zardaloop** [comment]
Thanks @offirgolan  do I acually need to use model ? because I am not using model here, I am binding data property into the template of the component.

**Comment by offirgolan** [comment]
@zardaloop you can use `_model` just to validate, you dont need to bind anything to it. You can just bind to `data` directly.

**Comment by zardaloop** [comment]
@offirgolan  then how do I use that within template?

**Comment by offirgolan** [comment]
```hbs
{{v-get _model 'isValid'}}
{{v-get _model 'data.foo.bar' 'isValid'}}
{{input value=(mut data.foo.bar)}}
```

**Comment by zardaloop** [comment]
@offirgolan  perfect thanks. One last question when I add 
`const validatableModel = Ember.Object.extend(Validations).create(Ember.getOwner(this).ownerInjection(), { data: data });`

I get error Uncaught ReferenceError: data is not defined

which is reffering to the second data do I need to say this.get('data') maybe?

**Comment by zardaloop** [comment]
@offirgolan  awesome it worked 💃  Many thanks

**Comment by offirgolan** [comment]
@zardaloop no problem 😸
