### ISSUE TITLE
Email validation too restrictive

### ISSUE THREAD

**Issue by ronco** [offirgolan/ember-cp-validations#13]
The current email regex rejects gmail style email aliases (eg `ronco+ember@example.org`).

This can definitely be supported using a custom regex, but I wanted to offer up this alias scenario for consideration as I think it's a pretty common use case.

I think you could go much further if interested.  The specific supported syntax for the local-part of email addresses are a bit tough to divine from the various RFCs, but according to [RFC3696](https://tools.ietf.org/html/rfc3696) the following are also valid characters: `! # $ % & ' * + - / = ?  ^ _ ` . { | } ~`.

I'd be happy to provide a PR if there's interest.

**Comment by blimmer** [comment]
If it's a valid character in emails, I think we should allow it. I, personally, use this all the time to see who sold my email (e.g. spam to `ben+offendingsite@mydomain.com`)

If people want to prevent the `+`, they should make a custom validator IMO.

**Comment by offirgolan** [comment]
I agree. Ill add a more extensive email regex.

**Comment by stefanpenner** [comment]
worth a read: http://davidcel.is/posts/stop-validating-email-addresses-with-regex/

**Comment by blimmer** [comment]
I get the article's point, but when user registration is a key business metric, you really want to make sure that something stupid (like fat-fingering an email address) doesn't cause you to lose a registration. New users are valuable.

**Comment by ronco** [comment]
I think trying to get a perfect email regex would be a fool's errand.

However there is value in having a 99% solution to help out with fat-fingering and such.  Consumers of this library can always override with their own regex if they want to be vastly more permissive.  I think the current implementation is already covering 98%, it's just us techie types that really make use of the '+' in addresses.

**Comment by stefanpenner** [comment]
I think what the article really suggests is: be aware of the short-comings, and choose appropriately.
