### ISSUE TITLE
Integrating with ember data json API backend errors

### ISSUE THREAD

**Issue by riklaunim** [offirgolan/ember-cp-validations#130]
I have a form than on submit passes data to controller, controller makes a new model record, calls save().then(..., ...) and on fail it gets response.errors and passes them down to component that displays them by the fields.

Can I integrate this somehow with ember-cp-validations? DS.Error support is listed. My current frontend validation is hooked to a component but likely could also be pushed to model (or two separate validators).

**Comment by offirgolan** [comment]
You can either change your code base to follow the DS.Errors methodology or just create a custom validator.

```js
const Validations = buildValidations({
  username: validator('server-error')
})

// validators/server-error

export default BaseValidator.extend({
  validate(value, options, model, attribute) {
    // model is your component here and errors is the response.errors that was passed down
    return model.get('errors')[attribute] || true; 
  }
})
```

See docs for [custom validators](http://offirgolan.github.io/ember-cp-validations/docs/classes/Custom.html) for more details.

**Comment by riklaunim** [comment]
So if I move the validation on model then only validator('ds-error') will be needed or something more?

**Comment by offirgolan** [comment]
Yup. If your validation is on a DS.Model object and you have correctly setup the DS.Errors stuff, then it should work seamlessly

**Comment by riklaunim** [comment]
I have django-rest-framework-jsonapi backend and on .save().then(*, *) it returns the errors on fail and I used that then to set the errors on form manually.

**Comment by offirgolan** [comment]
Are you using [DS.Errors](http://emberjs.com/api/data/classes/DS.Errors.html)?

**Comment by riklaunim** [comment]
not in the manual implementation, but it seems to be there. Will try to clean that up tomorrow.

**Comment by riklaunim** [comment]
Had to modify the JSONAPIAdapter:
```
handleResponse: function(status, headers, payload) {
    if(status === 400 && payload.errors) {
      return new DS.InvalidError(DS.errorsHashToArray(payload.errors));
    } else {
      return this._super(...arguments);
    }
  }
```
Status is 400 and not 422, and also DS.errorsHashToArray had to be used or InvalidError wasn't happy with the data format.

**Comment by offirgolan** [comment]
Nice! Is the `DS Error` validator working then?

**Comment by riklaunim** [comment]
Yes. It works now :)

**Comment by offirgolan** [comment]
:smile_cat: fantastic!

**Comment by iamthearvin** [comment]
Dropping by to say thanks to @offirgolan for this. My API complies to JSON API standards but wouldn't work until I added DS.errorsHashToArray.
