### ISSUE TITLE
Is there an addError?

### ISSUE THREAD

**Issue by luisjuniorj** [offirgolan/ember-cp-validations#133]
Hi, awesome addon, i am just wondering if it has any addError or something like, i try to login, and that password are incorrect, the place for error is there, i just need to add an error and show it. The same for email uniqueness, tks.

**Comment by offirgolan** [comment]
The error message should can be accessed via

```js
model.get('validations.attrs.password.message')
```

or inside your template via

```hbs
{{v-get model 'password' 'message'}}
```
