### ISSUE TITLE
Using with BufferedProxy

### ISSUE THREAD

**Issue by elatonsev** [offirgolan/ember-cp-validations#135]
I use BufferedProxy https://github.com/yapplabs/ember-buffered-proxy on my forms for buffering changes before save. It's common practice.

Model validation doesn't work in this way, because values don't set yet. How can I use it in this situation?

**Comment by offirgolan** [comment]
Cant you mixin the validations to the object proxy? Or is that what you were doing and it still didnt work?

```js
import BufferedProxy from 'ember-buffered-proxy/proxy';

const Validations = buildValidations({...});
let buffer = BufferedProxy.extend(Validations).create();
```

**Comment by elatonsev** [comment]
Yes, I did that, but it can't extend BufferedProxy. It throws error "Uncaught TypeError: [ember-cp-validations] <(subclass of Ember.ObjectProxy):ember975> is missing a container or owner."

//factory.js line 496
// We must have an owner to be able to lookup our validators

**Comment by offirgolan** [comment]
(via README)

To lookup validators, container access is required which can cause an issue with `Ember.Object` creation if the object is statically imported. The current fix for this is as follows. 

```javascript
// models/user.js

export default Ember.Object.extend(Validations, {
  username: null
});
```

**Ember < 2.3.0-beta.1**

```javascript
// routes/index.js

import User from '../models/user';

export default Ember.Route.extend({
  model() {
    var container = this.get('container');
    return User.create({ username: 'John', container })
  }
});
```

**Ember >= 2.3.0-beta.2**

```javascript
// routes/index.js

import User from '../models/user';

export default Ember.Route.extend({
  model() {
    return User.create(
     getOwner(this).ownerInjection(),
     { username: 'John' }
    );
  }
});
```

**Comment by elatonsev** [comment]
Sorry about that, I didn't read it carefully.

Now it looks like question for guys from BufferedProxy, but maybe you can answer on it for me.

It works well with normal ObjectProxy
`let buffer = Ember.ObjectProxy.extend(Validations);`

but didn't with BufferedProxy
`let buffer = BufferedProxy.extend(Validations);`

It crashed with error "Uncaught TypeError: Cannot convert undefined or null to object" if I trying to create an object with container as first parameter.

On line
https://github.com/yapplabs/ember-buffered-proxy/blob/master/addon/mixin.js#L58

```
buffer.create(
  getOwner(this).ownerInjection(),
  {content: this.get('user')}
);
```

My Ember version is 2.4.2

**Comment by offirgolan** [comment]
@elatonsev I would open this issue on `ember-buffered0proxy` and see if they can resolve this on their end.

**Comment by blimmer** [comment]
For others who run into this, I have a PR available https://github.com/yapplabs/ember-buffered-proxy/pull/25
