### ISSUE TITLE
debounce validates validators

### ISSUE THREAD

**Issue by basz** [offirgolan/ember-cp-validations#136]
Why does debounce validate validators until the debounce timeout is hit?

If i set debounce to 500 on a validator, the validators all are deemed valid until 500 milliseconds have passed.

That allows for the user to submit (via enter) a form after every keystroke for 500 milliseconds.

**Comment by offirgolan** [comment]
Although isValid might be true, isTruelyValid will only be true once the
debounce promise has been resolved and the validator returns true.

On Sunday, March 13, 2016, Bas Kamer <notifications@github.com> wrote:

> Why does debounce validate validators until the debounce timeout is hit?
>
> If i set debounce to 500 on a validator, the validators all are deemed
> valid until 500 milliseconds have passed.
>
> That allows for the user to submit (via enter) a form after every
> keystroke for 500 milliseconds.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/offirgolan/ember-cp-validations/issues/136>.
>


-- 
Thanks,
Offir Golan

**Comment by basz** [comment]
no isTruelyInvalid?

There is no easy way to use the the not operator in handlebars attributes, is there?

**Comment by offirgolan** [comment]
https://www.npmjs.com/package/ember-truth-helpers 😁

On Monday, March 14, 2016, Bas Kamer <notifications@github.com> wrote:

> no isTruelyInvalid?
>
> There is no easy way to use the the not operator in handlebars attributes,
> is there?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/offirgolan/ember-cp-validations/issues/136#issuecomment-196209673>
> .
>


-- 
Thanks,
Offir Golan

**Comment by basz** [comment]
thx! that's helpful
