### ISSUE TITLE
question about date validator 

### ISSUE THREAD

**Issue by danielspaniel** [offirgolan/ember-cp-validations#138]
Is there a way to do a date validation like 
   this date should be 3 months ( or whatever ) before this other date? 
 In my case I have paidToDate and paidFromDate. 
   I want paidFromDate to be less than 3 months before paidToDate. The diff not so important, I just curious how to achieve this kind of custom date thing where one date depends on another and I need to calculate a spread. 

```js 
paidDateFrom: validator('date', {
  before: 'now',
  after() {
    let paidDateTo = moment(new Date(this.get('model.paidDateTo')));
    return paidDateTo.add(-3, 'month');
  }
})
```

The above was my try ( it is not working ) .. I guess because you don't support functions for after or before .. but is that a good idea?  maybe another feature to spit out? in the next release?

**Comment by offirgolan** [comment]
Hmmmm I dont know why that's not working for you because that is supported ([see here](https://github.com/offirgolan/ember-cp-validations/blob/master/tests/dummy/app/models/user-detail.js#L30-L44)).

**Comment by danielspaniel** [comment]
Yikes .. I see my mistake ... your example showed me what I have to do:
```js
paidDateFrom: validator('date', {
  before: 'now',
  after() {
    let paidDateTo = moment(new Date(this.get('model.paidDateTo')));
    return paidDateTo.add(-3, 'month').format('M/D/YYY');
  }
})
```
I forgot to return a string with the format method.  Thanks for the hint :)
