### ISSUE TITLE
There should be a way to recompute the messages

### ISSUE THREAD

**Issue by luxferresum** [offirgolan/ember-cp-validations#139]
Hello

At the moment its no good way to recompute the messages, for example when the language changes. There should be a way to do this.

At the moment I return a JSON string from `getMessageFor` and parse this later from a helper, but this is ugly as hell. There must be a better way.

**Comment by offirgolan** [comment]
If you are using ember-i18n-cp-validations or any other i18n service you can do something like this

```js
const Validations = buildValidations({
  username: validator('presence', { presence: true, dependentKeys: ['i18n.locale']})
});

export default Ember.Object.extend(Validations, {
  i18n: Ember.service.inject(),
 username: ''
});
```

**Comment by danshapir** [comment]
That sounds like a valid solution. It's very manual though. A global 'recalculate messages' event would be better. And that event can be triggered as a service. This will allow a better integration with other things as well.

**Comment by offirgolan** [comment]
If you really want to force trigger the CPs, you can do the following

```js
model.get('validations.validatableAttributes').forEach(a => model.propertyDidChange(a));
```

But that is not really recommended. I dont think that injecting your models is really a manual process. You can always create an initializer that reopens your model and injects your service for you.

**Comment by luxferresum** [comment]
Injecting the service is the easy part. But defining the `dependentKeys` on every validator seems undesirable. From API View it would be cool to define an depencencyKey on the `messages` object. But at least a way to globally define your `dependencyKey` seems necessary. Otherwise I would use my custom util instead of `validator()` that adds the `dependencyKey and internally calls `validator()`.

**Comment by danshapir** [comment]
I agree. What util are you talking about?

Again, I think that having a validation service that has an end point that can be called, and that end point will trigger revalidation of all validators seems like the best way.

**Comment by luxferresum** [comment]
>What util are you talking about?

@danshapir I would write something like this:

    //app/utils/validation.js
    import { validator as origValidator, buildValidations} from 'ember-cp-validations';
    
    export function validation(name, options) {
      options.dependentKeys = options.dependentKeys || [];
      options.dependentKeys.push('i18n.locale');
      return origValidator(name, options);
    }
    
    export buildValidations;


and then replace `import {validator, buildValidations} from 'ember-cp-validations';` with `import {validator, buildValidations} from 'myApp/utils/validation';` in all my models.


>a validation service that has an end point that can be called, and that end point will trigger revalidation

I'm not sure about this. I think it should be at messages object, because its the same logical unit. But maybe convert the messages object to a service could be a good idea.

And maybe it could be better to be able to define a dependencyProperty on that service/messages object instead of a recompute function, because of the usual benefit of CPs over observers.

**Comment by offirgolan** [comment]
Maybe when I have some time, Ill create a feature which allows you to define global props

```js
const Validations = buildValidations({...}, { foo: 'bar'});
```

But right now you can also declare default options per attribute. See [Default Options docs](http://offirgolan.github.io/ember-cp-validations/docs/modules/Advanced%20Usage.html)

**Comment by jasonmit** [comment]
Is this a real-world use-case?  You usually need to reload models, side-load new translations, perhaps load different set of templates, to recreate a full localized app state.  At that point, why not just tear the application down and reload it?

**Comment by offirgolan** [comment]
Im gonna go ahead and close this issue since global option support has been released in `v2.7.0`

**Comment by danshapir** [comment]
@offirgolan How can I use the global option? :)

**Comment by offirgolan** [comment]
You would have to inject the service into your model.

```js
const Validations = buildValidations({
  name: validator('presence')
}, {
  dependentKeys: ['i18n.locale']
});

export default DS.Model.extends(Validations, {
  name: DS.attr('string'),
  
  i18n: Ember.inject.service()
});
```
