### ISSUE TITLE
format validator type `phone` does not recognize international numbers

### ISSUE THREAD

**Issue by luxferresum** [offirgolan/ember-cp-validations#141]
Actually (almost) everything starting with a '+' and then just digits is a valid number.
This for example should definitly be a valid number: `+41123456789`.

**Comment by offirgolan** [comment]
Thanks for opening this issue! Ill resolve this once I have some time but a PR is always welcome!

**Comment by luxferresum** [comment]
Actually phone number validation is extremely hard!
a simple RegExp like `^\+{0,1}[0-9, ]*$` is the only thing that works in all cases. Maybe we could add additional tests for some country codes (like `+1`/NANP) but then we need a configuration for the default country code.

Another idea could be to move the Validator to the addon namespace and just import it from the app namespace. Then a User could extend the Validator and configure the default country code and/or add country codes. What do you think about moving the validators into the addon namespace?

**Comment by offirgolan** [comment]
I dont think that is really necessary. You can always declare your own regex via

```js
validator('format', { type: 'phone', regex: /my new phone regex/})
```

> Another idea could be to move the Validator to the addon namespace and just import it from the app namespace

All validators are imported into the app/validators folder so you are welcome to write your own by extending the one already present. For example see #125

**Comment by luxferresum** [comment]
But you can't override an existing validator.

What I want to do is this:

    import Format from 'ember-cp-validations/validatos/format';
    export Format.extend({
    ...
    })

For this you would need to place the default validators under `addon/validators/format` and place a reexport file under `app/validators/format`:

    import Format from 'ember-cp-validations/validators/format';
    export default Format;


And defining the RegExp in the validator is undesirable if you have multiple phone fields.
Also, what would you make the default setting? US? Or just allow international format as default?

Btw, it could also be desirable to switch the default based on i18n.

**Comment by offirgolan** [comment]
I dont think that's really needed. There should be nothing wrong with creating your own Format validator. You can just name it `phone` in `app/validators/phone` and write custom logic to meet your needs. 

With that, you can also return custom messages via `this.createMessage` (see internal code for format validator).

**Comment by luxferresum** [comment]
It seems like international phone number validation is not intended to be part of this addon at the moment so I close this issue.
