### ISSUE TITLE
Empty hasMany validations

### ISSUE THREAD

**Issue by richmolj** [offirgolan/ember-cp-validations#142]
Many forms will have a list of entries. Every time you add an entry, a new blank field is added.

Think of a `Product` that has a list of `Tags` - every time you add a tag, the form gives you another blank section so you can keep adding tags. Something like:

<img width="411" alt="screen shot 2016-03-15 at 11 45 55 am" src="https://cloud.githubusercontent.com/assets/55264/13787369/11055114-eab2-11e5-850d-9e29eeee2ba4.png">

However, this means adding a new "blank" association so the form field displays:

```es6
model(params) {
  this.store.findRecord('product').then((product) => {
    let tag = this.store.createRecord('tag');
    product.get('tags').addObject(tag);
  });
}
```

Let's say `Tag` validates the presence of `name`. And `Product` has a `hasMany` validation on tags. The blank tag will be invalid and our form would never submit.

Taking a page from other tools, Rails solves this scenario by [reject_if](http://api.rubyonrails.org/classes/ActiveRecord/NestedAttributes/ClassMethods.html#method-i-accepts_nested_attributes_for).

```ruby
class Product < ActiveRecord::Base
  has_many :tags
  accepts_nested_attributes_for :tags, reject_if: :all_blank
end
```

Would it be possible to add similar functionality here? Validate associated objects only if those objects are not blank. Or is there a better way to solve this problem?

**Comment by offirgolan** [comment]
When the user initially selects `+ Friend` you can choose to show the validation error if `friend.validations.isInvalid` && `friend.validations.isDirty`. You can check out the [demo app example code](https://github.com/offirgolan/ember-cp-validations/blob/master/tests/dummy/app/components/validated-input.js).

**Comment by richmolj** [comment]
Yes, but that's not the issue. The issue is the form will never submit
because validations will always fail (since there will always be an empty
'Friend'.)

**Comment by offirgolan** [comment]
Would it be possible to bind the new friend field to an external object (not inside the validated `friends` model array) then on tab out or submit you can push it to the friends object if it's valid? I dont really know that it makes much sense to place an object that will always be invalid inside a validated model array.

**Comment by richmolj** [comment]
Part of the problem there is we want to skip validation on when it's totally blank. So consider the `Friend` has  `firstName` and `lastName`. If the user has typed in `firstName`, we *do* want to run validations. In addition, I believe this would allow the form to submit, but the form would (incorrectly) show an error while submitting. This is because the `hasMany` validation would pass, but the `presence` validation on `Friend` would still fail. This would be the case even with the [same code](https://github.com/offirgolan/ember-cp-validations/blob/master/tests/dummy/app/components/validated-input.js#L38) as the dummy app, since `didValidate` and `isInvalid` would both be true. So there's non-trivial work for a fairly common use case.

Conceptually, I disagree that it doesn't make sense to add this record to the validated model array. To me it's the same as how ember-data has `isDeleted` records part of the association array as well.

It might be more helpful to propose the concept of **conditional validations**. Imagine a step-by-step wizard. After the first step, we create a record server-side in an `incomplete` state. After the second step, the record moves to `complete` state. Some Rails code might look like this:

```ruby
validates_presence_of :name
validates_presence_of :poltiical_preference, if: ->(record) { record.state == 'complete' }
```

I'd suggest something similar here, which would accommodate my original scenario as well as other state-based validations down the line. Something like:

```es6
validator('presence', {
  presence: true,
  if: function(record) {
    return record.get('firstName') || record.get('lastName');
  }
})

// or in a wizard-like scenario, something like

validator('has-many', {
  if: function(record) {
    return record.get('state') == 'complete';
  }
})
```

**Comment by offirgolan** [comment]
Ah okay I see what you mean. I believe this is already supported

```js
validator('presence', {
  presence: true,
  disabled() {
    return isEmpty(this.get('model.firstName')) && isEmpty(this.get('model.lastName'));
  }
})
```

Im currently working on global options that will help you out in this case

```js
buildOptions({
  firstName: validator('presence', true),
  lastName: validator('presence', true)
}, {
  disabled() {
    return isEmpty(this.get('model.firstName')) && isEmpty(this.get('model.lastName'));
  }
}
```

That will disable all validations if firstName and lastName are both empty.

**Comment by richmolj** [comment]
Ooh yes! Not sure how I missed this when I read through the docs. Exactly what I needed, thanks! :+1:

**Comment by offirgolan** [comment]
No problem! Sorry it took my so long to come to that solution!
