### ISSUE TITLE
ember-bootstrap

### ISSUE THREAD

**Issue by basz** [offirgolan/ember-cp-validations#144]
Hi

Would you happen to know a better way to wire up this component with ember-bootstrap?

ember-bootstrap has support for ember-validations and looks at the model.errors.myProperty array, so what I no do in my model class is something like this; 

This and some accessing some protected properties of an bootstrap component works, but feels really hacky.

```
export default Ember.Object.extend(Validations, {
  errors: {
    displayName: [],
    emailAddress: [],
    password: [],
    passwordConfirmation: []
  },
  handleErrorsForBootstrapDisplayName: function () {
    this.set('errors.displayName', [this.get('validations.attrs.displayName.message')]);
  }.observes('validations.attrs.displayName.isValid'),
  handleErrorsForBootstrapEmailAddress: function () {
    this.set('errors.emailAddress', [this.get('validations.attrs.emailAddress.message')]);
  }.observes('validations.attrs.emailAddress.isValid'),
  handleErrorsForBootstrapPassword: function () {
    this.set('errors.password', [this.get('validations.attrs.password.message')]);
  }.observes('validations.attrs.password.message').on('init'),
  handleErrorsForBootstrapPasswordConf: function () {
    this.set('errors.passwordConfirmation', [this.get('validations.attrs.passwordConfirmation.message')]);
  }.observes('validations.attrs.passwordConfirmation.message').on('init'),

  displayName: '',
  emailAddress: '',
  password: '',
  passwordConfirmation: ''
});
```

**Comment by offirgolan** [comment]
Here you go:

https://github.com/offirgolan/ember-bootstrap-cp-validations

I cooked this up kinda quickly so if you can test it out in your app and give me some feedback that would be great. Just add the following to you package.json since I didnt release it to npm yet. 

`"ember-bootstrap-cp-validations": "offirgolan/ember-bootstrap-cp-validations"`

**Comment by basz** [comment]
wauw, thanks! Seems to work nicely...

**Comment by offirgolan** [comment]
For any ember-bootstrap issue please create an issue on offirgolan/ember-bootstrap-cp-validations
