### ISSUE TITLE
Asking for `validations` triggers save in Mixin

### ISSUE THREAD

**Issue by snewcomer** [offirgolan/ember-cp-validations#149]
```
export default Ember.Component.extend(Validations, ComponentCRUD, {
  actions: {
    save() {
      const validations = this.get('validations'); //remove this line and won't hit debugger
   }
```

```
var ComponentCRUD = Ember.Mixin.create({
  actions: {
    save(model){
      debugger;
      this.attrs.save(model);
    },
....
```

Is this the desired behavior?

**Comment by offirgolan** [comment]
Any chance you can reproduce this in a demo repo so I can debug this?

**Comment by snewcomer** [comment]
I'll put it together and see if I can get to the root of it and throw it up here!

**Comment by snewcomer** [comment]
Looks like this is the line.

https://github.com/offirgolan/ember-cp-validations/blob/2154d9276c68811af439b63a588ef21095f820a7/addon/validations/factory.js#L102

Here was the test I wrote.  You can see the console logs.
https://github.com/snewcomer/ember-cp-validations/blob/master/tests/acceptance/dummy-index-test.js#L83

So this._super() is calling the _validationsClass computed on the mixin?

**Comment by offirgolan** [comment]
Thanks for setting up a reproduction of the issue. This is definitely not the desired behavior and it's pretty weird tbh. Might need some time to debug this one.

**Comment by offirgolan** [comment]
@snewcomer I dumbed this issue down and found it to be an issue with ember itself. I dont really think that this is actually the desired behavior so I went ahead and opened an issue.

emberjs/ember.js#13230
