### ISSUE TITLE
How to validate only on Save

### ISSUE THREAD

**Issue by snewcomer** [offirgolan/ember-cp-validations#150]
Looking for simpler way to display a message in a template (defined on a validator in the model) only when I click save (and not when the input is cleared out).  Right now, I have a `saved` property on the model and when I hit save, it flips the value and then triggers another property defined on the model called `nameErrorMsg` which then displays the validators msg in the template.

Haven't seen anything in the docs that provides this functionality...Or more than likely I am missing something???

//component
```
save() {
  if(this.get('model.validations.isValid')){
     ...
  } else {
    this.get('model').set('saved', true);
  }
}
```

//model
```
  saved: false,
  nameErrorMsg: Ember.computed('saved', function(){
    return this.get('validations.isValid') ? undefined : this.get('saved') ?
      this.get('validations.attrs.key.message') : undefined;
  }),

```

//template
```
              {{#if model.nameErrorMsg}}
                <div class="t-name-error error">
                  {{model.nameErrorMsg}}
                </div>
              {{/if}}

```

**Comment by offirgolan** [comment]
Do you want to only display the messages on save or only run validations on save?

**Comment by snewcomer** [comment]
That's a great point.  That is a difference that I didn't think of.  Firing only on validation (by calling a hook) seems like a great option.  I think validate sync is what I want but the second I cleared out an input field, the validation msgs appear, which makes sense based on how I implemented it (before hitting save).  Is there a library specific way to fire validations and only display a msg by calling some hook?

**Comment by offirgolan** [comment]
You can disable a validation by using the `disabled` option as well as using the `dependentKeys` to help you toggle the disabled state. In terms of displaying your error messages, you should look at the `validated-input` component in the demo app in this repo. I think what you are looking for is the use of the `hasValidated` state that the demo app uses in the main controller.

**Comment by snewcomer** [comment]
Perfect, that will work!  Any use for a `how to` in the docs?  I can throw up an example here when I get it done.

**Comment by offirgolan** [comment]
There are docs for the [disabled](http://offirgolan.github.io/ember-cp-validations/docs/modules/Validators.html#disabled) feature but as for the `hasValidated` state, that is something you currently have to keep the state for yourself. (cc @jasonmit)

**Comment by jasonmit** [comment]
(cross referencing with #113)

**Comment by offirgolan** [comment]
Im gonna go ahead and close this issue. Feel free to reopen.

**Comment by kernel-io** [comment]
I have been having issue using the disabled option as a part of the global options, for the validations to actually disable I need to add disabled to each validation. any pointers?

**Comment by offirgolan** [comment]
Any chance you can include a snippet of your model and validations?

On Sunday, April 24, 2016, kernel-io <notifications@github.com> wrote:

> I have been having issue using the disabled option as a part of the global
> options, for the validations to actually disable I need to add disabled to
> each validation. any pointers?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/offirgolan/ember-cp-validations/issues/150#issuecomment-214075781>
>


-- 
Thanks,
Offir Golan

**Comment by kernel-io** [comment]
my model is just a POJO.

Here is the complete code...

````javascript
import Ember from 'ember';
import { validator, buildValidations } from 'ember-cp-validations';
import BufferedProxy from 'ember-buffered-proxy-modified/proxy';

const Validations = buildValidations({  
  'companyName': validator('presence', {
    presence: true,
    dependentKeys: ['saveAttempted'],
    disabled() { return !this.get('model.saveAttempted')}
  }),
  'email': validator('format', {
    type: 'email',
    dependentKeys: ['saveAttempted'],
    disabled() { return !this.get('model.saveAttempted')}
  }),
  'password': validator('presence', {
    presence: true,
    dependentKeys: ['saveAttempted'],
    disabled() { return !this.get('model.saveAttempted')}
  })  
});

let UserBuffer = BufferedProxy.extend(Validations)

export default Ember.Component.extend({  
  user: null,

  userBuffer: Ember.computed('user', function() {
    return UserBuffer.create(
      getOwner(this).ownerInjection(),
      { content: this.get('user') }
    )
  }),

  actions: {
    submit(e) {      
      let buffer = this.get('userBuffer')
      console.log(buffer.get('buffer'))
      buffer.set('saveAttempted', true);
      buffer.applyBufferedChanges()
    }
  }

});

````

I'm new to using the bufferedproxy, so probably using that wrong 🚽

**Comment by offirgolan** [comment]
Have you tried the global `disabled` option without buffered proxy?

**Comment by kernel-io** [comment]
I tried it with buffered proxy, but not without yet. I will try and let you know :)

**Comment by offirgolan** [comment]
@kernel-io ill take a look at this some time this week.

**Comment by anvyst** [comment]
@kernel-io, 

In my case, validating POJO's within the component, global setup worked this way:
```javascript
//global setup
const Validations = buildValidations({
  'user.firstName': validator('presence', true),
  'user.lastName' : validator('presence', true),
}, {
  disabled: Ember.computed('model.saveAttempted', function(){
    return !this.get('model.saveAttempted');
  })
});

export default Ember.Component.extend(Validations, {
   user: { firstName: '', lastName: '' },
    saveAttempted: false,
    isUserValidated: Ember.computed.alias('validations.isValid'),
    actions: {
      pressedSave() {
        this.set('saveAttempted', true);
        console.log( this.get('isUserValidated') );
      }
    }
});
```

addon version: **3.0.0-beta.2**

**Comment by omairrazam** [comment]
Hi. I faced the same issue with 4.0.0-beta.3

if computed is true for the first time and then turned false, validation switch correctly but after trying to return true again from false (based upon the status property), it doesn't recompute.

Any help?


@offirgolan
