### ISSUE TITLE
Issue with Validating inside of components

### ISSUE THREAD

**Issue by jwright04** [offirgolan/ember-cp-validations#151]
I'm certain this is something I'm just doing wrong, but I'm trying to figure out how I can validate inside of a nested component (if you have an example of how nested components are beling validated that would help tremendously).

Currently when validating a component, i do something like:

```
{{#path.validate-input model=model valuePath="firstName"}}
     {{input type="text" value=model.firstName placeholder="First Name" name="first-name"}}
{{/path.validate-input}}
```

The above block ^ is currently validating with no problems.  When I do something like what i have below:

```
<!-- main-form.hbs-->
{{#path.validate-input model=model valuePath="firstName"}}
     {{input type="text" value=model.firstName placeholder="First Name" name="first-name"}}
{{/path.validate-input}}

<!-- sign-up component has validation within that component-->
{{new.sign-up model=model.signUp}}
```

The `sign-up` component above ^ seems to ignore the validation.  The contents of this component are shown below:

```
<!-- -sign-up.hbs -->
{{#path.validate-input model=model valuePath="username"}}
    {{ input placeholder="Username" value=model.username name="username" id="username" type="text"}}
{{/path.validate-input}}
```
When i attempt to submit an empty form field, all fields in the `main-form.hbs` will check validation, but all of the fields inside of of the `sign-up` component will remain un checked.

Would you happen to have any examples of how you're currently handling the validations of nested components?

**Comment by jwright04** [comment]
I'm going to close this out, I ended up having to pass a custom validation check into the actual component to make this work.  huge oversight on my part.

**Comment by offirgolan** [comment]
:+1: Glad you were able to fix it! Thanks for updating the issue :smile:
