### ISSUE TITLE
What is causing "model.validate is not a function" ?

### ISSUE THREAD

**Issue by dant00ine** [offirgolan/ember-cp-validations#153]
Hey guys, 

I am trying to have the validation action fire from a route with the following code: 

```
import Ember from 'ember';
import AuthenticatedRouteMixin from 'ember-simple-auth/mixins/authenticated-route-mixin';

export default Ember.Route.extend(AuthenticatedRouteMixin, {

  store: Ember.inject.service(),

  session: Ember.inject.service(),

  model(params){
    return this.store.createRecord('info');
  },

  showAlert: false,
  isRegistered: false,
  showCode: false,
  didValidate: false,

  actions: {
    submit() {
      var model = this.get('model');
      model.validate().then(({
        model, validations
        }) => {
        if (validations.get('isValid')) {
          this.setProperties({
            showAlert: false,
            isRegistered: true,
            showCode: false
          });
        } else {
          this.set('showAlert', true);
        }
        this.set('didValidate', true);
      }, (errors) => {
        console.log(`errors from failed validation: ${errors}`);
      });
    }
```

But I am getting this error:

`Uncaught TypeError: model.validate is not a function` 

I am defining validations in the model, but am wondering if maybe I didn't set up the addon correctly, or if there is some config work still needing to be done.

Edit: here's my model

```
import Ember from 'ember';
import DS from 'ember-data';
import {validator, buildValidations} from 'ember-cp-validations';

const Validations = buildValidations({
  businessName: validator('presence', true),

  owner: {
    description: 'owner',
    validators: [
      validator('presence', true),
      validator('length', {
        max: 15
      })
    ]
  }
});

export default DS.Model.extend(Validations, {
  'businessName': DS.attr('string'),
  'owner': DS.attr('string')
});
```

**Comment by blimmer** [comment]
Can we see your model?

**Comment by dant00ine** [comment]
I think the problem is that I bring in the model at the route level but the child component (where the input exists) doesn't have access to that model

**Comment by dant00ine** [comment]
Confirmed. This was happening because I forgot to pass the model to a child component. Thanks for the help Blimmer.

**Comment by dant00ine** [comment]
so in the submit action of the Route, after setting

`let model = this.get('model')`

if I console log model I see: 

```
function model(params) {
      return this.store.createRecord('bizinfo');
    }
```

Probably a pretty stupid mistake. Am I missing something with setting the model? Thanks again >.>

**Comment by dant00ine** [comment]
Fixed by using `this.currentModel`
Really sorry to bother you twice guys. I'm done now.
Thanks!

**Comment by blimmer** [comment]
No problem - glad you got it figured out!

**Comment by JasonLin37** [comment]
Hi guys, really like this addon, but I'm running into some trouble validating on submit.

I initially had the same error as above but I got around it by passing the model into the submit action, like this: {{action 'submit' model}}
 
      `actions: {
		submit: function(model) {
	      model.validate().then(({
	        model,
	        validations
	      }) => {
	        if (validations.get('isValid')) {
	          this.setProperties({
	            showAlert: false,
	          });
	        } else {
	          this.set('showAlert', true);
	        }
	        this.set('didValidate', true);
	      }, (errors) => {

	      });
		},
	},`

and here is my model,

    import DS from 'ember-data';
    import Ember from 'ember';
    import {
      validator, buildValidations
    } from 'ember-cp-validations';

    const { computed } = Ember;
    const { attr } = DS;

    const Validations = buildValidations({
      fullName: {
        validators: [
          validator('presence', true)
        ]},
      email: {
        validators: [
          validator('presence', true),
          validator('format', { type: 'email' })
        ]
      },
      tel: {
        validators: [
          validator('presence', true),
          validator('format', { type: 'tel' })
        ]
      },
      emailConfirmation: {
        validators: [
          validator('confirmation', {
            on: 'email',
            message: 'Email addresses do not match',
            debounce: 500}),
        ]
      },
      city: validator('presence', true),
      state: validator('presence', true),
      zipCode: validator('presence', true),
    });

    export default DS.Model.extend(Validations, {
      fullName: DS.attr('string'),
      email: DS.attr('string'),
      tel: DS.attr('string'),
      comment: DS.attr('string'),
      city: DS.attr('string'),
      state: DS.attr('string'),
      zipCode: DS.attr('number'),
    });

but for some reason I there just doesn't seem to be a response when I click submit, I was trying this with all fields left empty so it will tell me to fill out all required info, but nothing!

Any help will be appreciated.

**Comment by Falibur** [comment]
I do have this same issue, only that I don't use a route which holds the currentModel property but a component. What else could I be doing wrong?

**Comment by offirgolan** [comment]
@Falibur please create a new issue with more details about your particular case.

**Comment by Kamill90** [comment]
Sure, here is repo. 
Only with register-form component and validation. 
Have no idea what is wrong with it.
