### ISSUE TITLE
Question: correct way of checking for relationships?

### ISSUE THREAD

**Issue by gzurbach** [offirgolan/ember-cp-validations#155]
First off, great library! I am switching a pretty big app from `ember-validations` (deprecated) to `ember-cp-validations` and it's been great so far!

I read the docs a couple times but I'm still confused on what is the correct way to check for the presence of a relationship.

```javascript
// models/address.js
export default DS.Model.extend({
  address1: DS.attr('string'),
  address2: DS.attr('string'),
  zipCode: DS.attr('string'),
  city: DS.attr('string'),
  state: DS.attr('string'),
  country: DS.belongsTo('country', { async: true })
});
```
I currently validate this way and it works:
```javascript
// validations/models/address.js
export default buildValidations({
  'country.id': validator('presence', true)
});
```
My understanding is that I could leverage the `dependent` validator (or other?) to do the same thing. But I'm not sure how to use it. Could you give me an insight? Thanks!

**Comment by offirgolan** [comment]
Hi there! Im very happy to hear you are making the switch! I think what you are looking for (in this case) is the `belongs-to` validator. You can do something like this:

```js
// validations/models/address.js
export default buildValidations({
  'country': validator('belongs-to')
});

// models/address.js
export default DS.Model.extend(Validations, {
  address1: DS.attr('string'),
  address2: DS.attr('string'),
  zipCode: DS.attr('string'),
  city: DS.attr('string'),
  state: DS.attr('string'),
  country: DS.belongsTo('country', { async: true })
});


// validations/models/country.js
export default buildValidations({
  'id': validator('presence', true),
  'name': validator('presence', true)
});


// models/country.js
export default DS.Model.extend(Validations, {
  name: DS.attr('string')
});
```

Then you can access `country` validations via

`address.get('validations.attrs.country.isValid')`

and to grab specific validations off of `country`

`address.get('country').get('validations.attrs.name.isValid')`

**Comment by gzurbach** [comment]
Appreciate the help, that's what I needed. Thanks for your quick answer!

**Comment by offirgolan** [comment]
Np! 😸

On Saturday, April 9, 2016, Guillaume Zurbach <notifications@github.com>
wrote:

> Appreciate the help, that's what I needed. Thanks for your quick answer!
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/offirgolan/ember-cp-validations/issues/155#issuecomment-207848502>
>


-- 
Thanks,
Offir Golan

**Comment by brayancastrop** [comment]
By doing this
```
// validations/models/country.js
export default buildValidations({
  'id': validator('presence', true),
  'name': validator('presence', true)
});
```
are not we making any new country record invalid just by validating the presence of the id?
i think what's needed here is to be able to get an isInvalid on the address model when there is no country associated and find an error in the address validations.errors for not having a country present
