### ISSUE TITLE
validate ember-power-select

### ISSUE THREAD

**Issue by epyx25** [offirgolan/ember-cp-validations#156]
First of all, great library!

I have thid models:

**content**
```Javascript
const Validations = buildValidations({
  name: validator('presence', true)
});

export default DS.Model.extend(Validations, {
  name: DS.attr('string')
});
```

**action**
```Javascript
const Validations = buildValidations({
  name: validator('presence', true),
  content: validator('belongs-to')
});

export default DS.Model.extend(Validations, {
  name: DS.attr('string'),
  content: DS.belongsTo('content')  
});
```

I have a **form-group** component, which wraps the different form controls. Its job to handle the validations.

**form-group**
```Javascript
  init: function() {
    this._super(...arguments);
    var valuePath = this.get('property');
    defineProperty(this, 'validation', computed.oneWay(`model.validations.attrs.${valuePath}`));
    defineProperty(this, 'value', computed.alias(`model.${valuePath}`));
  }
```

in a template:
```HBS          
{{#form-group model=action property="name" label="Action Name"}}
  {{bs-input value=action.name}}
{{/form-group}}

{{#form-group  model=action property="content" label="Content"}}
  {{#power-select 
    options=contents
    selected=action.content
    onchange=(action (mut action.content)) as |content|
  }}
    {{content.name}}
  {{/power-select}}
{{/form-group}}
```
Now if I log `validation.isValid` in `form-group.hbs` for a fresh created action model, it will give `false` in case of `action.name` but `true` for `action.content`.

I have made a repository with all the codes:  https://github.com/epyx25/validation-test

**Comment by offirgolan** [comment]
I see you are using ember-bootstrap. I think you might also want yo use [ember-bootstrap-cp-validations](https://github.com/offirgolan/ember-bootstrap-cp-validations)

As for your model validations, The validation for the `content` model will always be true since im assuming content.name will always have a value (im assuming this since you are using a select component). 

If you want to validate that action.content must exist, i think you should do something like this:

**action**
```Javascript
const Validations = buildValidations({
  name: validator('presence', true),
  content: [
    validator('presence', true),
    validator('belongs-to')
  ]
});

export default DS.Model.extend(Validations, {
  name: DS.attr('string'),
  content: DS.belongsTo('content')  
});
```

**Comment by epyx25** [comment]
Thanks for the quick answer, it worked!
I will take a look at **ember-bootstrap-cp-validations**.

**Comment by epyx25** [comment]
@offirgolan one more question: what does `validation.isDirty` represent?
https://github.com/offirgolan/ember-cp-validations/blob/master/tests/dummy/app/components/validated-input.js#L37-L38

In a new action model name.isDirty is false, but content.isDirty is true.

**Comment by offirgolan** [comment]
http://offirgolan.github.io/ember-cp-validations/docs/classes/ResultCollection.html#property_isDirty
