### ISSUE TITLE
`alias` validator

### ISSUE THREAD

**Issue by gustaff-weldon** [offirgolan/ember-cp-validations#160]
Recently, I found myself needing an `alias` validator. It copies first error message from an `aliased` field to another it is bound to (similar to how `ds-error` copies error from `model.errors.${attr}`). 

Internally it's very much like  `dependent` validator because it depends on  `validations.attrs.${alias}.isTruelyValid`, but unlike `dependent` it copies error message from
`validations.attrs.${alias}.messages.firstObject` 

Intended usage:
```
{
    date: [
        validator('ds-error')
    ],
    dateFormatted: [
        validator('alias', {
            alias: 'date',
        })
    ]
}
```

The example use case I had was: 
UI form is working on computed property named `dateFormatted`, which depends on `date`. 
Raw value of `date` is never displayed nor edited directly by the user. 
When sending payload to server, `date` is sent and all errors returned by server are assigned to `date` model attribute and those should be displayed under `dateFormatted`.

Not sure, how common is my use case, but I would like to share how I wanted to solve this, how I actually solved that (see next comment), and maybe it would turn out that such validator could be built into cp-validations.

**Comment by gustaff-weldon** [comment]
Solution attempts:

1) FAILED: Establishing dependency on `validations.attrs.${alias}.isTruelyValid` in `processOptions`
I have tried to add in `processOptions` a custom dependent key for aliased validations like so:

```
processOptions() {
    let
        options = this._super(),
        alias = options.alias

    options.dependentKeys = options.dependentKeys || []
    options.dependentKeys.push(`validations.attrs.${alias}.isTruelyValid`)

    return options
}
```

That does not work since, the validation `dependentKeys` are evaluated before validator constructor is called (see https://github.com/offirgolan/ember-cp-validations/blob/v2.7.0/addon/validations/factory.js#L283 and 
https://github.com/offirgolan/ember-cp-validations/blob/v2.7.0/addon/validations/factory.js#L287 respectively). So, my `processOptions` was adding a key, but it was never used, it was too late.

I was surprised, 'cause I expected that validators could add sth to `options` before they are further processed.

So, I have checked how cp-validations handle `dependent` or `belongs-to` and I turns out there's a special code in `getCPDependentKeysFor` that adds the dependent keys by hand eg. https://github.com/offirgolan/ember-cp-validations/blob/v2.7.0/addon/validations/factory.js#L384

So, effectively, my validator would have to get such special handling as well.

2) WORKS: Establishing dependency on `validations.attrs.${alias}.isTruelyValid` in config object passed to  `buildValidations`
 A remedy to #1 is to pass the dependent key in config like so:

```
{
    date: [
        validator('ds-error')
    ],
    dateFormatted: [
        validator('alias', {
           alias: 'dateBirth',
           dependentKeys: ['validations.attrs.dateBirth.isTruelyValid']
        })
    ]
}
```

That works, but I find it very verbose and developer unfriendly.

3) WORKS: Extending `dependent` validator with `alias` option. (requires cp-validations >-= 2.7)

In order to benefit from special handling that `dependent` validator receives in `factory.js` I have extended it with an `alias` option:
```
import Dependent from 'ember-cp-validations/validators/dependent'

export default Dependent.extend({
    validate(value, options, model) {
        const result = this._super(...arguments);

        if (typeof result === 'string' ) {
            if (options.alias) {
                return this.model.get(`validations.attrs.${options.alias}.message`);
            }
            return result;
        }
        return true;
    }
});
```

Now the usage look like:
```
        validator('dependent', {
            alias: 'hiredAt', // custom option to copy messages from aliased field
            on: ['hiredAt']
        })
```
Not quite what I wanted but close. That's what I settled on for now.

Personally, I'd prefer to use the simple definition described in ticket desc. With current `factory.js` logic, that would be only possible with built in `alias` validator.

**Comment by gustaff-weldon** [comment]
On a final note. I was wondering about a solution where instead calculating `dependentKeys` statically, those could be extracted from instantiated validators processed options.

Instead:
```
function createCPValidationFor(attribute, validations) {
  const dependentKeys = getCPDependentKeysFor(attribute, validations);

  return computed(...dependentKeys, cycleBreaker(function () {
    const model = get(this, '_model');
    const validators = getValidatorsFor(attribute, model);
```
do sth like:
```
function createCPValidationFor(attribute, validations) {
  const validators = getValidatorsFor(attribute, model);
  const dependentKeys = getCPDependentKeysFor(attribute, validators);

  return computed(...dependentKeys, cycleBreaker(function () {
    const model = get(this, '_model');
```
With that being possible, all sort of dependent validators could be written outside of `cp-validations`
and the custom validators handling code could be moved to respective validators `processOptions` function

**Comment by offirgolan** [comment]
Thanks for opening up this request @gustaff-weldon :smile_cat: 

@stefanpenner @rwjblue @blimmer what do you guys think of this use-case? I think it might be a nice addition. Either create a whole new alias validator or add an option on `dependent` validator to do this.

> On a final note. I was wondering about a solution where instead calculating dependentKeys statically, those could be extracted from instantiated validators processed options.

The reason we dont already do this is because we have no access to the owner/container outside of the CP.

**Comment by blimmer** [comment]
I think this is a totally valid use case and something I've run into before. I'll use ember moment to create a computed property on the model, but serialize the real date or time to the server. My only concern is with returning the `firstObject` message. Why not return all the messages?

**Comment by offirgolan** [comment]
@blimmer I agree. Ill see what I can do to make this happen :smile:

**Comment by gustaff-weldon** [comment]
@blimmer My understanding was that up until now, validators were expected to return one validation value, I totally agree that full-fledged `alias` would copy all errors (type and message)

@offirgolan Thanks for taking your time to implement this!

**Comment by offirgolan** [comment]
Just had a shower thought...

@gustaff-weldon @blimmer is this validator needed anymore after the implementation of the `value` option? (see #171)

**Comment by blimmer** [comment]
I think strictly speaking `value` can do everything `alias` does. The biggest advantage I see is that the `alias` validator automatically will setup invalidations for you.
