### ISSUE TITLE
Feature: Allowing attribute to be specified in options

### ISSUE THREAD

**Issue by aaronbhansen** [offirgolan/ember-cp-validations#166]
We ran into a situation where we would like the validator to be tied to a specific property on the model, but we need the value passed into the validator to be based on a different related property. I didn't see a way in the code that would allow today, so I wanted to throw the idea out there.

A example could be something like (they must make 3 selections)

```
const Validations = buildValidations({
  selections: {
    description: "Order Selections",
    validators: [
      validator('ds-error'),
      validator('has-many'),
      validator('number', {
        lte: 3,
        attribute: 'selections.length'
      })
    ]
  }
})
```

This would allow us to group validation errors to display in the UI to be based on a single property, but allow the value passed into some of the validators to be based on a different attribute than the main attribute.

Is there way to do this today, if not, something you would be open to?

**Comment by offirgolan** [comment]
In the example above you can just do

```
const Validations = buildValidations({
  selections: {
    description: "Order Selections",
    validators: [
      validator('ds-error'),
      validator('has-many'),
      validator('length', { max: 3 })
    ]
  }
})
```

But I think what your'e looking for is #161 :smile:

**Comment by aaronbhansen** [comment]
Yeah my example wasn't perfect, but easiest to explain :) I saw the alias ticket, but it felt different. Alias felt more of pulling in errors from a different property all together. In my example I want to have a different validation value (attribute) passed in to validate() thats maybe a computed property.  That helps keep all validates for a property under a single attribute. Alias would probably work, but then I feel like tracking validations could get more complex if you had several alias validations. 

When we used to use ember validations, we would run into this situation, where the value to validate on maybe needed to change based on other properties, but it was still related or validating on the main property. Maybe alias would work, just felt like a different use case.

**Comment by aaronbhansen** [comment]
I was also hoping this would be much easier to implement. Possibly change this [line](https://github.com/offirgolan/ember-cp-validations/blob/master/addon/validations/factory.js#L322) just to 
```
validator.validate(get(model, options.attribute || attribute), options, model, attribute);
```

**Comment by offirgolan** [comment]
Ah I see what you mean. Ill explore this more :smile_cat:
