### ISSUE TITLE
validate on a generic property

### ISSUE THREAD

**Issue by Jordan4jc** [offirgolan/ember-cp-validations#172]
Is there a way I can have a validator validate on a generic property being true or false?

I have a `ccNumber` validation that should be present and also needs to be a valid credit card number. To determine that, I'm using Stripe's jQuery payments plugin that will format an input to accept a credit card number and I can also validate that the number meets their built in credit card regex. When I type in this input my component sets a `ccNumberValid` property from true to false depending on if the entered number passes the Stripe credit card validator.

So I thought I could have something like

```
ccNumber: [
    validator('presence', true),
    validator('dependent',{on:['ccNumberValid']})
  ],
```

But I get

`Uncaught Error: Assertion Failed: Cannot call get with 'isTruelyValid' on an undefined object.`

Which I assume is because there is not a validator in my `Validations` object for the `ccNumberValid` property, this is just a normal property on my component.

Not sure if I can make a custom validator to do this, or even where I would start with that route.

**Comment by offirgolan** [comment]
As of right now, until #171 gets merged, your best solution would be to create a custom validator.

```js
// validators/valid-cc.js
export default BaseValidator.extend({
  validate(value, options, model) {  
    return model.get('ccNumberValid') ? true : 'Invalid credit card';
  }
})
  
  
// model/foo.js
const Validations = buildValidations({
  ccNumber: [
    validator('presence', true),
    validator('valid-cc',{ dependentKeys: ['ccNumberValid'] })
  ]
})
```

For more info, check out the [custom validator docs](http://offirgolan.github.io/ember-cp-validations/docs/classes/Custom.html)

**Comment by offirgolan** [comment]
Im gonna go ahead and close this issue. Feel free to reopen if you need any more help 😸
