### ISSUE TITLE
Allow messages.js to be places in the app/validators folder of an addon

### ISSUE THREAD

**Issue by jnfingerle** [offirgolan/ember-cp-validations#178]
Hi,

we're using ember-cp-validations with custom validators and with our own messages for the bundled validators. After factoring this out to an addon, we still have to provide thoses messages in the app's validators directory. Ok, it's only an import, still it would be great if we could place it into the addons app/validators folder instead.

Cheers, jnfingerle

**Comment by offirgolan** [comment]
That should be possible, in your 3rd party addon that holds the `messages` files, put it in `app/validators/messages.js` and add the following to the `package.json`

```json
"ember-addon": {
    "configPath": "tests/dummy/config",
    "after": "ember-cp-validations"
}
```

**Comment by jnfingerle** [comment]
Works, thanks a lot.
