### ISSUE TITLE
belongs-to validator returns true

### ISSUE THREAD

**Issue by IAmJulianAcosta** [offirgolan/ember-cp-validations#179]
Oversimplified example of the issue:

`models/user.js`
```
const Validations = buildValidations (
    {
        category  : validator ('belongs-to')
    }
);
export DS.Model.extend (
    validations,
    {
       category           : DS.belongsTo ('category', {async : true}),
    }
);
```

`components/component.js`
```
componentInit : Ember.on (
			'init',
			function () {
				let store    = this.get ("store");
				let user = store.createRecord (
					'user'
				);
				console.log (user.get ("validations.attrs.category.isValid")); //true 
			}
		),
```

If my model doesn't have any relationship, why does it validates as true?

**Comment by offirgolan** [comment]
It returns true because it has nothing to validate. I think what you're looking for is this:

```js
const Validations = buildValidations (
    {
        category  : [ validator('presence', true), validator('belongs-to') ]
    }
);
```

**Comment by IAmJulianAcosta** [comment]
Does `belongs-to` validate if the relationship's model is valid too?

**Comment by offirgolan** [comment]
All belongs-to does is create a link from the relational models's validations to the current one.

**Comment by IAmJulianAcosta** [comment]
Ohhh get it, thanks! Closing

**Comment by IAmJulianAcosta** [comment]
@offirgolan does `model.get('validations.attrs.category.name.isValid')` should work?

**Comment by offirgolan** [comment]
Nope that wouldnt work. You would need to do

`model.get('category.validations.attrs.name.isValid')`

**Comment by IAmJulianAcosta** [comment]
I'm modifying your example, but I can't understand how `isDirty` works.

`model.get('validations.attrs.category.isValid')` returns true, but `model.get('validations.attrs.name.isValid')` returns false, in a new model. Why does this happen?
