### ISSUE TITLE
show async validation example

### ISSUE THREAD

**Issue by stefanpenner** [offirgolan/ember-cp-validations#18]
something quick and dirty to demonstrate how one would integrate with a foreign backend for some validation.

**Comment by offirgolan** [comment]
Added an async example to the readme [here](https://github.com/offirgolan/ember-cp-validations/commit/73fd053678b3ce463ac781f2928f701c9108c81e#diff-04c6e90faac2675aa89e2176d2eec7d8R428). Is that what you mean?
