### ISSUE TITLE
Misleading Documentation

### ISSUE THREAD

**Issue by jamiechong** [offirgolan/ember-cp-validations#180]
Just a heads from a user who has fresh eyes on this project:
I'm trying to get a feel for your addon and I see things in the documentation like: 

`validator('no-whitespace-around')`

And I'm lead to believe that this validator is built-in, but after some searching I discover it's not. It might be worth changing this specific example to: 

`validator('some-custom-validator')`

**Comment by blimmer** [comment]
Will you please put together a PR with the changes you're thinking? I agree that it can be confusing!
