### ISSUE TITLE
Working example with all the files?

### ISSUE THREAD

**Issue by adityasingh-ruckus** [offirgolan/ember-cp-validations#181]
Hi,

I installed this addon in my project but it isn't working like it was shown in the demo.
I can't get my head around on what it is that I am missing, I would really appreciate if somebody can give a link to a small ember app where this is implemented with the source code.

Thanks,
Aditya Singh

**Comment by offirgolan** [comment]
Hi there! Im sorry you are running into some issues! You can check out the full source for the demo app [here](https://github.com/offirgolan/ember-cp-validations/tree/master/tests/dummy/app). If you have more specific questions, feel free to ask here or open another issue.

**Comment by adityasingh-ruckus** [comment]
Thank you so much. I am able to integrate it with my code now. :)

The only problem which I see is that I was thinking it will probably be a plug and play solution, like if I just want to validate a simple form, why do I need to have 3 models for it? 

Thanks for your quick help.

**Comment by blimmer** [comment]
@adityasingh-ruckus it's hard to provide any feedback because we don't know what your situation looks like. Perhaps create some sample code or give us a more specific example?

**Comment by adityasingh-ruckus** [comment]
Hi @blimmer ,
Sorry for the late response, I was on a vacation.
I have implemented it across my application. Its working fine, except for the fact that I can't find any support to integrate select and tag inputs.

Is there something which I can use?

Thanks

**Comment by blimmer** [comment]
Feel free to fork and use this repo https://github.com/blimmer/ember-cli-example-app-for-github to commit an example.

**Comment by offirgolan** [comment]
Im gonna go ahead and close this issue. Feel free to reopen if the solution above did not solve your problem. 😺
