### ISSUE TITLE
isDirty validation with non models

### ISSUE THREAD

**Issue by IAmJulianAcosta** [offirgolan/ember-cp-validations#183]
Hi! I'm trying to use `isDirty` with a regular object, not a model, but I found this:

```
//result.js 61

// Check default model values
      if ((0, _emberCpValidationsUtilsUtils.hasEmberData)() && model instanceof self.DS.Model && canInvoke(model, 'eachAttribute')) {
```

It validates if `model` is a `DS.model`. Is possible to use this function with a component or another class?

**Comment by offirgolan** [comment]
`isDirty` works on all objects. The only difference is that for `ember-data` models it checks to see if you have a defaultValue set to use that as a reference. For regular `Ember.Object` instances, it assumes that any attribute that is not `null` or `undefined` is dirty.

**Comment by offirgolan** [comment]
Im gonna go ahead and close this issue. Feel free to reopen if the solution above did not solve your problem. 😺

**Comment by Allariel** [comment]
Hi guys! Could you tell me, please? I use the advanced validation (http://offirgolan.github.io/ember-cp-validations/docs/modules/Advanced.html) for some edit form. How can I use `validations.isDirty` property for it? I can't use DS.Model...
