### ISSUE TITLE
Not validating the first time we load a model

### ISSUE THREAD

**Issue by nbehboudi** [offirgolan/ember-cp-validations#187]
I have put all my validations on model. The very first time that I load the page some of the fields are empty but I dont want that page to load with the error message on that (currently as soon as I load the page it apears with error msg). Has anyone have any idea what I should do?

**Comment by offirgolan** [comment]
You can take a look on how it's done in the demo app via the [validated-input component](https://github.com/offirgolan/ember-cp-validations/blob/master/tests/dummy/app/components/validated-input.js)

**Comment by nbehboudi** [comment]
I have those already but still not sure how I can use it on template to hide it as the page loads and shows when some activity has been done on the page? (clicking the save button?)

**Comment by jelhan** [comment]
You should use a form component which shows validation errors only if there has been user interaction. There are several out in the wild. Have a look at https://emberobserver.com/categories/forms.

**Comment by offirgolan** [comment]
@nbehboudi what you are looking for is not in the scope of this addon. There are many projects out there (as @jelhan noted) that can help you with what you are looking for. Im gonna go ahead and close this issue. Feel free to reopen if anything else comes up.
