### ISSUE TITLE
Presence only if another field is filled in

### ISSUE THREAD

**Issue by Jordan4jc** [offirgolan/ember-cp-validations#188]
I'm having a hard time figuring out how I would make this work.

I have a `name` property that I want to validate to be present and not blank, but I on'y require this property to be present and not blank if a `phone` property is present. If the `phone` property is not filled in then I want to allow the `name` property to be blank.

I see the dependent validation but I'm not sure if that can be combined with the presence the way I'm trying to use it.

**Comment by offirgolan** [comment]
```js
validator('presence', {
  presence: true,
  dependentKeys: ['phone'],
  disabled(model) { return !Ember.isPresent(model.get('phone')) }
});
```

**Comment by offirgolan** [comment]
Im gonna go ahead and close this issue. Feel free to reopen if the solution above did not solve your problem. 😺

**Comment by Jordan4jc** [comment]
Sorry I got taken away from getting this to work so wasn't able to test this code until now.

I'm trying to get something like the working where I have a service that has a `chosenCard` property on it,  and I only want to force a credit card field to validate when there is no card chosen from a list of available ones.

    validator('presence', {
        presence: true,
        dependentKeys: ['creditcards.chosenCard'],
        disabled(creditcards) { return creditcards.get('chosenCard'); }
    })

`creditcards` is the service name injected into the component, but I'm getting an error in the console

`Uncaught TypeError: Cannot read property 'get' of undefined`

**Comment by offirgolan** [comment]
In your model you need to inject the `creditCards` service.

```js
export default DS.Model.extend({
  creditCards: Ember.inject.service()
});
```

Then your validator's disabled function will look like this:

```js
    validator('presence', {
        presence: true,
        dependentKeys: ['creditcards.chosenCard'],
        disabled(model) { return Ember.isNone(model.get('creditcards.chosenCard')); }
    })
```

**Comment by Jordan4jc** [comment]
I'm not adding these validations to a model though I'm adding them to a component, the `creditcards` service is injected on the component the validations are injected on

**Comment by offirgolan** [comment]
@Jordan4jc the solution will be the same. In the `disabled` function, `this.get('model')` === component

**Comment by Jordan4jc** [comment]
It doesn't seem to be working, I can log it but maybe I'm just getting confused how this is supposed to be done.

So this should disable if a card is chosen and it doesn't equal 'addCard', otherwise the format should validate the value.

I'm using the format validator with a regex btw not presence.

```
dependentKeys: ['creditcards.chosenCard'],
disabled() {
    return this.get('model.creditcards.chosenCard') && this.get('model.creditcards.chosenCard') !== 'addCard';
}
```

That's what I have tried, am I doing the conditionals wrong? When I change the `chosenCard` from a card to `addCard` it's not properly changing it's valid state. I can see by using the `v-get` helper that is's always false even if I have a card chosen.

**Comment by Jordan4jc** [comment]
This doesn't seem to be working, here's what I'm trying

```
    validator('format', {
      allowBlank: true,
      regex: /^[\d\s]{12}/,
      dependentKeys: ['creditcards.chosenCard'],
      disabled() {
        return this.get('model.creditcards.chosenCard') && this.get('model.creditcards.chosenCard') !== 'addCard';
      }
    }),
```

using `v-get` I can see it's always false even if I have a `choseCard` set and it's not `addCard`

**Comment by Jordan4jc** [comment]
Took the `allowBlank` out and all is working.

**Comment by offirgolan** [comment]
Awesome! Glad you were able to figure it out 😸
