### ISSUE TITLE
Deleting component with a validated-input inside it causes model to equal null in factory.js

### ISSUE THREAD

**Issue by ewalti** [offirgolan/ember-cp-validations#190]
I ran in to an interesting problem yesterday trying to implement `ember-cp-validations` and the `validated-input` from the dummy app. 

My scenario:

I have a model that is being passed down through a few levels of components. The component in question has a `validated-input` inside it, ie:

```hbs
// rule-item.hbs
{{#each rules.conditionGroups as |conditionGroup|}}
  {{some-component conditionGroup=conditionGroup}}
{{/each}}
```

and 

```hbs
// some-component.hbs
{{validated-input model=this valuePath='conditionGroup.name' placeholder='Name' class="condition-group-name-input"}}
```

I'm setting up the validations on the `some-component.js` via:

```javascript
const Validations = buildValidations({
  'conditionGroup.name': validator('presence', true)
});
```

This works perfectly well with the exception of: condition groups can be added and deleted. When I attempt to delete one from the `rules.conditionGroups`, I get the following error:

`Uncaught Error: Assertion Failed: Cannot call get with 'validations._validators.conditionGroup.name' on an undefined object.`. The error kills my app.

This has to do with the fact that `ember-cp-validations` loses reference to `model=this` because the component containing the built validations is consumed before the `validated-input`.

I introduced a quick fix to the `factory.js` to [sanity check](https://github.com/ewalti/ember-cp-validations/commit/0c61c268e94b7a8804927b994e87228fb4147ae9) vs the model being present.

Would this be a valid pull request? Or is there a better way I should go about handling this?

**Comment by offirgolan** [comment]
Thanks for opening up this issue and for doing some debugging to help find the main cause of the problem!  I went ahead and added a quick fix for it with the latest release. If you upgrade to `2.9.0`, that should solve your issue. Im gonna go ahead and close this issue but if something similar pops up again, feel free to reopen! 😺
