### ISSUE TITLE
Unit tests fail after upgrading to 2.9.0 ("validator not found")

### ISSUE THREAD

**Issue by splattne** [offirgolan/ember-cp-validations#191]
After upgrading from 2.8.0 to 2.9.0 all my model unit tests fail with the following error message:

>Promise rejected after it exists: [ember-cp-validations] Validator not found of type: presence.@ 40 ms
>Source: 	
>Error: [ember-cp-validations] Validator not found of type: presence.
>     at lookupValidator (http://localhost:5200/assets/vendor.js:145633:13)
>        at http://localhost:5200/assets/vendor.js:145477:92
>        at Array.map (native)
>        at getCPDependentKeysFor (http://localhost:5200/assets/vendor.js:145474:37)
>        at createCPValidationFor (http://localhost:5200/assets/vendor.js:145355:25)
>        at http://localhost:5200/assets/vendor.js:145314:20
>        at Array.forEach (native)
>        at init (http://localhost:5200/assets/vendor.js:145313:31)
>        at superWrapper [as init] (http://localhost:5200/assets/vendor.js:33248:22)
>        at new Class (http://localhost:5200/assets/vendor.js:46980:14)

The tests are simple "it exists" tests which Ember CLI generates automatically, like 

    test('it exists', function(assert) {
      let model = this.subject();
      assert.ok(!!model);
    });

I reverted to 2.8.0 and the unit tests run successfully.

**Comment by offirgolan** [comment]
Since the CPs now require container access, you will need to add all validators that your model depends on in your tests. 

```js
import { moduleFor, test } from 'ember-qunit';

moduleForModel('foo', 'Unit | Model | model', {
  needs: ['validator:presence']
});
```

Thanks for catching + reporting this! Ill add it to the release notes

**Comment by offirgolan** [comment]
Im gonna go ahead and close this. Feel free to reopen if you face any similar issues 😺
