### ISSUE TITLE
Easier translated custom error message

### ISSUE THREAD

**Issue by jelhan** [offirgolan/ember-cp-validations#192]
Currently it's a mess to pass in a custom error message which is translated.

What have to be done to get it working with ember-i18n:

```
let Validations = buildValidations({
  firstName: [
    validator('presence', {
      // depent on locale to observe locale changes
      dependentKeys: ['i18n.locale'],

      // pass message as a function
      message: function() {
        // consume i18n service
        let i18n = this.model.get('i18n');

        // get translated text as Ember.SafeString
        let message = i18n.t('create.options.error.notEnoughOptions');

        // convert to string
        return message.toString();
      }
    })
  ]
});

export default Ember.Component.extend(Validations, {
   // inject service in component to consume it via this.model in validator
   i18n: Ember.inject.service()
});
```

It would be nice if ember-cp-validations supports an easier way to achieve this. Might it be possible to support computed properties as `option.message` and look them up on `this.model`?

**Comment by offirgolan** [comment]
Or you can use [one of these solutions](http://offirgolan.github.io/ember-cp-validations/docs/modules/I18n%20Solutions.html) 😉

**Comment by jelhan** [comment]
You got me wrong. I use `ember-i18n-cp-validations` but it does not support translating custom error messages does it?

What I'm looking for would be something like `options.messageKey` (similar to `options.descriptionKey`). So to give it a more elaborated example:

```
// app/locales/en/translations.js
export default {
  errors: {
    description: "This field",
    present: "{{description}} must be present",
    presentPhoneNumber: "We need your phone number to call you in case of emergency"
  }
}

// some component
let Validations = buildValidations({
  phoneNumber: [
    // We need your phone number to call you in case of emergency
    validator('presence', {
      messageKey: 'errors.presentPhoneNumber`
    }
  ],
  firstName: [
    // This field must be present
    validator('presence')
  ]
};
```

**Comment by offirgolan** [comment]
Ohhh okay I see what you mean (my bad 😝). I would open up this issue on ember-i18n-cp-validations. @jasonmit is usually very responsive and I done believe it should be very difficult to implement this feature on his end.

**Comment by jasonmit** [comment]
:+1: I'm on board.  Opened an issue, feel free to add information -- will try and implement it soon.
