### ISSUE TITLE
Documentation out of date?

### ISSUE THREAD

**Issue by jcowley** [offirgolan/ember-cp-validations#194]
Attempting to use ember-cp-validations for a user registration form and running into several issues. Maybe the docs are just out of date?

**First approach: Validations on the model**
Having the validations on the User model seems ideal so that they could be used in multiple places. However, the example(s) in [the docs](http://offirgolan.github.io/ember-cp-validations/docs/modules/Basic%20Usage.html) and README of using `User.create` are no longer valid. Ember Data throws the following error if you try instantiate a model object directly:
```
ember.debug.js:16318 Uncaught Error: You should not call `create` on a model. Instead, call `store.createRecord` with the attributes you would like to set.
```

You could of course use store.createRecord('user') instead. However, you then run into the issue of adding unsaved records to the store every time the component loads. You could go down the road of trying to destroy those objects when the component is destroyed, but that seems like an overly complex and error-prone solution caused the by the need to generate a model just for the purpose of form validation.

**Second approach: Nested validations on the component**
Next, I tried the [Nested Keys approach from the docs](http://offirgolan.github.io/ember-cp-validations/docs/modules/Advanced%20Usage.html#nestedKeys). If you cut and paste that example code into a component, fix the typo on 'user.lasName', and then make 'acceptTerms' default to true, you'll find that `isFormValid` will incorrectly return false. Also, the `validations` object does not contain any messages... `validations.messages`, `validations.attrs.user.messages`, `validations.attrs.user.firstName.message`, etc. are all empty.

Here's a trimmed down example of that code:

```javascript
import Ember from 'ember';
import { validator, buildValidations } from 'ember-cp-validations';

const Validations = buildValidations({
  'user.firstName': validator('presence', true)
});

export default Ember.Component.extend(Validations, {
  user:  {
    firstName: 'John'
  },
  isFormValid: Ember.computed.alias('validations.isValid') // should be true, but returns false 
});
```

**Comment by offirgolan** [comment]
@jcowley I'm sorry you've been running into some issues. Once I have some free time, Ill look into this and see whats going on there. Can I please ask what versions of ember-cp-validations and ember you are on?

**Comment by jcowley** [comment]
Hi @offirgolan,

Thanks for following up. Would love to help contribute to the docs/code if we can figure out the issue.

I'm using ember-cp-validations 2.3.0 and ember 2.3.1.

Thanks!

**Comment by offirgolan** [comment]
@jcowley nested key validations were introduced in `v2.6.0`. I would suggest to upgrade to the latest version of `ember-cp-validations`.

**Comment by offirgolan** [comment]
@jcowley im gonna go ahead and close this issue. Feel free to reopen if you run into any similar problems.
