### ISSUE TITLE
Ember.String.htmlSafe throws exception

### ISSUE THREAD

**Issue by blimmer** [offirgolan/ember-cp-validations#198]
```javascript
validator('presence', {
  presence: true,
  message: Ember.String.htmlSafe('&rsquo;')
});
```

throws an exception.

At work ATM, I might have time to work on this later, but I pushed a [failing test](https://github.com/offirgolan/ember-cp-validations/commit/893df8481b9cd1802f058bb21a999bd7be5bc9c0) as an example.

**Comment by offirgolan** [comment]
👍 Ill take a look at this!
