### ISSUE TITLE
Shorthanded htmlbars helpers

### ISSUE THREAD

**Issue by jcbvm** [offirgolan/ember-cp-validations#199]
Currently you can get properties by:

```html
{{ v-get model 'prop' 'isValid' }}
{{ v-get model 'prop' 'isInvalid' }}
etc...
```

I think it might be handy if some of these would have a shorthanded version like:

```html
{{ v-valid model 'prop' }}
{{ v-invalid model 'prop' }}
etc...
```

Not sure for which attributes there should be shorthands, but at least `isValid`, `isInvalid` and `message` I think.

**Comment by blimmer** [comment]
I could definitely see value in this. @jcbvm can you put together a PR?

**Comment by offirgolan** [comment]
@jcbvm @blimmer the `v-get` helper is a htmlbars tree transform that takes input and converts it to the native ember `get` helper. Although this could be nice to have, IMHO, I dont really see the need for this since this is just sugar on top of sugar.

**Comment by offirgolan** [comment]
Im gonna go ahead and close this issue. @jcbvm thank you for the suggestion, but unfortunately, the implementation to do something like that is not very simple and will require unnecessary code maintenance for a mere 5 character shortcut. Feel free to comment and/or reopen!
