### ISSUE TITLE
isInvalid helper

### ISSUE THREAD

**Issue by blimmer** [offirgolan/ember-cp-validations#2]
Many times, a button is disabled until the model is valid. It would be nice to have an `isInvalid: Ember.computed.not('isValid')` on a validated object.

**Comment by stefanpenner** [comment]
seems very reasonable. r? @offirgolan

**Comment by offirgolan** [comment]
I agree. I'll add this tomorrow

**Comment by blimmer** [comment]
available in 1.0.1
