### ISSUE TITLE
Handling validations on blur (Need suggestion)

### ISSUE THREAD

**Issue by lnaravindan** [offirgolan/ember-cp-validations#200]
Hi, 

We have a form which is populated by a ember data model. We need the validations of the model to fire only when the form element goes out of focus. 

Example, 

Lets assume I have a user form, for user registration. 

I need to check if the user name is unique, for which I have written a custom validator and used store to access records in the store/ fetch records from the server for checking. 

Currently this validator gets fired whenever I change the user name field. But I don't want the validator to be fired on each change. Rather I want it to be fired only when the input element goes out of focus. 

I might have the same requirement of validating on blur for other default validators too.

Kindly provide suggestions on how to accomplish this task.

**Comment by blimmer** [comment]
To accomplish this, why not bind the `focusout` event on the input to actually set the value on the model and, thus, handle the validation? Something like this:

```handlebars
<!-- don't utilize two way bindings at all here so the validations aren't firing as the user types -->
{{input focus-out='blur'}}
{{#if (v-get model 'userName' 'isInvalid')}}
  <div class="error">
    {{v-get model 'userName' 'message'}}
  </div>
{{/if}}
```

```js
actions: {
  blur(val) {
    // `val` is the value of the input (the desired username or whatever the input is capturing)
    this.set('model.userName', val); // will fire the validator
  }
}
```

**Comment by blimmer** [comment]
I'm going to close this issue since I believe the solution I provided will get the behavior you're seeking. If not, please feel free to reopen. Thanks!
