### ISSUE TITLE
New has-many associations don't invalidate the parent

### ISSUE THREAD

**Issue by dfalling** [offirgolan/ember-cp-validations#206]
My form allows creating new child objects.  These objects are initially blank and invalid, but this doesn't bubble up to the parent.

From the debugger:
```
this.get('model.product.translations').toArray()[0].get('validations.isValid');
true
this.get('model.product.translations').toArray()[1].get('validations.isValid');
false
this.get('model.product.validations.isValid');
true
```

Is there something I need to do to the parent to make it refresh after a new child is added?

Thanks!

**Comment by offirgolan** [comment]
Are you using a `belongs-to` or `has-many` validator on the parent?

**Comment by dfalling** [comment]
belongs-to:

```
const Validations = buildValidations({
  translations: validator('has-many')
});
```

**Comment by offirgolan** [comment]
Can you add a snippet of both the parent and child model/validations?

**Comment by dfalling** [comment]
product-translation:
```Javascript
import DS from 'ember-data';
import { validator, buildValidations } from 'ember-cp-validations';

const Validations = buildValidations({
  name: validator('length', { min: 1 }),
  field: validator('length', { min: 1 }),
  product: validator('presence', true),
  locale: validator('presence', true)
});

export default DS.Model.extend(Validations, {
  name: DS.attr('string'),
  field: DS.attr('string'),
  product: DS.belongsTo('product'),
  locale: DS.belongsTo('locale', { inverse: null })
});
```

product:
```Javascript
import DS from 'ember-data';
import { findTranslation } from 'ecommerce/utils/translations-util';
import { validator, buildValidations } from 'ember-cp-validations';

const Validations = buildValidations({
  partNumber: validator('presence', true),
  pricing: validator('belongs-to'),
  translations: validator('has-many')
});

export default DS.Model.extend(Validations, {
  translations: DS.hasMany('product-translations', { async: true }),
 ...
```

I create new `product-translation`s like this:
```Javascript
    let newTranslation = { product: this.get('model.product'), locale, field: fieldName };

    this.store.createRecord('product-translation', newTranslation);
```

**Comment by offirgolan** [comment]
Are you adding the new product-translation to the hasMany array?

```js
var translation = this.store.createRecord('product-translation', {});
product.get('translations').pushObject(translation);
```

**Comment by dfalling** [comment]
No.  If I hit `product.get('translations');` it's there.  Should I also push it to let ember-cp-validations know about it?

**Comment by dfalling** [comment]
I tried that as well and didn't have any more luck:
```Javascript
    let newTranslation = this.store.createRecord('product-translation', { product: this.get('model.product'), locale, field: fieldName });

    this.get('model.product.translations').pushObject(newTranslation);
```

**Comment by offirgolan** [comment]
Okay weird. Let me play around with this I might know where this issue is coming from.

**Comment by dfalling** [comment]
Great, thanks for the quick response!

**Comment by dfalling** [comment]
My view was checking the wrong property (`model.validations.isValid` instead of `model.product.validations.isValid`) which was keeping the validation from ever firing.  Fixing that did get it to see the child with no other changes necessary.

I did run into another issue though, with an easy workaround: `name: undefined` is considered valid to the `length, { min: 1 }` rule.  I can fix this with `name: ''`, but this seems like an oversight.  Should I log a separate issue for this?  Thanks!

**Comment by offirgolan** [comment]
Great! Glad you were able to fix it. I actually found some issues that need to be resolved so ill just add the length validator to my list. No need to create another issue.

**Comment by dfalling** [comment]
Sounds good.  Thanks for your help!
