### ISSUE TITLE
[Feature] Expose validator functions as public API

### ISSUE THREAD

**Issue by poteto** [offirgolan/ember-cp-validations#209]
There is a use-case for being able to manually lookup the validation without having to use a CP. Other addons can integrate with this one to manually validate a value. As an example, https://github.com/poteto/ember-changeset is an addon that stores valid changes on a changeset before being set on the underlying model. Since no values are set on the model until the changeset is executed, `ember-cp-validations` cannot validate the values as a CP on the model.

For example, given a validation mixin like this:

```js
const Validations = buildValidations({
  username: validator('presence', true)
});
```

the API could look like `Validations.validate('username', value, options, ...)` and return either a `Boolean` or an error message/object.

**Comment by offirgolan** [comment]
@poteto I'm gonna take a look into this early next week. If you dont hear from me, please shoot me a ping 😺

**Comment by offirgolan** [comment]
Okay after a good amount of time thinking of the best possible way to do this, I have a solution. 

```js
const Validations = buildValidations({
  username: validator('presence', true)
});

const model = DS.Model.extend(Validations);
const usernameResult = model.get('validations').validatedAttribute('username', 'offirgolan');
```

In the context of this library, there is never a point where a boolean or string is returned, instead a [validation result collection](http://offirgolan.github.io/ember-cp-validations/docs/classes/ResultCollection.html) is returned. If the result collection is async, it will return a promise which will resolve to the same result collection but this time, all validations have finished. From there, you can do `usernameResult.get('isValid')` or `username.get('error')`.

Would that solve your use-case?

**Comment by blimmer** [comment]
Also, I'm not incredibly familiar with ember-changeset, but I've had good luck mixing Validations directly into ember-buffered-proxy before. The proxy nicely allows running validations on the proxied changes before applying them to the real model:

```javascript
import { myValidations } from 'my-app/models/foo';

BufferedProxy.extend(Validations, {});
```

I do, however, think this feature could be useful for this and other purposes. @offirgolan I 👍 the API direction you're proposing!
