### ISSUE TITLE
Extra work done in validation-results-collection.js?

### ISSUE THREAD

**Issue by blimmer** [offirgolan/ember-cp-validations#21]
Are we doing extra work by pulling both `.messages` and `.message` from the validation [here](https://github.com/offirgolan/ember-cp-validations/blob/master/addon/utils/validation-result-collection.js#L62-L65)?

It seems like since `.message` is always an alias to `messages.firstObject` we shouldn't need to grab both. It's working currently because we `flatten` and `uniq`, but if we don't need to grab both, seems like we should always just have `.messages`.

**Comment by offirgolan** [comment]
I swear it was there for a reason.... Let me think it over and get back to you on this one. Honestly it could just be some old code.

**Comment by offirgolan** [comment]
Okay so the code that you pointed to is correct. A validation result collection can be a collection of validation-result objects which will only have a single message, a validation-result-collection which will have multiple message, and a model validations object which again will have multiple messages.

**Comment by offirgolan** [comment]
@blimmer can we close this?

**Comment by blimmer** [comment]
Yep, sorry. I read your comment and didn't close it.
