### ISSUE TITLE
Tabbing through fields sets off validation unexpectedly

### ISSUE THREAD

**Issue by jamesdixon** [offirgolan/ember-cp-validations#22]
When viewing the demo, it appears that tabbing through the fields will set off the validation immediately on the field that the cursor is entering. I would expect it to show up on the field that the cursor is leaving, but not the field the cursor is entering. This does not occur when using the mouse to enter a field.

Demo here: http://quick.as/X6QLFp21B

**Comment by blimmer** [comment]
This is something [we've talked about before](https://github.com/offirgolan/ember-cp-validations/issues/5#issuecomment-138777372). Basically, our idea is that this library should be decoupled from the presentation (e.g. not delay running the validations).

How you choose to present the validation messaging is up to you. For my app, I have a component that tracks whether or not the field has been visited and then show the error only if the field was visited.

**Comment by stefanpenner** [comment]
> our idea is that this library should be decoupled from the presentation (e.g. not delay running the validations).

yes, this is the goal :+1:

**Comment by blimmer** [comment]
@jamesdixon , please check out #23 and provide your thoughts/examples.

**Comment by jamesdixon** [comment]
@blimmer - thanks, i did see #5 previously, but it seemed odd that tabbing into the field triggered the message immediately, but clicking into the field did not. I suppose that's something to do with the way the event is triggered. Regardless, maybe there is a better way to demo the library; the demo seems to make it appear "broken" from a user perspective in my opinion.

Regardless, I completely agree that the library should be decoupled from the presentation and I will certainly have a look at #23.

**Comment by blimmer** [comment]
i opened up #24 for improving the demo. thanks!

**Comment by jamesdixon** [comment]
sweet. thanks!
