### ISSUE TITLE
Best way to do model validation in one form, but exclude validation requirement from another form

### ISSUE THREAD

**Issue by aronysidoro** [offirgolan/ember-cp-validations#222]
**Problem:** I'd like to do validation on a "create" form for it to require a User ``password`` to create a User.  But, on the update form, not to require a ``password``. 

If I put the validations on the ``model`` it will always require the ``password`` field.  So, in this case, do you recommend putting it on the ``new User component``?  Just looking for a high level recommendation.  Or if all can be left on the ``model``, and I'm just missing something. 

Thank you, and thank you for this great library!

**Comment by offirgolan** [comment]
Both methods are possible. 

You can either place your validations on the component like you said, or place the validations on the model and using `disabled` to toggle the password validation.

```js
password: {
  dependentKeys: ['isNew'],
  disabled(model) {
    return !model.get('isNew');
  },
  validators: [
    validator('presence', true),
    validator('length', { max: 8 }
  ]
}
```

**Comment by aronysidoro** [comment]
@offirgolan thank you for your response. I didn't know about `disabled`. I really like your solution. Cheers!

**Comment by offirgolan** [comment]
@aronysidoro no problem! Glad I could help out 😸

**Comment by mashpie** [comment]
sadly can't get that to work. Am I missing anything? Or is there something more to do than:

validations setup in Model (stripped down to password):

```js
// models/user.js
import Model from 'ember-data/model';
import attr from 'ember-data/attr';
import { validator, buildValidations } from 'ember-cp-validations';

const Validations = buildValidations({
  password: {
    dependentKeys: ['isNew'],
    disabled(model) {
      return !model.get('isNew');
    },
    validators: [
      validator('presence', true),
      validator('length', { min: 12, max: 18 })
    ]
  }
}, {
  debounce: 500
});

export default Model.extend(Validations, {
  password: attr('string'),
  // isNew: attr('boolean') --> adding this with true on creation didn't work either
});

```

create Model on route:

```js
// routes/user/add.js
import Ember from 'ember';

export default Ember.Route.extend({
  model() {
    return this.get('store').createRecord('user');
  }
});
```

calling validate in controller

```js
import Ember from 'ember';
export default Ember.Controller.extend({

  actions: {
    save() {
      var model = this.get('model');

      model.validate().then(({ model, validations }) => {
        if (validations.get('isValid')) {
         // save, redirect, show toast, etc. 
        }
        this.set('didValidate', true);
      }, (errors) => {

      });
    }
  }
});

```

still validates all attributes including password. Any hints? Thanks a lot!

**Comment by lyudvigmakeit** [comment]
password: {
  dependentKeys: ['isNew'],
  disabled: computed(function () {
        return this.model.isNew;
      }),
  validators: [
    validator('presence', true),
    validator('length', { max: 8 }
  ]
}
