### ISSUE TITLE
Ember-Data is required to use the DS Error validator - Too Strict for ED 2.6+

### ISSUE THREAD

**Issue by hhff** [offirgolan/ember-cp-validations#224]
In recent versions of Ember Data, validating that Ember Data exists by `self.DS` is no longer effective - because ED imports work like this now:
```
import Model from 'ember-data/model';
import attr from 'ember-data/attr';
```

This error is thrown:
https://github.com/offirgolan/ember-cp-validations/blob/d682193c1bb978ad56b300d38c1297e42aa96ba7/addon/validators/ds-error.js#L10

I'd recommend something like this:
```
try {
  requireModule('ember-data');
} catch {
  throw new Error('Ember-Data is required to use the DS Error validator.');
}
```

That cool?  if so I'll shoot over a PR

**Comment by stefanpenner** [comment]
try/catch hurts debuggability, the following should work:

```js
import require from 'require';
const hasEmberData = require.has('ember-data/model')
```
https://github.com/ember-cli/loader.js/blob/master/lib/loader/loader.js#L264-L266

**Comment by hhff** [comment]
ah!  👌

**Comment by hhff** [comment]
PR incoming
