### ISSUE TITLE
disabled as a global option doesn't work

### ISSUE THREAD

**Issue by dustinfarris** [offirgolan/ember-cp-validations#237]
When i try this:

```js
const Validations = buildValidations({
  'model.email': [
    validator('presence', true)
  ]
}, {
  disabled(model, attribute) {
    console.log('Can anyone hear me?');
    return false;
  }
});

export default Component.extend(Validations, {
});
```

The console.log never fires.  The validations are disabled though—despite the fact that I am returning false.

**Comment by dustinfarris** [comment]
Actually disabled as a function doesn't work right no matter how you use it.

**Comment by offirgolan** [comment]
@dustinfarris what version of ember-cp-validations are you on?

**Comment by dustinfarris** [comment]
2.9.3

**Comment by offirgolan** [comment]
Does it work when you do this:

```js
const Validations = buildValidations({
  'model.email': [
    validator('presence', true)
  ]
}, {
  disabled(model, attribute) {
    console.log('Can anyone hear me?');
    return false;
  }
});

export default Component.extend(Validations, {
  model: { email: '' }
});
```

**Comment by hschmidt99** [comment]
I have a similar use case and am currently working with version 3.0.0-beta.0
What I can confirm is that the global disabled-computed is being utilized whenever a validator doesn't specify its own disabled logic, so it's more or less a default option.
My intuition was that it would act as a real global disabled aka "Check the topmost disabled first and only if that is false, check the disabled properties on the specific validators".

But I guess that's what #165 is aiming for, right?

**Comment by offirgolan** [comment]
@hschmidt99 

> Just like in the default options, local validator options will always take precedence over default options and default options will always take precedence over global options. This allows you to declare global rules while having the ability to override them in lower levels.

[- docs](http://offirgolan.github.io/ember-cp-validations/docs/modules/Advanced%20Usage.html#globalOptions)

**Comment by offirgolan** [comment]
@dustinfarris have you been able to resolve your issue?

**Comment by steven-ferguson** [comment]
I noticed the docs show disabled being used as a function, but the tests only use it as a [property or a computed property](https://github.com/offirgolan/ember-cp-validations/blob/master/tests/integration/validations/factory-general-test.js#L377-L421). Switching to a computed property for disabled resolved the problems I was having.

**Comment by dustinfarris** [comment]
I'm using ember-changeset-validations now.  Please feel free to close, but looks like there is still an open issue with updating docs for 3.x.
