### ISSUE TITLE
Improve Demo with simple visited-input component

### ISSUE THREAD

**Issue by blimmer** [offirgolan/ember-cp-validations#24]
While we're discussing a forms library, we should improve the UX of the demo with a `visited-input` or something that tracks when to show the validation errors. I have one that I could clean up and open-source, and I know that @jimmay5469 said that he has one, too.

This will provide a nice interim solution for folks.

**Comment by blimmer** [comment]
Actually, now that I've had time to dig into the code, the validated-input is a pretty darn good starting point, I think. My solution just relies on `focus-out`, which is not as good of a UX as [the debounce](https://github.com/offirgolan/ember-cp-validations/blob/master/tests/dummy/app/components/validated-input.js#L41) behavior we have today.

@jamesdixon didn't expect this behavior and I'd be interested to hear his opinions in the [form examples](https://github.com/blimmer/ember-form-examples) repo while we consider what would be useful in a form library.

**Comment by offirgolan** [comment]
The reason for the errors appearing when you tab through an input is because it changes the value of the model attribute from undefined to an empty string. That triggers the validations to run and the errors to display since it is now in a dirty state. Ill take a look at this more when I get some time.

**Comment by blimmer** [comment]
I think it's questionable whether or not that's a bad UX, though. Visiting a field, even without filling it out seems like a reasonable time to tell the user if they have to fill out the field.

**Comment by jamesdixon** [comment]
I think the current experience is somewhat jarring in that when you first load the form, as a user, all seems great. Nothing appears to be required and then you enter a seemingly non-required field and boom! Red error messages everywhere! 

That said, I prefer some sort of initial 'hinting' that indicates if the field is required and what it requires. If I've left the field after entering it and have not satisfied those requirements, then it seems prudent to display an error messages that indicate what I need to do to satisfy the requirement. But with some sort of hinting, I know what's initially expected of me as a user. Also, when I say hinting, that's not to be confused with a placeholder. The [React Material](http://material-ui.com/#/components/text-fields) text fields have a good example of hints vs error messages.

Isn't it crazy that forms have been around for forever and there's still plenty of debate on how to optimize the experience? Nutty.
