### ISSUE TITLE
not validating on submit

### ISSUE THREAD

**Issue by JLin37** [offirgolan/ember-cp-validations#246]
EDIT: ok, it seems like once I put the actions code into the controller for my route it worked fine. 
I'm new to ember, so forgive me for a noob question, but isn't ember 2.0 onwards depreciating the use of controller? So would it be better to do this right in the route? and if so, how would I implement it?

Hi guys, really like this addon, but I'm running into some trouble validating on submit.

I'm trying to get the:

                   {{#if showAlert}}
                        <div class="alert">
                            <div class="fa fa-times icon-remove" {{action 'dismissAlert'}}></div>
                            Please fix all the errors below before continuing.
                        </div>
                    {{/if}}

and also any alert messages for a input field to show up, when there is nothing entered or there is a missing field on submit.

but for some reason I there just doesn't seem to be a response when I click submit, I was trying this with all fields left empty so it will tell me to fill out all required info, but nothing! here is how i call submit action in template.

       {{action 'submit' model}}

code in the route:

      `actions: {
		submit: function(model) {
	      model.validate().then(({
	        model,
	        validations
	      }) => {
	        if (validations.get('isValid')) {
	          this.setProperties({
	            showAlert: false,
	          });
	        } else {
	          this.set('showAlert', true);
	        }
	        this.set('didValidate', true);
	      }, (errors) => {

	      });
		},
	},`

and here is my model,

    import DS from 'ember-data';
    import Ember from 'ember';
    import {
      validator, buildValidations
    } from 'ember-cp-validations';

    const { computed } = Ember;
    const { attr } = DS;

    const Validations = buildValidations({
      fullName: {
        validators: [
          validator('presence', true)
        ]},
      email: {
        validators: [
          validator('presence', true),
          validator('format', { type: 'email' })
        ]
      },
      tel: {
        validators: [
          validator('presence', true),
          validator('format', { type: 'tel' })
        ]
      },
      emailConfirmation: {
        validators: [
          validator('confirmation', {
            on: 'email',
            message: 'Email addresses do not match',
            debounce: 500}),
        ]
      },
      city: validator('presence', true),
      state: validator('presence', true),
      zipCode: validator('presence', true),
    });

    export default DS.Model.extend(Validations, {
      fullName: DS.attr('string'),
      email: DS.attr('string'),
      tel: DS.attr('string'),
      comment: DS.attr('string'),
      city: DS.attr('string'),
      state: DS.attr('string'),
      zipCode: DS.attr('number'),
    });

I'm at lose as to what I'm not doing right. Any help will be appreciated.

**Comment by blimmer** [comment]
Did you figure it out? If so, can you post the solution in case others find this?

**Comment by JLin37** [comment]
@blimmer well in my Edit at the top I ended up just creating a controller for my route and put the action code in there and everything worked fine. also worked fine when using it in a component. But from what I gather about ember going forward they plan to remove controllers from blueprint, so was asking if there are plans to move the implementation into the route directly instead of using the controller. I new to ember, so I'm not very well versed in quite a lot of the thing to understand how to change the code so it works directly inside the route.

btw, it seems it's the model.validate part of the code that doesn't seem to hook when in the route, if there is a way to fix that, then it should work fine directly in route.

**Comment by blimmer** [comment]
To get around using a Controller, I would consider making your form logic into a Component. I usually follow the pattern of having my route render just one component so I'm not introducing Controllers and will be ready if routable components ever happen.

You might also look at [ember-route-actions](https://github.com/DockYard/ember-route-action-helper).
