### ISSUE TITLE
How to validate belongsTo/hasMany relationship?

### ISSUE THREAD

**Issue by ugoa** [offirgolan/ember-cp-validations#254]
I have a  `merchant` and a  `location` model, a `merchant` has a `hasMany` relationship with `location`. what I want to validate is `a merchant must have at least one location` when creating a merchant. How can I achieve this? I went through all the documents but still not sure which validator I should use.

Appreciate it if anybody can help.

- Ember Version: 2.4.5
- Ember CLI Version:2.4.3
- Ember CP Validations Version: 2.9

**Comment by offirgolan** [comment]
```js
{
  location: [
    validator('has-many'),
    validator('length', {
      min: 1
    })
  ]
}
```

If the above doesnt work, try this: 

```js
{
  location: [
    validator('has-many'),
    validator('length', {
      min: 1,
      value(model) { 
        return model.get('length'); 
      }
    })
  ]
}
```

**Comment by ugoa** [comment]
@offirgolan The first one works, many thanks! Awesome add-on!

**Comment by offirgolan** [comment]
Fantastic! Glad to help out 😺

**Comment by ugoa** [comment]
Unfortunately I received error like below:
```
vendor.js:42200 Error: Assertion Failed: Cannot call get with 'isValidations' on an undefined object.
    at new Error (native)
    at Error.EmberError (http://perx-live.localhost:4200/assets/vendor.js:26656:21)
    at assert (http://perx-live.localhost:4200/assets/vendor.js:16466:13)
    at Object.assert (http://perx-live.localhost:4200/assets/vendor.js:26420:34)
    at Object.get (http://perx-live.localhost:4200/assets/vendor.js:30881:22)
    at i (http://perx-live.localhost:4200/assets/vendor.js:43726:41)
    at Array.every (native)
    at Array.isEvery (http://perx-live.localhost:4200/assets/vendor.js:44224:19)
    at Class.update (http://perx-live.localhost:4200/assets/vendor.js:89191:56)
    at http://perx-live.localhost:4200/assets/vendor.js:89220:22
```
The error log is quite long so I only paste only part of them, please let me know if you need more info. Thanks.

**Comment by offirgolan** [comment]
@ugoa this is a known issue. Im currently working on this and have a fix for it in a branch (nested-models). Feel free to checkout that branch in the mean time until I fix all underlying issues.

**Comment by ugoa** [comment]
@offirgolan Hi, could you please update me how this issue was fixed, or not. I tried to find the branch but it's not there anymore, please advise. Thanks.

**Comment by offirgolan** [comment]
@ugoa if you are on 3.0-beta, I suggest upgrading to the latest version which has this fix in it.

`npm i ember-cp-validations@beta`

**Comment by krasnoukhov** [comment]
Another option would be to use `validator('collection', true)` instead of `validator('has-many')` in case you don't really want to validate nested models
