### ISSUE TITLE
Usage in tests?

### ISSUE THREAD

**Issue by iheanyi** [offirgolan/ember-cp-validations#256]
### Environment

- Ember Version: 2.6.2
- Ember CLI Version: 2.5.1
- Ember CP Validations Version: 3.0.0-beta.1

### Steps to Reproduce
1) Setting a Question model with the following validators.

```
const Validations = buildValidations({
  title: [
    validator('presence', {
      presence: true,
      message: 'Don\'t forget to enter a question!'
    }),
    validator('length', {
      min: 15,
      message: 'Please enter at least {min} characters'
    })
  ],
}, {
   debounce: 500
);
```

And I'm trying to use it in my unit test like so.

```javascript
import PresenceValidator from 'ember-cp-validations/validators/presence';
import LengthValidator from 'ember-cp-validations/validators/length';
...

this.register('validator:presence', PresenceValidator);
this.register('validator:length', LengthValidator);

let model = this.subject({
    title: ''
});

expect(model.get('validations.attrs.title.isValid')).to.be.false;
expect(model.get('validations.attrs.title.message')).to.equal("Don't forget to enter a question!");
```

Yet `isValid` is returning `true`, although I expect it to return `false`. Do you have any idea why? Been trying to figure this out and I'm stumped.

**Comment by iheanyi** [comment]
I figured it out, having the `debounce` in there was causing the tests to fail. Any suggestions you have for safeguarding against this in tests? Thanks.

**Comment by offirgolan** [comment]
> a debounced validation validate returns a promise

@iheanyi you are totally right! I should a snippet of this in the docs. Glad you were able to figure it out 😺
