### ISSUE TITLE
Validator generator shows "init without calling this._super" deprecation warning.

### ISSUE THREAD

**Issue by GCheung55** [offirgolan/ember-cp-validations#268]
### Environment

- Ember Version: 2.6.1
- Ember CLI Version: 2.6.2
- Ember CP Validations Version: 3.0.0-beta.3

### Steps to Reproduce

- Install ember-cp-validations: `ember install ember-cp-validations`
- Run generate command: `ember generate validator foo-bar`
- See warning:
```javascript
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `undefined`
    at Function.Blueprint.load (/project/node_modules/ember-cli/lib/models/blueprint.js:1352:33)
```

**Comment by offirgolan** [comment]
@GCheung55 thanks for bringing this to my attention. Fix is in master 😺
