### ISSUE TITLE
Broken build: ember-release (object destroy tests)

### ISSUE THREAD

**Issue by offirgolan** [offirgolan/ember-cp-validations#275]

**Comment by moubi** [comment]
@offirgolan please provide more info. 
Tests break on my side as well when using `validator('format')`
I am using `3.0.0-beta.3`

**Comment by offirgolan** [comment]
@moubi I dont believe this should effect your app's test cases. Please upgrade to the latest beta and open a new issue with more details regarding your specific issue.

**Comment by offirgolan** [comment]
Resolved in #279
