### ISSUE TITLE
calling predefined validator in custom validator

### ISSUE THREAD

**Issue by georgi-kovachev** [offirgolan/ember-cp-validations#289]
I created the custom validator in dependent-state.js

import BaseValidator from 'ember-cp-validations/validators/base';
import LengthValidator from 'ember-cp-validations/validators/length';
import validator from 'ember-cp-validations';

export default BaseValidator.extend({
  validate(value, options, model, attribute) {

    if (model.get('country') !== 'US') {
      return true;
    }
    else {
      // return LengthValidator.validate(value, options, model, attribute);
      // return new LengthValidator(value, options, model, attribute);
      return validator('length', options);
    }

  }
});

Here I would like to call default 'length' validator, but all of above code fails.
Any help?

And I use this custom validator in another file.

state: {
    description: "State",
    validators: [
      validator('ds-error'),
      validator('presence', true),
      validator('dependent-state', { max: 2 }),
    ]
  },

**Comment by georgi-kovachev** [comment]
any updates on this ticket?

**Comment by offirgolan** [comment]
@georgi-kovachev it looks like you just want to disable a length validator if the country is not 'US'. Why not do something like this instead:

```js
validator('length', {
  disabled: computed('model.country', function() {
    return this.get('model.country') !== 'US';
  })
});

**Comment by georgi-kovachev** [comment]
how I still apply length should be max 2 for US? I used to do

**Comment by offirgolan** [comment]
validator('length', {
  disabled: computed('model.country', function() {
    return this.get('model.country') !== 'US';
  }),
  max: computed('model.country', function() {
    return this.get('model.country') === 'US' : 2 : undefined;
  })
});

**Comment by georgi-kovachev** [comment]
I just replaced the code as  Ember.computed.
But I receive organization-address.js:33 Uncaught TypeError: this.get is not a function
http://prntscr.com/c0v5zy
```
state: {
    description: "State",
    validators: [
      validator('ds-error'),
      validator('presence', true),
      validator('length', {
        disabled: Ember.computed('model.country', function() {
          return this.get('model.country') !== 'US';
        }),
        max: Ember.computed('model.country', function() {
          return this.get('model.country') === 'US' ? 2 : undefined;
        })
      })
    ]
  },
```

**Comment by offirgolan** [comment]
What version of ember-cp-validations are you on? Using Ember.computed is only compatible in v3.x

**Comment by georgi-kovachev** [comment]
"ember-cp-validations": "git://github.com/unchartedcode/ember-cp-validations#162b424b50e1009f01907a22c119704d5b294227",

It is using another library which is forked from your library.

**Comment by offirgolan** [comment]
Alright well try something like this:

```js
state: {
    description: "State",
    validators: [
      validator('ds-error'),
      validator('presence', true),
      validator('length', {
        dependentKeys:['country'],
        disabled() {
          return this.get('model.country') !== 'US';
        }),
        max() {
          return this.get('model.country') === 'US' ? 2 : undefined;
        })
      })
    ]
  },
```

If this doesnt work then you will have to open an issue on the fork's github page since I dont know what changes they have made to this library.

**Comment by georgi-kovachev** [comment]
Thanks it is working. Thanks for your help.
