### ISSUE TITLE
ember-cp-validations adds about 193 Kb to the vendor.js file size (minimized)

### ISSUE THREAD

**Issue by ivanvotti** [offirgolan/ember-cp-validations#30]
The library including its dependencies can be too heavy for projects that don't use `lodash` and `moment.js`

For example, [ember-validations](https://github.com/dockyard/ember-validations) adds just about 16 Kb to the vendor.js file (minimized).

**Comment by rwjblue** [comment]
#31 addresses the lodash part (though I'm not sure how much of the filesize that is)

**Comment by ivanvotti** [comment]
#31 fixes the problem. It's still possible to make the build 42 Kb lighter, if `moment.js` will be optional.

**Comment by rwjblue** [comment]
Ya, we can do that too I think.

**Comment by offirgolan** [comment]
Moment has been removed as a dependency but will be required if you want to use the date validator. This will be available when 2.0 is released.
