### ISSUE TITLE
model.validate() not a function

### ISSUE THREAD

**Issue by datasc123** [offirgolan/ember-cp-validations#300]
### Environment

- Ember Version: 2.4.3
- Ember CLI Version: 2.4.3
- Ember CP Validations Version: 3.0.0-beta.4

### Steps to Reproduce

In my route's action, I used the same as provided in the dummy example and in the model as well. Still does not work for me. 

In closed issues I found the same problem, but 
`this.currentmodel` did not help

**Comment by offirgolan** [comment]
@datasc123 when you have a action in your route, you cannot do `this.get('model')` since this.model is a function. I suggest when you call your action from your template/controller/component, you pass it the current model you are trying to validate.

So instead of

```hbs
<a {{action 'doSomething'}}></a>
```

You do something like this:

```hbs
<a {{action 'doSomething' model}}></a>
```

**Comment by offirgolan** [comment]
Closing as this issue has been abandoned.
