### ISSUE TITLE
Ember inspector - Named scope

### ISSUE THREAD

**Issue by taheilo** [offirgolan/ember-cp-validations#306]
### Environment

- Ember Version: 2.6
- Ember CLI Version: 2.6
- Ember CP Validations Version: 3.0.0-beta.3

### Feature request

I would love if it was possible to assign a named scope to the validations mixin, so that in the ember inspector, the validations are not grouped under a `(unknown mixin)` tab.

### Reading that could help solving the issue

https://github.com/emberjs/ember-inspector/issues/284 

### Screenshot

![screen shot 2016-08-10 at 16 43 06](https://cloud.githubusercontent.com/assets/922444/17558009/8bbd16b8-5f19-11e6-89c6-7b856a7868a8.png)

**Comment by offirgolan** [comment]
@taheilo thank you for bringing this to my attention. It will be included in the next release 😺
