### ISSUE TITLE
Deprecation warning for v-get from ember-cli-htmlbars-inline-precompile

### ISSUE THREAD

**Issue by timiyay** [offirgolan/ember-cp-validations#318]
### Environment

- Ember Version: 2.7.0
- Ember CLI Version: 2.7.0
- Ember CP Validations Version: 2.9.3
- `ember-cli-htmlbars-inline-precompile` Version: 0.3.5

### Steps to Reproduce

* Install `ember-cli-htmlbars-inline-precompile` 0.3.5
* Install `ember-cp-validations` 2.9.3
* Start `ember server`

An error message will be displayed:

```
DEPRECATION: ember-cli-htmlbars-inline-precompile is opting out of caching due to an AST plugin that does not provide a caching strategy: `v-get`.
DEPRECATION: ember-cli-htmlbars is opting out of caching due to an AST plugin that does not provide a caching strategy: `v-get`.
```

**Comment by offirgolan** [comment]
@timiyay thanks for opening up this issue. This has been resolved in #305 and is currently in master 😺
