### ISSUE TITLE
Deprecation warnings after upgrading to ember-cli v2.7.0

### ISSUE THREAD

**Issue by kasunvp** [offirgolan/ember-cp-validations#319]
### Environment

- Ember Version: 2.7.0
- Ember CLI Version: 2.7.0
- Ember CP Validations Version: 3.0.0-beta.5 (same with v2.9.3)

### Steps to Reproduce
1. create new Ember app with v2.7.0
2. install ember-cp-validations addon
3. run `ember s`

it will display:

```
DEPRECATION: ember-cli-htmlbars-inline-precompile is opting out of caching due to an AST plugin that does not provide a caching strategy: `v-get`.
DEPRECATION: ember-cli-htmlbars is opting out of caching due to an AST plugin that does not provide a caching strategy: `v-get`.
```

**Comment by rwjblue** [comment]
This is a duplicate. Issue is fixed on master, but not released yet.

**Comment by rwjblue** [comment]
https://github.com/offirgolan/ember-cp-validations/issues/318

**Comment by kasunvp** [comment]
Thanks! Sorry about the duplicate. Closing this now.

**Comment by rwjblue** [comment]
No worries! I'm not 100% sure what the release blockers are. I'll try to circle around with @offirgolan tomorrow and find out.

**Comment by kasunvp** [comment]
That would be great! :+1:

**Comment by offirgolan** [comment]
@kasunvp `v2.9.4` has been released with this fix.

**Comment by Moedav** [comment]
When will there be a fix for `v3`?

**Comment by offirgolan** [comment]
@Moedav Im waiting on 2 PRs to get merged before I make another 3.0 beta release.

**Comment by kasunvp** [comment]
@offirgolan thanks for the quick fix. But I've waiting for the 3.x update. Looks like it's in now.

**Comment by offirgolan** [comment]
Yup the fix is in the latest beta now 😁
