### ISSUE TITLE
Documentation doesn't mention `needs` for unit tests

### ISSUE THREAD

**Issue by indirect** [offirgolan/ember-cp-validations#32]
While writing a unit test for an ember-data model with validations, I had to add `needs: ['validator:presence']` to the unit test, which isn't documented anywhere that I can find. Maybe a good thing to mention?

**Comment by blimmer** [comment]
I'm torn on what to do with this one. It's very common to see container lookups fail in unit tests, and needing to build out the `needs` array. Is the message particularly cryptic, or is it similar to other container lookup failures in unit tests?

**Comment by blimmer** [comment]
Either way, I don't think it hurts to add into the documentation :-)

We have [a branch](https://github.com/offirgolan/ember-cp-validations/pull/29) for new docs, so maybe a PR once that gets merged? We'd sure appreciate any improvements to docs.

**Comment by offirgolan** [comment]
Closing in favor of #40.
