### ISSUE TITLE
Ensuring other validators pass first when including a custom validator? 

### ISSUE THREAD

**Issue by timmyomahony** [offirgolan/ember-cp-validations#320]
I am writing a custom validator to check for email uniqueness. My custom validator checks a backend API to make sure that the supplied email isn't already signed-up. 

I use it like so:

```
const Validations = buildValidations({
  email: {
    validators: [
      validator('presence', true),
      validator('format', {
        type: 'email'
      }),
      validator('unique-email', {
        debounce: 500,
        message: 'That username is already taken'
      })
    ]
  },
  ..
```

I notice that my custom validator is running even when the `presence` and `format` validators are failing. Is is possible to make sure that my validator _doesn't_ run if the preceding validators fail? Otherwise I have to re-validate the input in my custom validator.

**Comment by timmyomahony** [comment]
I think I figured this out. You can simply check within your `validate` method to see if the attribute is currently validating or not and then abort the custom validation:

```
const UniqueEmail = BaseValidator.extend({
  validate(value, options, model, attribute) {
    if(model.get(`validations.attrs.${attribute}.isValid`)) {
      // do remote validation
    }
  }
});
```

**Comment by offirgolan** [comment]
@timmyomahony I think you bring up a valid use case. In theory, a validation should only be run if the previous validation is passing. Currently, all validations are run every time something changes but that logic is a bit flawed. 

In your first example, the format and unique-email validators should only need to run when the presence validator passes.

I'll work on putting something together 😸

**Comment by timmyomahony** [comment]
Thanks for the quick reply. Intuitively I would have thought that the validators would run in order and stop processing when one fails so yes, maybe there is a use case there. That said, checking ```model.get(`validations.attrs.${attribute}.isValid`)``` seems to work OK so maybe just a documentation change is all that is needed for the moment? 

Maybe there could be both a global and validator option to enable or disable aborting on fail? 

```
const Validations = buildValidations({
  email: {
    validators: [
      validator('presence', {
        stopOnFailure: false
      }),
      validator('unique-email', {
        stopOnFailure: true
      })
     ]
   },
});
```

and

```
const Validations = buildValidations({
  email: {
    validators: [
      validator('presence'),
      validator('unique-email')
     ]
   },
}, {
    stopOnFailure: true
});
```

(I don't think `stopOnFailure` is the right name for it but can't think of another)
