### ISSUE TITLE
Allow regex on format to be a string

### ISSUE THREAD

**Issue by aaronbhansen** [offirgolan/ember-cp-validations#325]
### Environment

- Ember Version: 2.6
- Ember CLI Version: 2.6
- Ember CP Validations Version: 3.0.0-beta.6

### Steps to Reproduce

We have a computed property that is regex right out of the database, would you be okay having regex be a string or a regex class? 

The validator looks like
```
validator('format', {
        allowBlank: true,
        regex: Ember.computed.readOnly('model.country.postal_code_format')
})
```

In the validator I figure you could do something like 
```
if (regex) {
  if (typeof regex === "string") {
    regex = new RegExp(regex);
  }

  if (!regex.test(value)) {
    return this.createErrorMessage(type || 'invalid', value, options);
  }
}
```

instead of what it is today.

![debug](https://cl.ly/0G0R031L0m1u/Screen%20Shot%202016-08-22%20at%201.00.54%20PM.png)

**Comment by offirgolan** [comment]
@aaronbhansen unfortunately this is something I will not be supporting. The are many alternative solutions to solve this sort of issue:

- Create an ember-data transform
- Create a CP macro the will convert the given string value to a regex
- Or just use a one time CP to do the conversion

**Comment by aaronbhansen** [comment]
Sounds good. I already did one of the alternatives, but thought it might be nice for others, since it could be a common pattern.
