### ISSUE TITLE
Live demo page has unexpected behavior with tab key

### ISSUE THREAD

**Issue by jamespenick** [offirgolan/ember-cp-validations#328]
### Environment

- Ember Version:  2.4.2
- Ember CLI Version: 2.4.2
- Ember CP Validations Version: 2.6.1

### Steps to Reproduce
I initially noticed this issue on my local machine (running the versions noted above), but I also see the issue on the Ember CP Validations Demo page (http://offirgolan.github.io/ember-cp-validations/). Here are the steps to reproduce on the demo page:

1. Click the Username field. Don't type anything.
2. Press the tab key

Expected results:
The username field shows a validation error

Actual results:
Both the username and password fields show a validation error

**Comment by offirgolan** [comment]
@jamespenick this is a known Ember behavior. By default, values in the models are set to `null`. When you tab out of an input field, it changes it to an empty string which triggers the validations. A simple solution to this is adding `{ defaultValue: '' }` to your model attributes.

**Comment by jamespenick** [comment]
Hmm, that doesn't seem to work. If I do that, then neither the username nor the password field show a validation error. I'm looking for a solution that will still show a validation error for the username field, but not show a validation error for the password field.

**Comment by jamespenick** [comment]
I should also probably add that my problem isn't with the behavior when tabbing out of an input field. I fully expect tabbing out of the input field to trigger the validation. The problem is that tabbing into the password field is also apparently trigger a validation on that field.

**Comment by escobera** [comment]
I have to say that I found the "focus-in" validation a little strange on the demo as well.

**Comment by offirgolan** [comment]
Hi all,

I have an open PR (#331) which addresses this issue. Feel free to test out the new `validated-input` component and let me know if that works better 😸
