### ISSUE TITLE
Fixed email format validator with opt-out for top-level domain validation

### ISSUE THREAD

**Issue by indr** [offirgolan/ember-cp-validations#329]
@simonihmig changed the email regex of the format validator to include the presence of a top-level domain with PR #249 :+1: 

This will introduce a breaking change for people who expect email addresses like 'mail@localhost' to be valid. In the comments to the PR was this decision made:

- [x] Email format validator validates only if a top-level domain is present (PR #249)
- [ ] Introduce option `allowNonTld` with default value `false` (PR #330)
- [ ] Mention this breaking change together with the new option in the changelog

/cc @offirgolan

**Comment by offirgolan** [comment]
@indr perfect. Thank you 😸

**Comment by indr** [comment]
@offirgolan it's a pleasure! And that article on regular-expressions.info a nice refresher :smirk:
