### ISSUE TITLE
Ember.String.fmt is deprecated

### ISSUE THREAD

**Issue by indirect** [offirgolan/ember-cp-validations#33]
Inside `createErrorMessage`, the [usage of `Ember.String.fmt`](https://github.com/offirgolan/ember-cp-validations/blob/1c3f32a0c6636fd4a4f3387e1264311c1d472d29/addon/validators/base.js#L105) generates a deprecation warning: 

> Ember.String.fmt is deprecated, use ES6 template strings instead. [deprecation id: ember-string-utils.fmt] See https://babeljs.io/docs/learn-es6/#template-strings for more details.

**Comment by blimmer** [comment]
Yep, we're aware of this and this will likely be resolved by [our i18n solution](https://github.com/offirgolan/ember-cp-validations/issues/9#issuecomment-140155506)
