### ISSUE TITLE
Test issue: Validator not found of type: length

### ISSUE THREAD

**Issue by oskarrough** [offirgolan/ember-cp-validations#332]
Hi, I'm having trouble getting my standard model tests to pass when using validations. The validations work just fine in the app. When testing my model, I get the following error. Are there any extra test-steps to take when using ember-cp-validations?
```
Promise rejected after it exists: [ember-cp-validations] Validator not found of type: length.@ 141 ms
Source: 	
Error: [ember-cp-validations] Validator not found of type: length.
    at lookupValidator (http://localhost:7357/assets/vendor.js:79417:13)
    at http://localhost:7357/assets/vendor.js:79222:92
    at Array.map (native)
    at getCPDependentKeysFor (http://localhost:7357/assets/vendor.js:79219:37)
    at createCPValidationFor (http://localhost:7357/assets/vendor.js:79094:25)
    at http://localhost:7357/assets/vendor.js:79029:24
    at Array.reduce (native)
    at createAttrsClass (http://localhost:7357/assets/vendor.js:79028:39)
    at createValidationsClass (http://localhost:7357/assets/vendor.js:78945:22)
    at Class.<anonymous> (http://localhost:7357/assets/vendor.js:78826:25)
```

### Environment

- Ember Version: 2.7.0
- Ember CLI Version: 2.7.0
- Ember CP Validations Version: 3.0.0-beta.6

### Steps to Reproduce

```javascript
// model.js
import Model from 'ember-data/model';
import attr from 'ember-data/attr';
import {validator, buildValidations} from 'ember-cp-validations';

const Validations = buildValidations({
	title: [validator('length', {min: 5, max: 100})]
});

export default Model.extend(Validations, {
	title: attr('string')
});

// model-test.js
import Ember from 'ember';
import { moduleForModel, test } from 'ember-qunit';

moduleForModel('classified', 'Unit | Model | classified', {
  // Specify the other units that are required for this test.
});

test('it exists', function(assert) {
  let model = this.subject();
  assert.ok(!!model);
});
```

**Comment by offirgolan** [comment]
@oskarrough are you adding the validators that are used in your model via the `needs` array in your model test module?

[See example here](https://github.com/offirgolan/ember-cp-validations/blob/master/tests/unit/validations/nested-model-relationship-test.js#L4-L17)

**Comment by oskarrough** [comment]
No, I wasn't. Thank you very much, it works now.

Is it documented somewhere? Otherwise it would be great to have a small paragraph in the documentation.

**Comment by benjaminlong** [comment]
It is documented inside Ember Test documentation https://guides.emberjs.com/v2.7.0/testing/testing-models/

**Comment by offirgolan** [comment]
@oskarrough I swear I had some blurb about it in the docs but I guess I was wrong. Ill make sure to add something to it 😸
