### ISSUE TITLE
Debounce parameters not working properly

### ISSUE THREAD

**Issue by wayneiny** [offirgolan/ember-cp-validations#336]
### Environment

- Ember Version: 1.12
- Ember CLI Version: 0.2.3
- Ember CP Validations Version: 2.9.0

### Steps to Reproduce

I used the debounce parameter defined in validations in one of my model to delay validations. However, it doesn't seem to delay at all and always runs immediately.

**Comment by offirgolan** [comment]
@wayneiny please upgrade to 2.9.6, if you still face this issue again, please post some code snippets of your model and its validations.
