### ISSUE TITLE
Documentation doesn't explain anything about belongs-to or has-many

### ISSUE THREAD

**Issue by indirect** [offirgolan/ember-cp-validations#34]
Right now, the documentation says that you can validate associations using `validator('belongs-to')`, but this does not seem to produce any validation error messages under any circumstances—the association is not checked for presence, and the association's validation messages do not bubble up to the parent object's validation messages.

How does it work? What does it do? :)

**Comment by stefanpenner** [comment]
A place to look for now would be the tests, maybe that will provide some ideas. And maybe inspire said docs.

If I recall, there was an ember-data bug that prevented this library from working on newer version. For a time the feature was just disabled, pending upstream fix. This may or may not be the case right now. Merely providing potentially useful context

**Comment by indirect** [comment]
The tests provide no examples of using `belongs-to` validations beyond declaring the validator. There is no usage anywhere I could find. (and I did check there first before opening this ticket). :)

**Comment by offirgolan** [comment]
Can you provide an example of what exactly you're trying to do?

**Comment by indirect** [comment]
No, I can't... that's the point of this ticket. I don't know what belongs-to does, and the tests don't even provide an example of what belongs-to does... so I don't know what I can do. :)

(I was hoping that it would allow me to make an ember-data model include validation errors from a child, but I just wrote my own validations to handle that, so I don't care anymore.)

**Comment by stefanpenner** [comment]
closing this, and opening to two targeted issues:

- [missing tests](https://github.com/offirgolan/ember-cp-validations/issues/36)
- [example recommendations](https://github.com/offirgolan/ember-cp-validations/issues/35)
