### ISSUE TITLE
use public api on owner object

### ISSUE THREAD

**Issue by ssured** [offirgolan/ember-cp-validations#341]
Instead of `owner._lookupFactory` you should use `owner.resolveRegistration` which is public API. 

https://github.com/offirgolan/ember-cp-validations/search?utf8=%E2%9C%93&q=_lookupFactory

Just two occurrences need to be replaced.

**Comment by rwjblue** [comment]
Well, they aren't quite *exactly* the same.  `resolveRegistration` does not guarantee that the returned factory has been injected (with things like `owner`, manually setup injections, etc). It is intended to return the factory directly from the resolver. On the other hand, `owner._lookupFactory` returns a factory that has already been injected (via `.extend`).

We would need to review the specific usage scenarios in more detail to know if injections are actually needed to be sure we can swap...

**Comment by offirgolan** [comment]
@ssured is there a specific reason for your concern besides the usage of the private API? Have you faced any specific issues regarding this?

**Comment by ssured** [comment]
@offirgolan: no specific reason. I hit an error about a module which could not be found. Everyday I seem to learn something from @rwjblue, never knew there is a difference. I'm ok to close this issue as it's only about private API.

**Comment by offirgolan** [comment]
@ssured sounds good. Thank you for bringing this to our attention!
