### ISSUE TITLE
isValid and message are readonly in 3.0

### ISSUE THREAD

**Issue by v-shan** [offirgolan/ember-cp-validations#342]
Hi all,

The way we're handling server validations doesn't work in 3.0 because we use the isValid and message properties to dynamically mark fields with server errors. We don't use ember-data, we just make ajax requests to a server. 

Here's a simple example of how we handle an email taken error from the server:
```
const Validations = buildValidations({
  email: [
    validator('presence', {
      presence: true,
      messageKey: 'user_signup.email.required'
    })
  ]
});

Ember.Component.Extend(Validations, {
  email: null,
  myService: Ember.inject.service(),

  actions: {
    submit() {
      this.get('myService').post(email).catch((error) => {
        if (error is email taken) {
          this.set('validations.attrs.email.isValid', false);
          this.set('validations.attrs.email.message', 'email is taken');
        }
      })
    }
  }
})
```

Now that these fields are read-only we're not quite sure how to refactor for 3.0 (and we really want the sweet computed options :))

One way would be to create a separate `validOnServer` property for every field and put them into the Validations object, but this adds a lot of cruft that I think is really not necessary. 

Is there a better way to dynamically mark fields as invalid, OR can we remove read-only for these fields until there is a better solution in place?

**Comment by offirgolan** [comment]
@v-shan all properties under the validations object as well as the properties on the attrs object should have been readOnly from the beginning. 

That being said, I believe what you are looking for here is a [custom validator](http://offirgolan.github.io/ember-cp-validations/docs/classes/Custom.html).

```js
const Validations = buildValidations({
  email: [
    validator('presence', {
      presence: true,
      messageKey: 'user_signup.email.required'
    }),
    validator('my-server-validator')
  ]
});
```

```js
// validators/my-server-validator.js

export default Base.extend({
  myService: Ember.inject.service(),
  validate(value, options, model, attribute) {
   return this.get('myService').post(attribute).then(() => true, (error) => error.message);
  }
});
```

**Comment by v-shan** [comment]
Thanks @offirgolan! I also agree these properties should be read-only, but we're unable to get the behavior we want with custom validators. 

The custom validator works great in that case, but as a more realistic example let's consider a form with 10 fields. We post the form data to the server and expect that the server could return a server validation error for any of these 10 fields. It seems crazy to have to attach a custom validator to all 10 fields and to make 10 requests to the server. 

This seems like a common use case to me.

**Comment by v-shan** [comment]
Hmmmmm, on second thought I think we are relying too much on ember-cp-validations to handle this for us. I think it makes more sense for our field components to handle ember-cp-validation errors and server validation errors separately

**Comment by offirgolan** [comment]
@v-shan one solution I can think of is doing something like this:

```js
// validators/my-server-validator.js

const ServerValidator = Base.extend({
  myService: Ember.inject.service(),
  validate(value, options, model, attribute) {
    return this.get('myService.errors.' + attribute) || true;
  }
});

ServerValidator.reopenClass({
  getDependentsFor(attribute, options) {
    return [`model.myService.errors.${attribute}`];
  }
});
```

```js
// service/my-service.js

export default Ember.Service.extend({
  errors: null,
  validate(model) {
   // call server and get all errors
   this.set('error', validationsErrors);
  }
})
```

Now you can just do `this.get('myService').validate(model)` once and it will update the according attributes.

**Comment by tehmaestro** [comment]
Hi, I just upgraded to using this addon, and I was searching on how to implement the exact same functionality described in the initial post. Thank you so much for your suggestions, I got it working by using the following code:

```
// validators/server-validator.js
import Ember from 'ember';
import BaseValidator from 'ember-cp-validations/validators/base';

const ServerValidator = BaseValidator.extend({
  validationService: Ember.inject.service(),

  validate(value, options, model, attribute) {
    return this.get('validationService.errors.' + attribute) || true;
  }
});

ServerValidator.reopenClass({
  /**
   * Define attribute specific dependent keys for your validator
   *
   * [
   * 	`model.array.@each.${attribute}` --> Dependent is created on the model's context
   * 	`${attribute}.isValid` --> Dependent is created on the `model.validations.attrs` context
   * ]
   *
   * @param {String}  attribute   The attribute being evaluated
   * @param {Unknown} options     Options passed into your validator
   * @return {Array}
   */
  getDependentsFor(attribute, options) {
    return [`model.validationService.errors.${attribute}`];
  }
});

export default ServerValidator;
```

```
// service/validation-service.js
// My server side errors look something like this: {email: ['errorMessage1', 'errorMessage2'], password:['errorMessage1'] }

import Ember from 'ember';

export default Ember.Service.extend({
    i18n: Ember.inject.service(),
    errors: {},

    /**
     * Push errors
     */
    pushErrors: function(errors) {
        var self = this;
        for (let errorName in errors) {
            if (errors.hasOwnProperty(errorName)) {

                // Only take into account the first error
                var err = errors[errorName].objectAt(0);
                switch (err) {
                    // Localize the errors maybe?
                    case 'emailTakenCode':
                          err = this.get('i18n').t('email.taken');
               }
               // Set the error message on the errors attribute
                this.set('errors.' + errorName, err);
               
               // On field focus, remove the error
                Ember.$(id).focus(function () {
                    self.set('errors.' + errorName, undefined);
                    Ember.$(this).unbind("focus");
                });
            }
        }
    }
});
```

Then, in my component, I can do something like this:
```
import Ember from 'ember';
import { validator, buildValidations } from 'ember-cp-validations';

const Validations = buildValidations({
    email: [
        validator('presence', {
            presence: true
        }),
        validator('format', {
            type: 'email'
        }),
        validator('server-validator')
    ]
});


export default Ember.Component.extend(Validations, {
    validationService: Ember.inject.service(),

    actions: {
        sendServerRequest: function() {
            var self = this;
            this.sendRequest().then(function() {
                // success
            }, function(errors) {
                self.get('validationService').pushErrors(errors);
            });
        }
    }
});
```

**Comment by offirgolan** [comment]
@tehmaestro I think your solution is pretty solid. That's probably the same route I would take as well 😺

**Comment by tehmaestro** [comment]
One other think I forgot. If the user doesn't focus on the input to clear the server error, we should probably call a `this.get('validationService').clearErrors()` function on `willDestroyElement` hook of the component, and maybe inside `willTransition` action in the route.

 I will give you an example. If the user clicks on a button that shows a login popup, and upon entering wrong credentials, the `validationServer.errors.password` has the message `Incorrect username or password`, if the user simply dismisses the popup and then reopens it, the password field will have the server validation error attached to it.
