### ISSUE TITLE
Validations on destroyed model

### ISSUE THREAD

**Issue by wayneiny** [offirgolan/ember-cp-validations#348]
### Environment
- Ember Version: 1.12
- Ember CLI Version:1.0.0
- Ember CP Validations Version:2.9.0
### Steps to Reproduce

I'm doing some validations on an attribute of a model and using the validated-input example you provided in demo.

The thing is that after saving and setting the model to null, the validation is still running and it's causing this error
`ember.debug.js:15793Uncaught Error: Property set failed: object in path "model" could not be found or was destroyed.`

Is there a way to properly destroy the validations? Thanks in advance.

**Comment by offirgolan** [comment]
@wayneiny can you try upgrading to the latest patch release of v2.9 and see if that resolves your issue?

**Comment by offirgolan** [comment]
Closing as this issue has been abandoned. Feel free to reopen if needed.
