### ISSUE TITLE
Validating arrays

### ISSUE THREAD

**Issue by goofiw** [offirgolan/ember-cp-validations#350]
### Environment

- Ember CP Validations Version: 2.9.5

Is there any support for validating models with an Array?  I'm having trouble creating a custom validator that validates individual fields in the array while being able to access which field easily when I'm forced to return a string in a invalid case.

**Comment by offirgolan** [comment]
Are the objects in the array instances of Ember.Object?

```js
// models/parent.js
buildValidations({
  myArray: validator('belongs-to')
})
```

```js
// models/array-object.js
buildValidations({
  foo: validator('presence', true)
})
```

```js
this.get('parent.validations.myArray.isValid');
this.get('parent.myArray')[0].get('validations.isValid');
```

**Comment by offirgolan** [comment]
Closing as this issue has been abandoned.

**Comment by TommyUMS** [comment]
Hi. I have a plain json object in a component which I would like to validate:  {
  "personDetail": {
    "id": "",
    "ownerId": "",
    "ownerName": ,
    "firstName": "",
    "lastName": "",
    "organizations": "",
    "addressDetails": [
      {
        "channelId": "voice",
        "countryCode": "91",
        "number": "2064010000",
        "channelAddress": "912064010000"
      },
      {
        "channelId": "sms",
        "countryCode": "91",
        "number": "8881200000",
        "channelAddress": "918881200000"
      }
    ]
}

const Validations = buildValidations({
'personDetail.firstName': validator('presence', true),
**'personDetail.addressDetail.@each.number': validator('presence',true) ???????????**
});
export default Ember.Component.extend(Validations,{})

My problem is validating the addressDetail property which is an array, any ideas?

**Comment by allinne** [comment]
Hi!
I just came into the same issue, but my array contains strings and I use fragments-array type for it.
So I wrote:
`models/model.js`
```
import DS from 'ember-data';
import { array } from 'ember-data-model-fragments/attributes';
import { validator, buildValidations } from 'ember-cp-validations';

const Validations = buildValidations({
'toggleElements.[]': validator('presence', true)
});

export default DS.Model.extend(Validations, {
toggleElements: array(),
}
```
`templates/model.hbs`
```
{{#each model.toggleElements as |item|}}
{{v-get item 'isInvalid'}}
{{/each}}
```
And it doesn't work. Could you help me please.
