### ISSUE TITLE
Usage of `targetObject` in example app

### ISSUE THREAD

**Issue by ebryn** [offirgolan/ember-cp-validations#355]
I noticed that your example app at http://offirgolan.github.io/ember-cp-validations/ uses the private `targetObject` API to read `didValidate` off the `targetObject` (which happens to be the controller in this case, but isn't guaranteed to be).

This is going to be deprecated in 2.9 (related issue: https://github.com/emberjs/ember.js/issues/14168) and I think, it's fair to say, is considered a really bad practice. Components should be passed the data they need to do their job, not read data magically from the context they're evaluated inside of. Metaphorically, in JS, this would be akin to doing something like `arguments.caller.someLocalVariable`.

**Comment by offirgolan** [comment]
@ebryn I totally agree with you here. Once I have some spare time, Ill remove the `targetObject` dependency on the validated-input component.
