### ISSUE TITLE
Q: property path to collection items?

### ISSUE THREAD

**Issue by basz** [offirgolan/ember-cp-validations#365]
Hi,

What is the best way to generated a dynamic form, with a collection of regular objects?
How would I set the property path such that it will reference each item in the collection?

```
{{#bs-form formLayout="vertical" model=model action="submit" disabled=isProcessing}}
    {{#each model.phoneNumbers as |component|}}
        {{bs-form-element controlType="input" placeholder="phonenumber" property="model.phoneNumbers.[]" disabled=isProcessing showValidation=true}}
    {{/each}}
{{/bs-form}}
```

**Comment by offirgolan** [comment]
@basz I'm not sure I follow. Can you elaborate?

**Comment by basz** [comment]
[From](http://kaliber5.github.io/ember-bootstrap/api/classes/Components.Form.html):
When using Components.FormElements with their property set to property names of the form's validation enabled model, you gain some additional powerful features:

- the appropriate Bootstrap markup for the given formLayout and the form element's controlType is automatically generated
- markup for validation states and error messages is generated based on the model's validation (if available), when submitting the form with an invalid validation, or when focusing out of invalid inputs

```
{{#bs-form formLayout="horizontal" model=this action="submit"}}
  {{bs-form-element controlType="email" label="Email" placeholder="Email" property="email"}}
  {{bs-form-element controlType="password" label="Password" placeholder="Password" property="password"}}
  {{bs-form-element controlType="checkbox" label="Remember me" property="rememberMe"}}
  {{bs-button defaultText="Submit" type="primary" buttonType="submit"}}
{{/bs-form}}
```

So when I have a template that generates form-element through a loop (`model.phoneNumbers` is an array) how would I reference an property path that contains an index?

```
property="model.phoneNumbers[index]"
```

**Comment by offirgolan** [comment]
@basz I'm sorry but I dont believe that is possible unless ember-bootstrap supports such markup. I think this is a type of issue that should be created on ember-boostrap 😅

**Comment by basz** [comment]
Ok
