### ISSUE TITLE
validator option `if` is not documented anywhere

### ISSUE THREAD

**Issue by indirect** [offirgolan/ember-cp-validations#37]
Even though it is possible to add a condition to validators using the `if` option, it is not documented anywhere. For example:

```js
var Validations = buildValidations({
  title: validator('presence', {
    presence: true,
    "if": "enabled",
    attributeDescription: 'Title',
    message: 'must be provided when enabled'
});
```

This validator does actually use the `enabled` property as a condition to enable or disable this validation, and the `validations.messages` property includes the error message only if `enabled` is true, but the `if` option is not documented anywhere in the ember-cp-validations documentation.

**Comment by offirgolan** [comment]
Validators do not currently support an `if` option. The best way to achieve this use-case is to create a [custom validator](http://offirgolan.github.io/ember-cp-validations/docs/validators/custom/index.html). Within that, you have full access to the model, along with the ability to inject any service you might need for your validations.

**Comment by indirect** [comment]
Whoa... I have no idea why I thought that was working, then. Thanks for the clarification!

Adding support for conditional validation based on another property would be pretty awesome.

**Comment by jelhan** [comment]
I tried to implement a conditional validator and run in some problems with observers.

Assume we have two properties `name` and `forceName`. `name` must not be present if `forceName` is true. Seems to be easy using a validator function like this one:
```
var Validations = buildValidations({
  name: [
    validator(function(value, options, model, attribute) {
      return !Ember.isEmpty(value) || !model.get('forceName');
    })
  ]
});
```

But `name` is not revalidated when `forceName` changes. I ended up with an additional dependent validator just to have `name` revalidated if `forceName` changes. Therefore `forceName` also needs a validator which always returns true. Ended up with this code:

```
var Validations = buildValidations({
  forceName: validator(function() { return true; }),

  name: [
    validator(function(value, options, model, attribute) {
      return !Ember.isEmpty(value) || !model.get('forceName');
    }),
    validator('dependent', { on: ['forceName'] })
  ]
});
```

Doesn't look nice to me and `forceName` can not be validated. What is the correct way to write a conditional validator?

**Comment by offirgolan** [comment]
What about something like this:

```javascript
var Validations = buildValidations({
  name: validator('presence', { 
    presence() { 
      return !this.get('model.forceName ')
    },
    dependentKeys: ['forceName']
  })
});
```

**Comment by jelhan** [comment]
Oh I missed the `dependentKeys` option. It works like a charm. Thanks for the hint!
```
var Validations = buildValidations({
  name: validator(function(value, options, model, attribute) {
    return !Ember.isEmpty(value) || !model.get('forceName');
  }, {
    dependentKeys: ['forceName']
  })
});
```

I didn't really get the idea of Options as Functions and what for they should be used. Is there some more documentation or use cases anywhere?

**Comment by offirgolan** [comment]
Any option can act as a function which get executed right before validate gets called. The function also has the same context as the validator meaning you have access to all its attributes (like the model being evaluated). In your case an attribute must be present if another attribute on the model is true/false. That means that you can set `presence` at runtime depending on what the value of `forceName` is. See my example above. Hope that helps. If you're still confused feel free to ping me on slack or gitter :smile_cat: 

Im gonna go ahead an close this issue

**Comment by jherdman** [comment]
I'm not sure this is quite working correctly. I have a similar use case. Here's my validation mixin:

```javascript
import { validator, buildValidations } from 'ember-cp-validations';

export default buildValidations({
  value: validator('presence', {
    presence() {
      let model = this.get('model');

      let {
        required,
        includedInActivityResponse
      } = model.getProperties('required', 'included);

      return required && included;
    },

    dependentKeys: ['required', 'included']
  })
});
```

The first time this validation fires for an optional attribute it works for a blank value. The second time it fires when a value has been entered, the message is "This field must be blank". Both times the validation fires the above `presence()` method returns `false`.

Perhaps I'm misunderstanding the conversation here, but `presence()` returning false is effectively saying "this field is optional". Am I missing something?

**Comment by offirgolan** [comment]
From what I can see, you have the following 

```js
let {
        required,
        includedInActivityResponse
      } = model.getProperties('required', 'included')
```

but are returning `return required && included;`. Your variable names dont match.

**Comment by jherdman** [comment]
That's just my fat fingers changing variable names a bit for the purpose of this example :)

**Comment by jelhan** [comment]
You misunderstood the api. I got also confused first time. If presence returns `false` it means: Must not be presence. To make the field optional presence must be `null`.

**Comment by offirgolan** [comment]
> You misunderstood the api. I got also confused first time. If presence returns false it means: Must not be present. To make the field optional presence must be null. 

:+1: Thats right. 

@jherdman I think what you are looking for is `disabled`


```javascript
import { validator, buildValidations } from 'ember-cp-validations';

export default buildValidations({
  value: validator('presence', {
    presence: true,
    disabled() {
      let model = this.get('model');

      let {
        required,
        included
      } = model.getProperties('required', 'included');

      return !(required && included);
    },

    dependentKeys: ['required', 'included']
  })
});
```

**Comment by jherdman** [comment]
That worked like a charm! Many thanks, folks!

For any future users out there that feel a little lost, you probably made the same mistake I did and didn't read the [Validators](https://offirgolan.github.io/ember-cp-validations/docs/modules/Validators.html) documentation.

**Comment by NLearner** [comment]
Hi All, I am new to ember and ember-cp-validations. I have two fields in a model. One a list, another is another model. At a time, either only one should be present. How to define the presence attribute. I am getting confused.
