### ISSUE TITLE
How can I dynamically change validator options after creating?

### ISSUE THREAD

**Issue by elatonsev** [offirgolan/ember-cp-validations#392]
### Environment

- Ember Version: 2.9.1
- Ember CLI Version: 2.9.1
- Ember CP Validations Version: 3.1.2

### Steps to Reproduce

I need to change 'presence' option from 'true' to 'false' depending on dynamic form state.
If formState == 'a' 'name' field is required, if == 'b' then not, and if I dynamically toggled formState, validator should change its option.

I tried do that, but it didn't help:

```
//form/component.js	
init() {
    this._super(...arguments);

    const Validations = buildValidations({
        name: validator('presence', {
	    presence: Ember.computed('formState', function() {
	        return this.get('formState') == 'a';
	    })
	 }),
    });

    // I use ember-validated-form-buffer for buffering changes
    this.set('formValues', formBufferProperty('model', Validations));
}
```

Is there any way to solve it?

**Comment by offirgolan** [comment]
Try this:

```js
//form/component.js	
init() {
    this._super(...arguments);

    const Validations = buildValidations({
        name: validator('presence', {
	    presence: Ember.computed.equal('model.formState', 'a')
	 }),
    });

    // I use ember-validated-form-buffer for buffering changes
    this.set('formValues', formBufferProperty('model', Validations));
}
```

**Comment by elatonsev** [comment]
Thanks, it works!

But for those who use ember-validated-form-buffer: it is sensitive to imports order and should be above the ember-cp-validations, at least in current versions:

"ember-validated-form-buffer": "0.0.1",
"ember-cp-validations": "3.1.2",

**Comment by yandiro** [comment]
How can I do so in 2022? :sweat_smile:

**Comment by elatonsev** [comment]
Try this:
```
const Validations = buildValidations({
  name: [
    validator('presence', {
      presence: true,
      disabled: computed('model.formState', function () {
        return this.get('model.formState') == 'a';
      })
    })
  ]
});
```

**Comment by yandiro** [comment]
This also helped me:
https://github.com/poteto/ember-changeset-validations/issues/116#issuecomment-315304932
