### ISSUE TITLE
Needs Documentation

### ISSUE THREAD

**Issue by offirgolan** [offirgolan/ember-cp-validations#40]
This is just a comprehensive todo list on what needs to be documented or just needs more extensive documentation.

- [x] `belongsTo` validator
- [x] `hasMany` validator
- [x] `createErrorMessage` in BaseValidator
- [x] `needs` in unit testing
- [x] Better `v-get` helper 
- [x] Ember.Object container dependency

**Comment by ngouy** [comment]
Is there a way to access of an hasMany record not validated ? 
I mean having access to the attributes of the record record_B_1 that invalidate the record_A_1 where
model_A:
```
```
model_A has 'model_B: validator('has-many')' There is no docs about it

**Comment by ngouy** [comment]
Is there a way to access of an hasMany record not validated ? 
I mean having access to the attributes of the record_B that invalidate a record_A where
model_A:
```
const Validations = buildValidations({
  model_B: validator('has-many'),
});

export default Model.extend(Validations, {
  model_Bs: hasMany('model_B')
)};
```

no docs about it.
