### ISSUE TITLE
How to group validation rules?

### ISSUE THREAD

**Issue by estshy** [offirgolan/ember-cp-validations#420]
I have a kind of wizard with separate steps. The flow is bounded to one model and each step has own validation rules. I can not validate full model at once because user would see failed state on step one, which is wrong. On step one only validation rules connected to first step should be validated. 

I was trying to solve it by using `ObjectProxy` without effect.

```
return Ember.ObjectProxy.extend(Validations).create({
  content: this.modelFor('intake/client')
});
```

Is there any other way to approach this problem?

**Comment by offirgolan** [comment]
@estshy Im not really sure how you are validating each step but you can use the options provided on the [validate method](http://offirgolan.github.io/ember-cp-validations/docs/classes/Factory.html#method_validate). That way you can control which attribute you are validating and whether that group of attributes are indeed valid.

**Comment by offirgolan** [comment]
Another idea is to have your validations be on each step component. See [nested keys](http://offirgolan.github.io/ember-cp-validations/docs/modules/Advanced.html#nested-keys).

**Comment by offirgolan** [comment]
Closing as this issue has been abandoned. Feel free to reopen if needed.

**Comment by gosseti** [comment]
@estshy Apologies for picking up again on this issue… but was just wondering what solution you ended up going with here? I’m trying to tackle a similar problem in #519.

**Comment by estshy** [comment]
@gosseti I believe I've made validation rule for non existing property `my-group` defined as validation rule, making logical `AND` statement between passed model properties as parameters.

**Comment by gosseti** [comment]
I don't suppose you have a code example still available somewhere?

**Comment by estshy** [comment]
```
const Validations = buildValidations({
  "addressObject": validator('address', {
    value(model, attribute) {
      return this.get('model').get('address');
    },
    debounce: 500,
    disabled: computed('model.address.countryObject', 'model.address.zipcode', 'model.address.housenumber', function() {
      return isEmpty(this.get('model.address.countryObject')) || isEmpty(this.get('model.address.zipcode')) || isEmpty(this.get('model.address.housenumber'))
    }),
    messageKey: 'intake.validation.incorrectAddress'
  }),
  "address.countryObject": validator('presence', {
    presence: true,
    messageKey: 'intake.validation.countryRequired'
  }),
  "address.zipcode": validator('presence', {
    presence: true,
    messageKey: 'intake.validation.zipcodeRequired'
  }),
  "address.housenumber": validator('presence', {
    presence: true,
    messageKey: 'intake.validation.houseNumberRequired'
  }),
  'addressStepWasAccessed': validator('presence', true),
});
```

```
import BaseValidator from 'ember-cp-validations/validators/base';

const Address = BaseValidator.extend({
  i18n: Ember.inject.service(),
  maps: Ember.inject.service(),

  validate(value, options, model, attribute) {
    return this.get('maps').getCoordinates({
      country: Ember.get(value, 'country'),
      zipcode: Ember.get(value, 'zipcode'),
      housenumber: Ember.get(value, 'housenumber')
    })
      .then(location => true)
      .catch(() => this.get('i18n').t('validations.addressDoesNotExist').toString());
  }
});

Address.reopenClass({
  getDependentsFor(attribute, options) {
    return [
      'model.address.countryObject',
      'model.address.zipcode',
      'model.address.housenumber'
    ];
  }
});

export default Address;
```

**Comment by gosseti** [comment]
Super, thank you!
