### ISSUE TITLE
3.1.4 fails with plain property validations

### ISSUE THREAD

**Issue by BryanCrotaz** [offirgolan/ember-cp-validations#427]
### Environment

- Ember Version: 2.10.2
- Ember CLI Version: 2.10.0
- Ember CP Validations Version: 3.1.4

### Steps to Reproduce
```
const Validations = buildValidations({
	value: {
		validators: [
			validator("truthiness", { message: "Must not be blank" })
		]
	}
});
```

fails in `function createValidationsClass(inheritedValidationsClass)`

`var lastObject = get(_this, path.slice(0, path.length - 1).join('.'));`
`Assertion Failed: Cannot call `Ember.get` with an empty string`

**Comment by BryanCrotaz** [comment]
Argh - npm again installing wrong versions of stuff... sorry. Roll on yarn #1816

**Comment by alexmiddeleer** [comment]
@BryanCrotaz I know this is a bit old, but we're seeing this too and I am stuck on it. Do you know remember what you did by chance?

**Comment by BryanCrotaz** [comment]
Delete your node modules and upgrade everything. That's all I did. I think
I had an old version reference.

Npm outdated will help

Bryan Crotaz
Silver Curve

On 1 May 2017, at 21:29, Alex Middeleer <notifications@github.com> wrote:

@BryanCrotaz <https://github.com/BryanCrotaz> I know this is a bit old, but
we're seeing this too and I am stuck on it. Do you know remember what you
did by chance?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/offirgolan/ember-cp-validations/issues/427#issuecomment-298423855>,
or mute the thread

**Comment by alexmiddeleer** [comment]
Thanks, I think I tracked down my issue and it's actually a problem that updating to Ember 2.10 introduced. Created a separate issue for it. https://github.com/offirgolan/ember-cp-validations/issues/499
