### ISSUE TITLE
Cannot read property '_lookupFactory' of undefined on Ember.Object validation

### ISSUE THREAD

**Issue by web-melt** [offirgolan/ember-cp-validations#430]
### Environment

- Ember CLI Version: 2.9.1
- Ember CP Validations Version: 3.1.4

### Steps to Reproduce

Create Object with Mixin provided by buildValidations.
Instantiate object and try to validate on it.

Example code:

```

// controllers/test-controller.js

import Ember from 'ember';
import { validator, buildValidations } from 'ember-cp-validations';

let validations = buildValidations({
		email: {
			description: 'format',
			validators: [
				validator('format', {
						type: 'email',
						message: 'E-Mail address is not in the correct format',
				}),
			]
		},
	});
const DummyValidatorObject = Ember.Object.extend(validations, {});

export default Ember.Controller.extend({
	actions: {
		validateTest() {
			let validator = DummyValidatorObject.create({email: 'test@example.org'});
			console.log(validator.validateSync()); // throws error
		}
	}
});
```
I saw a possible solution in #48 but the solution seems to not work anymore.

Thanks in advance.

**Comment by web-melt** [comment]
Shame on me.. right after posting I found the solution in the documentation.
Sorry.

**Comment by Sandeeprao69** [comment]
Hey @theTechGuyy am facing same issue when trying to validate Ember object inside controller.
Can you please guide me to resolve this issues?

**Comment by Sandeeprao69** [comment]
TypeError: Cannot read property '__OWNER__ [id=__ember14906810689851125464105918]' of undefined 

This is what i got when i followed your instruction
Ember 2.12 
Ember-cli 2.12

**Comment by theTechGuyy** [comment]
Hi @Sandeeprao69,

I followed the instructions here:
http://offirgolan.github.io/ember-cp-validations/docs/modules/Basic.html#a-note-on-testing--object-containers

Check this - maybe it will help you. If not - a code sample would be good to have

**Comment by Sandeeprao69** [comment]
Hey
My Validation file
`import { validator, buildValidations } from 'ember-cp-validations';

const guestValidation = buildValidations({
'guestDetails.email': [
validator('presence', true),
validator('format', {
type: 'email',
message: 'Please enter a valid email address'
})
],
'guestDetails.firstName': [
validator('presence', true),
],
'guestDetails.lastName': [
validator('presence', true),
],
'guestDetails.dateOfBirth': [
validator('presence', true),
],
'guestDetails.phoneNumber': [
validator('presence', true),
validator('length', {
min: 10,
max: 10
})
]
});

export default guestValidation`

My Controller

import Ember from 'ember';
import guestValidations from '../validators/add-guest-validations'
export default Ember.Controller.extend( {
validationObj:Ember.Object.extend(guestValidations);
guestDetails:validationObj:Ember.create(Ember.getOwner(this).ownerInjection(),{
name:'',
})

}
It gives me error.

**Comment by Sandeeprao69** [comment]
it gives Cannot read property 'ownerInjection' of undefined

**Comment by offirgolan** [comment]
@Sandeeprao69 I suggest you do something like this in your controller.

```js
import Ember from 'ember';
import GuestValidations from '../validators/add-guest-validations'

const ValidationObject = Ember.Object.extend(GuestValidations);

export default Ember.Controller.extend({
    guestDetails: Ember.computed(function() {
      return Ember.create(Ember.getOwner(this).ownerInjection(), {
          name: '',
      });
    })
});
```
