### ISSUE TITLE
Help validating arrays

### ISSUE THREAD

**Issue by TommyUMS** [offirgolan/ember-cp-validations#431]
### Environment

- Ember Version: 2.10.0
- Ember CLI Version: 2.10.0
- Ember CP Validations Version: 3.1.4

Hi. I have a plain json object in a component which I would like to validate: {
"personDetail": {
"id": "",
"ownerId": "",
"ownerName": ,
"firstName": "",
"lastName": "",
"organizations": "",
"addressDetails": [
{
"channelId": "voice",
"countryCode": "91",
"number": "2064010000",
"channelAddress": "912064010000"
},
{
"channelId": "sms",
"countryCode": "91",
"number": "8881200000",
"channelAddress": "918881200000"
}
]
}

const Validations = buildValidations({
'personDetail.firstName': validator('presence', true),
'personDetail.addressDetail.@each.number': validator('presence',true) ???????????
});
export default Ember.Component.extend(Validations,{})

My problem is validating the addressDetail property which is an array, any ideas?

**Comment by offirgolan** [comment]
@TommyUMS you would need wrap each object in the addressDetails in an Ember.Object with its own validations and then use the `has-many` validator on the personDetails object.

```js
const AddressDertailsValidations = buildValidations({
  number: validator('presence', true)
});

const AddressDetail = Ember.Object.extend(AddressDertailsValidations);

const Validations = buildValidations({
  'personDetail.firstName': validator('presence', true),
  'personDetail.addressDetails': validator('has-many')
});

export default Ember.Component.extend(Validations, {
  personDetail: null,

  init() {
    this._super(...arguments);

    // Note: This doesnt need to be in init, just anytime after personDetail is being set.

    const personDetail = this.get('personDetail');
    const owner = Ember.getOwner(this);

    // Wrap the addressDetail objects in an ember object with our validations
    personDetail.addressDetails = personDetail.addressDetails.map(a => AddressDetail.create(owner.ownerInjection(), a));

    // Access those validations
    this.get('validations.attrs.personDetail.firstName.isValid');
    this.get('validations.attrs.personDetail.addressDetails.isValid');

    // Access individual validations
    personDetail.addressDetails[0].get('validations.attrs.number.isValid');
  }
});
```

**Comment by offirgolan** [comment]
Closing as this issue has been abandoned. Feel free to reopen if needed.

**Comment by TommyUMS** [comment]
Thanks for the help @offirgolan :)

**Comment by offirgolan** [comment]
No problem at all 😸

**Comment by JackEllis** [comment]
@offirgolan This issue is back in the 4 beta on Ember 3.3.0. When you call save() on DS.model, the serialize() method (to json) still has those __owner_override variables along with the validations.

I'm wondering, is there anything in place to remove this on serialization? I think you'd want to keep the validation object in place, but have some sort of 'Child Object Mixin' that automatically removes the pieces that aren't needed on serialization. Although, when doing that, the validation ceases to work once the model saves.

Any thoughts?

**Comment by JackEllis** [comment]
@offirgolan I've done some further debugging and has-many works fine. The issue comes up when you use DS.attr('array') within a DS.Model
