### ISSUE TITLE
Proposal: description should also accept a function

### ISSUE THREAD

**Issue by patric-eberle** [offirgolan/ember-cp-validations#432]
We create a dynamic form, where the fields and labels are delivered by the server. So we actually don't know the name of the field. If description would accept a function, we could get the description name from the model.

```
const Validations = buildValidations({
  value: validator('presence', {
    presence: true,
    disabled: Ember.computed.readOnly('model.isDisabled.content'),
    description(model) {
         return model.get('fieldName');
    }
  })
});
```

**Comment by patric-eberle** [comment]
I just discovered, that this at least is working with Ember.computed() values (like disabled in example).

**Comment by offirgolan** [comment]
@patric-eberle you can use a CP for the description.

```js
const Validations = buildValidations({
  value: validator('presence', {
    dependentKeys: ['model.fieldName'],
    presence: true,
    disabled: Ember.computed.readOnly('model.isDisabled.content'),
    description: computed(function() {
      return model.get('fieldName');
    })
  })
});
```

If you want the description to be recomputed each time, just add a `.volatile()` to the CP.

**Comment by patric-eberle** [comment]
@offirgolan Thx. That will do :)
