### ISSUE TITLE
Decoupled i18n Addons

### ISSUE THREAD

**Issue by offirgolan** [offirgolan/ember-cp-validations#44]
As discussed in #43 and suggested by @jasonmit, we have decided that it would be better to completely decouple the i18n solutions and leave the work to separate addons that will extend the `message` validator with the logic necessary. 

- [x] Support for Ember-Intl
- [x] Support for Ember-I18n
- [x] Support for attributeDescription

Once these two will be supported we can issue a v2.0 release.

**Comment by jasonmit** [comment]
I can complete these both over the weekend :+1:

**Comment by offirgolan** [comment]
Great! Once you're done just post the links on here and I'll update the docs :smile:

**Comment by jasonmit** [comment]
attributeDescription will cause problems, as I'll need a way of overriding that as well when you're generating the message.

**Comment by jasonmit** [comment]
https://github.com/jasonmit/ember-i18n-cp-validations
https://github.com/jasonmit/ember-intl-cp-validations

both published to npm as 0.0.1.  We'll want to fix `attributeDescription` though as part of this issue.

**Comment by offirgolan** [comment]
Oh man I didnt even think about that. What if I create another method in `messages`

```js
getAttributeDescriptionFor(attribute, options) {
  return options.attributeDescription || 'This Field'
}
```

Then in your translation you can maybe have something like the following

```yaml
errors:
  attributeDescriptions:
    username: 'Username'
```

**Comment by offirgolan** [comment]
Also in regards to your log message, just so I dont forget, the link to the message docs will be wrong once the new docs get published. It will be `http://offirgolan.github.io/ember-cp-validations/docs/messages/index.html`.

**Comment by jasonmit** [comment]
> Oh man I didnt even think about that. What if I create another method in messages

Sounds good :+1:

**Comment by offirgolan** [comment]
All necessary changes are now in master so im gonna go ahead and close this issue.
