### ISSUE TITLE
question on `description` field

### ISSUE THREAD

**Issue by jamesdixon** [offirgolan/ember-cp-validations#448]
Hi,

I have a format validator with a `description` field. I would expect that the `description` would override any defaults.

```js
    validator('format', {
      regex: /^(?=.{8,32}$)(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9]).*/,
      description: "Your password doesn't meet the above requirements."
    })
```

Expected result when field is invalid:

`Your password doesn't meet the above requirements.`

Actual result:

`Your password doesn't meet the above requirements. is invalid`

Is this intended or am I using it incorrectly?

Thanks!

### Environment

- Ember Version: 2.11
- Ember CLI Version: 2.11
- Ember CP Validations Version: 3.2.2

**Comment by offirgolan** [comment]
@jamesdixon that is definitely not intended behavior. I'll take a look into this.

**Comment by offirgolan** [comment]
@jamesdixon haha I think we both got confused. I think what you are looking for is the `message` option.

```js
validator('format', {
      regex: /^(?=.{8,32}$)(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9]).*/,
      message: "Your password doesn't meet the above requirements."
    })
```

The `description` option is just the error message prefix which is defaulted to `This field`.

**Comment by jamesdixon** [comment]
Well, shit. My bad, @offirgolan! Sorry for wasting your time!

**Comment by offirgolan** [comment]
No worries 😸
