### ISSUE TITLE
Allow message on custom validators to be set via options

### ISSUE THREAD

**Issue by chadian** [offirgolan/ember-cp-validations#45]
For all the validators, except ones that are custom, the message is set on the `options` object. It would be handy if this was available for custom validators as well:

```
var Validations = buildValidations({
  hello: [
    validator(function(value) {
      return false;
    }, { message: 'Sorry, this greeting will never pass' }),

    validator('length', {
      is: 25,
      message: 'The greeting should be 25 characters long'
    })
  ]
});
```

The function passed could return `true` or `false`, with the message still passed in via the options and used when the case is `false`. This would help where people use quick boolean helpers for the function.

**Comment by offirgolan** [comment]
Im not sure I follow. Could you not do something like this

```js
var Validations = buildValidations({
  hello: [
    validator(function(value, options) {
      return options.message;
    }, { message: 'Sorry, this greeting will never pass' }),
  ]
});
```

or even

```js
var Validations = buildValidations({
  hello: [
    validator(function(value) {
      return 'Sorry, this greeting will never pass';
    }),
  ]
});
```

**Comment by chadian** [comment]
You're absolutely right, that's the way you can pass things from the options, or just return the string directly. What I was thinking that you could use a utility function, maybe something you've used elsewhere that relates to the property that you're validating. As an example I'll say `isValidSkuFormat`, that returns a `boolean`.

The validation would look something like this:
```
import SkuHelpers from '../utils/sku-helpers';

var Validations = buildValidations({
  sku: validator(SkuHelpers.isValidSkuFormat, { message: 'Please use a valid sku' })
});
```
This keeps the re-usability of the helper concise in implementation without having to wrap it in a function to set things up. The true/false logic is kept separate from the message, with a similar style as the other validators. I could see enough people possibly having these single parameter helpers, with a true/false return, that could be usable in this case. You're right though, you can access the options argument and pull this through in a way that is organized, with only a few more lines.

Just a suggestion, in any case thanks for this project. Everything has been really a pleasure to use, and is versatile in combining with custom functions.

**Comment by offirgolan** [comment]
I think you might want to try [creating a custom validator](http://offirgolan.github.io/ember-cp-validations/docs/validators/custom/index.html). That should solve your use-case while also giving you the ability to inject services like an ember-data store.

**Comment by chadian** [comment]
Sounds good, thanks for the feedback.
