### ISSUE TITLE
Feature Request: Do not include CSS by default

### ISSUE THREAD

**Issue by tsteuwer** [offirgolan/ember-cp-validations#461]
I would like to not include the CSS that comes with this plugin. I'd like to add my own and unfortunately, this CSS will always be in my payload. We should have an option via our ``config/environment.js`` that allows us to basically do:

```
emberCpValidations: {
    includeCss: false, // have it default to true but those who dont need it can set this to false
},
```

**Comment by rwjblue** [comment]
:+1: for making CSS optional, but we definitely don not want to put build time configuration into `config/environment.js` (the serialized results of this file are included in index.html at runtime, and there is no need for this type of build time only setting in the final built assets).

**Comment by tsteuwer** [comment]
@rwjblue so ember-cli-build.js?

**Comment by rwjblue** [comment]
yep

**Comment by offirgolan** [comment]
Wait... this addon doesnt come with any CSS. Am I missing something here?

**Comment by rwjblue** [comment]
haha, I dunno, I was just replying to the OP's suggestion that we use `config/environment.js` 😝

**Comment by offirgolan** [comment]
@rwjblue LOL 

@tsteuwer Im 100% certain this addon doesnt come with any css. The only css here is in the demo app.

**Comment by tsteuwer** [comment]
Did I have a brain fart? The developer I was working with told me the inputs he was working with had a default style. If this is the case I sincerely apologise to everyone involved lol...

**Comment by offirgolan** [comment]
@tsteuwer no worries at all 😺
