### ISSUE TITLE
Validator for currency

### ISSUE THREAD

**Issue by SatVel** [offirgolan/ember-cp-validations#469]
@offirgolan - 

Hi ! , 
I just wanted to know if there is a ready-made validator for validating currency fields. For e.g. My application has several currency fields and I want to allow commas as thousand separators for e.g. 1,000 and 1.000 if the locale is German. I am currently using the number validator for validating these fields, but the field displays a validation message if I enter a value like 1,000 as it considers the comma as invalid.

Thanks and Regards
Satyen

### Environment

Ember Version: 2.8.3
Ember CLI Version: 2.8.0
Ember CP Validations Version: 3.1.0

**Comment by offirgolan** [comment]
@SatVel no there isnt. You are welcome to use the `format` validator and provide it a custom regex that would match that of your currency format or you can simply create a custom validator.

**Comment by offirgolan** [comment]
Closing as this issue has been abandoned. Feel free to reopen if needed.
