### ISSUE TITLE
Bug? Presence validation allows whitespace only strings.

### ISSUE THREAD

**Issue by luketheobscure** [offirgolan/ember-cp-validations#470]
`presence` validator should fail if the given field consists of only whitespace.

### Environment

- Ember Version: 2.11.0
- Ember CLI Version: 2.11.0
- Ember CP Validations Version: 3.2.4

### Steps to Reproduce

Build a validator with:

```
Validations = buildValidations({ foo: validator('presence', true) })
```

Now set `foo` to be something like `'  '`. Model is still valid.

**Comment by offirgolan** [comment]
@luketheobscure 

```js
Validations = buildValidations({ foo: validator('presence', { presence: true, ignoreBlank: true }) })
```

**Comment by luketheobscure** [comment]
Well you guys should really put that in the docs. Oh... what's that? [You totally did](http://offirgolan.github.io/ember-cp-validations/docs/classes/Presence.html#method_validate)? Well never mind then. Sorry about that.
