### ISSUE TITLE
v-get helper to support validateAttribute

### ISSUE THREAD

**Issue by danidr** [offirgolan/ember-cp-validations#476]
I have a feature request regarding the v-get helper.
Right now, it can only retrieve validation status from the model or each property in the model
 It would be very interesting to also be able to run the validateAttribute method somehow from the v-get helper, so that a value can be checked BEFORE being inserted into the model.
Thank you!

**Comment by offirgolan** [comment]
@danidr at this moment, that would not be possible. The `v-get` helper is actually a HTMLBars transform into `get`. You can have similar functionality using `ember-changeset` + `ember-changeset-cp-validations`

**Comment by offirgolan** [comment]
Closing as this issue has been abandoned. Feel free to reopen if needed.
