### ISSUE TITLE
Confirmation validation behavior causes strange UX

### ISSUE THREAD

**Issue by blimmer** [offirgolan/ember-cp-validations#5]
it's strange to me that there's a validation error message before the user even starts typing the confirmation.

For example, consider a password reset form:
* The user gets here and needs to fill out their password and do a confirmation
* The types their password the first time
* They see a message that the passwords don't match, but they haven't even entered the confirmation yet

For example:

![](http://zippy.gfycat.com/DecimalTenseAnemonecrab.gif)

What do you think about applying the confirmation to the actual `${foo}Confirmation` property itself instead of the `${foo}` property? That way you can associate the error with the confirmation field if it's wrong.

**Comment by blimmer** [comment]
This is a much better UX, IMO:

![](http://zippy.gfycat.com/PopularImmediateCougar.gif)

I wrote a custom validator to do this in my app and am happy to port it over if this is the direction you guys want to go.

**Comment by stefanpenner** [comment]
ya, the idea is to provide helpers (for the UI) to allow the users to opt into various forms.

**Comment by blimmer** [comment]
1.0.1 fixed this.
