### ISSUE TITLE
Cannot stringify Ember.Object with ownerInjection()

### ISSUE THREAD

**Issue by rynam0** [offirgolan/ember-cp-validations#507]
### Environment

- Ember Version: 2.11.3
- Ember CLI Version: 2.11.1
- Ember CP Validations Version: 3.3.2

Hi!  Thanks for the awesome library!

### Steps to Reproduce
I have followed steps found in the docs and in other issues on how to validate `Ember.Object`s using the `getOwner` API.  Validations are found and work really well.  The problem arises when trying to `JSON.stringify(...)` the validated `Ember.Object` instance.

I doubt this is an issue with `ember-cp-validations` but was hoping you might have some insight into how to deal with this issue.  

To reproduce:

    const FooValidations = buildValidations({ name: validator('presence', true) });
    const Foo = Ember.Object.extend(FooValidations);

    let bar = Foo.create(Ember.getOwner(this).ownerInjection(), { name: 'baz' });
    JSON.stringify(bar);

This results in the following:

    TypeError: Converting circular structure to JSON
        at JSON.stringify (<anonymous>)
        at Class.save (index.js:7)
        at Backburner.join (ember.debug.js:771)
        at Function.run.join (ember.debug.js:22291)
        at ember.debug.js:9935
        at Object.flaggedInstrument (ember.debug.js:18477)
        at Class.<anonymous> (ember.debug.js:9934)
        at ember.debug.js:11629
        at Object.flaggedInstrument (ember.debug.js:18477)
        at ember.debug.js:11628

Ember Data Models do not exhibit this behavior (guessing due to serializers stripping out the internals).  Unfortunately for this case I am unable to use an Ember Data Model.  
Any insight, workarounds, etc. you may have would be greatly appreciated.  

Thanks!

**Comment by rynam0** [comment]
I've worked around the issue by overriding `RESTAdapter.ajaxOptions` to ignore the injected owner:

      ajaxOptions(url, type, options) {
      let hash = options || {};
      hash.url = url;
      hash.type = type;
      hash.dataType = 'json';
      hash.context = this;

      if (hash.data && type !== 'GET') {
        hash.contentType = 'application/json; charset=utf-8';
        hash.data = JSON.stringify(hash.data, this._stringify_replacer);
      }

      let headers = get(this, 'headers');
      if (headers !== undefined) {
        hash.beforeSend = function (xhr) {
          Object.keys(headers).forEach((key) =>  xhr.setRequestHeader(key, headers[key]));
        };
      }

      return hash;
    },

    _stringify_replacer(key, value) {
      if (key.startsWith('__OWNER__')) {
        return undefined;
      }
      return value;
    }

While this gets me around the issue, I wonder if there is something that could be done to allow validated Ember Objects requiring an owner injection to work more seamlessly with the default `ajaxOptions` function that calls JSON.stringify on the validated instance?

**Comment by offirgolan** [comment]
@rynam0 this seems to be an Ember core issue and should be posted on the ember.js repo since this only has to do with `ownerInjection`. Hopefully they can be of some more help there.

**Comment by rynam0** [comment]
Ok, that's what I was thinking but wanted to see if you had run into this before.
I'll create an issue in the appropriate repo. 
Thanks!

**Comment by offirgolan** [comment]
@rynam0 I havent ran into that issue before but I suggest trying it out in an ember-twiddle as well without ember-cp-validations so you can provide reproductions.

**Comment by rynam0** [comment]
Sounds, good.  Thanks again :)
