### ISSUE TITLE
Should make clear to check `validations.isValid` > `model.isValid`

### ISSUE THREAD

**Issue by Gowiem** [offirgolan/ember-cp-validations#510]
## Info

I've been adding `cp-validations` to my app and couldn't get them working for a bit due to `model.get('isValid')` always returning true after calling `validate()`. I used the Ember inspector to dig into the model and the validations mixin and saw that they were running and had the correct state of invalid. After banging on this for a while, I finally saw in the dummy app that you're expected to check the `validations.isValid` and not the `model.isValid`. This was confusing to me and I think it could be cleared up in documentation. I realize if I watched the video again that this is probably made clear, but I watched that one day, came back, and I had no clue. Just figured I'd save somebody else the headache of having to debug by trying to make this more clear. 

Let me know you'd like me to clarify anything. Thanks!

### Environment

- Ember Version: 2.13.0
- Ember CLI Version: 2.13.0
- Ember CP Validations Version: 3.3.2

**Comment by Gowiem** [comment]
After digging around more, it does seem that this is well documented in the [`Factory#validate`](https://offirgolan.github.io/ember-cp-validations/docs/classes/Factory.html#method_validate) docs by showing a clear example. I think my only issue here is that this seemed hidden to me and I found these docs as part of looking up building a custom validator. I think docs that show usage of `validate` and checking validations > model would clear this up usage of this library up a lot.

**Comment by offirgolan** [comment]
@Gowiem please refer to the docs [here](http://offirgolan.github.io/ember-cp-validations/docs/modules/Accessing%20Validations.html) on how to access the validations.

You should be using `model.get('validations.isValid')` not `model.get('isValid')` 😄

**Comment by Gowiem** [comment]
@offirgolan I completely passed over that somehow. May be me being braindead, but I guess I didn't expect the `validate` usage to be covered in 'Accessing Validations' I figured that would be accessing the validation messages. Putting a basic usage of `validate()` + `validations.isValid` in "Usage > Basic" would make sense to me, but no big deal. 

Thanks for the help @offirgolan. Closing out.

**Comment by offirgolan** [comment]
No worries at all! I know the docs can be a bit confusing. Maybe I should link out to `Accessing Validations` from the Basic Usage page 😄
