### ISSUE TITLE
Integration test for a form in a component

### ISSUE THREAD

**Issue by stephanebruckert** [offirgolan/ember-cp-validations#515]
I'm struggling to write a simple integration test and can't find any example. This test is quite simple: by default the submit button is disabled and it should become enabled when `username` is passed a valid nickname. 

But the following doesn't pass even though I don't have any `debounce`.
```
import { moduleForComponent, test } from 'ember-qunit';

import hbs from 'htmlbars-inline-precompile';

moduleForComponent('user/signup-form', 'Integration | Component | user/signup form', {
  integration: true
});

test('submit enables when filled in correctly', function(assert) {
  this.render(hbs`{{user/signup-form}}`);
  this.$('input[name="username"]').val('my-nickname');
  assert.equal(self.$(':disabled').length, 0);
});
```

My component looks like this:

```
<form>
  {{validated-input autofocus="autofocus" model=this valuePath='username' placeholder='Username' didValidate=didValidate}}
  <div class="form-group">
    <button disabled="{{if this.validations.isValid "" "disabled"}}"
            type="submit" class="btn btn-primary btn-block"
            {{action 'submit'}}>Create Your Account</button>
  </div>
</form>
```

 - I've looked at the integration tests in this repo https://github.com/offirgolan/ember-cp-validations/tree/master/tests/integration but I can only find tests that check the model directly,  which is probably too specific for a "normal usage" of ember-cp-validations?

 - Do you think I should rather content myself with acceptance tests such as here https://github.com/offirgolan/ember-cp-validations/blob/master/tests/acceptance/dummy-index-test.js?

Thanks for your help

**Comment by stephanebruckert** [comment]
After all I'm rather writing acceptance tests. However they are a bit slow. Would still love your help on this!

**Comment by offirgolan** [comment]
@stephanebruckert when you run this line:

```
this.$('input[name="username"]').val('my-nickname');
```

Can you verify that the value propagates to the correct property which is being validated?

**Comment by offirgolan** [comment]
Closing as this issue has been abandoned. Feel free to reopen if needed.
