### ISSUE TITLE
Introduction to ember-cp-validations on Global Ember Meetup?

### ISSUE THREAD

**Issue by taras** [offirgolan/ember-cp-validations#52]
Would you be interested in giving an *Introduction to ember-cp-validations* lightning talk at one of the future Global Ember Meetups?

The talk is usually 15 minutes long and answers the following questions:

1. What problem is the addon trying to solve?
2. How to get started?
3. How should it be used?
4. What should person be aware of?

We'll produce a video that you can link to in your README. You can see existing videos here https://vimeo.com/album/3607049

What do you think?

**Comment by chadian** [comment]
:+1: I would enjoy seeing that.

**Comment by offirgolan** [comment]
I would love to. Any chance I can get some more details?

**Comment by taras** [comment]
@offirgolan definitely, we have 4 events scheduled and more in the works for next year. How much time do you need to prepare a talk?

**Comment by offirgolan** [comment]
Just sent you a PM on slack. I think it would be easier that way lol :smile_cat:

**Comment by offirgolan** [comment]
Okay so the final date is Saturday, November 7, 2015 · 09:00 AM · Pacific Time (US & Canada). You can sign up [here](https://www.bigmarker.com/global-ember-meetup/Ember-Authentication-Day)!
