### ISSUE TITLE
`allowNonTld: false` should not accept single-character top-level domain names

### ISSUE THREAD

**Issue by stephanebruckert** [offirgolan/ember-cp-validations#524]
The following validation:

```
email: {
    type: 'email',
    allowNonTld: false,
}
```

should not accept `john@domain.t` when we know that [there is currently no single-character top-level domain names](https://stackoverflow.com/a/21872376/1515819):

> #### Is it possible to have single character for top level domain name? (e.g.: lockevn.c)
> Yes, it is possible to have single character for top level domain name, however, there are currently no single character TLDs in the root.

-------------

I've noticed this issue when a single-character domain would be accepted on the Ember side while not on the Rails side ([here with Devise](https://github.com/plataformatec/devise/blob/master/lib/devise/models/validatable.rb)) which leads to inconsistencies between front-end/back-end validations.

If you accept, I would be happy to send over a PR

Thank you

**Comment by offirgolan** [comment]
@stephanebruckert PR is def. welcome. The line you will need to modify is [here](https://github.com/offirgolan/ember-validators/blob/master/addon/format.js#L80)

**Comment by stephanebruckert** [comment]
Just realized this is already implemented, we can use `minTldLength`!

https://github.com/offirgolan/ember-validators/blob/master/tests/unit/validators/format-test.js#L131
