### ISSUE TITLE
v-get can't be used inside {{if}} 

### ISSUE THREAD

**Issue by iivvoo** [offirgolan/ember-cp-validations#53]
<div class="form-group {{if (v-get model property 'isInvalid') 'has-error' }}">
      <label for="email">{{label}}</label>
      {{input value=(mut (get model property)) placeholder=placeholder class='form-control' type=type}}
      {{#if (v-get model property 'isInvalid')}}
        <div class="error">
          {{v-get model property 'message'}}
        </div>
      {{/if}}
    </div>

The (v-get) inside the class="" (first line) isn't handled properly, resulting in "A helper named 'v-get' could not be found"

The other cases (of course) work fine.

**Comment by rwjblue** [comment]
Thanks for reporting!

Demo JSBin here: http://jsbin.com/racogu/edit?html,js,output

**Comment by rwjblue** [comment]
@offirgolan - Looks like we need to also handle attributes?

**Comment by offirgolan** [comment]
Hmmm we already handle attributes (See [here](https://github.com/offirgolan/ember-cp-validations/blob/master/htmlbars-plugins/v-get.js#L75-L86)) but yeah this is a special case. Ill take a closer look into this.

**Comment by offirgolan** [comment]
Fixed with `v2.0.1`. Thanks for pointing this issue out!
