### ISSUE TITLE
Depend on other addons

### ISSUE THREAD

**Issue by villander** [offirgolan/ember-cp-validations#542]
I have a private addon, that have `ember-cp-validations` in `dependencies` but in my consumer app ember-cp-validations does not work as it should, and then I'm forced to install the addon also in my app.

Reference: https://dockyard.com/blog/2015/03/22/tips-for-writing-ember-addons
https://github.com/BrianSipple/ember-stagger-swagger/issues/1#issue-145557246

**Comment by villander** [comment]
#334

**Comment by offirgolan** [comment]
@villander did the solution from #334 solve your issue?

**Comment by offirgolan** [comment]
Closing as this issue has been abandoned. Feel free to reopen if needed.
