### ISSUE TITLE
Observe model validity

### ISSUE THREAD

**Issue by CrushedPixel** [offirgolan/ember-cp-validations#543]
Is it possible to observe a cp-validated model's validity?

I have tried

```js
  observeModels: Ember.observer(
    'model.validations.isValid', function() {
    // [...]
```
and
```js
  allValid: Ember.computed(
    'model.validations.isValid', function() {
    // [...]
```

but neither of them trigger at all, even when the model becomes valid, although I can access `model.validations.isValid` using `this.get()` otherwise.

Any ideas?

**Comment by offirgolan** [comment]
@CrushedPixel I made [a simple twiddle ](https://ember-twiddle.com/e5a8b3e52c58fec0f4858bbd2fe3f8d8?openFiles=templates.application.hbs%2C) and everything seems to be working.

**Comment by CrushedPixel** [comment]
I tried to reproduce my own issue with jsfiddle as well, but it seems to work even with a more complex setup...
Will close and debug this myself. Thanks!

**Comment by CrushedPixel** [comment]
Turns out the issue was caused by me not consuming `validations.isValid`, which is a computed property...

I was incredibly lucky to stumble across this issue on ember.js: https://github.com/emberjs/ember.js/issues/15679

I also had to check for validity on init once to enable the observer, not sure why that is. I'm just glad it works now!
