### ISSUE TITLE
validateSync throws Assertion Failed Error

### ISSUE THREAD

**Issue by gajewsky** [offirgolan/ember-cp-validations#544]
### Environment

- Ember Version: 2.8.0
- Ember CLI Version: 2.8.3
- Ember CP Validations Version: 3.5.0

### Steps to Reproduce
1. Add simple validation to model
2. run model.validateSync()
3. EmberError is thrown with message 
```
EmberError {description: undefined, fileName: undefined, lineNumber: undefined, message: "Assertion Failed: [validator:presence] [home.content] option 'presence' is required", name: "Error", …}
```
4. Expected not to throw error but return validation object instead.
  
Is it expected behaviour or am I missing something

**Comment by offirgolan** [comment]
The error is thrown because of:

```
[home.content] option 'presence' is required"
```
