### ISSUE TITLE
Laziness not lazy 

### ISSUE THREAD

**Issue by stephanebruckert** [offirgolan/ember-cp-validations#547]
Hi,

Quick question, 

```
export default {
  description: 'Email',
  type: 'email',
  lazy: true,
  validators: [
    validator('format'),
    validator('uniqueness', { // <-- custom validator, always called
      negate: true
    })
  ]
};
```

isn't this supposed to not run my `uniqueness` format validator when `format` doesn't validate?

I've also tried to move the `lazy: true` into the validator, still no luck:

```
validator('uniqueness', {
  negate: true,
  lazy: true
})
```

Thanks!

**Comment by offirgolan** [comment]
@stephanebruckert that's weird. Any chance you can recreate this in a twiddle?

**Comment by stephanebruckert** [comment]
I must be missing something? https://ember-twiddle.com/b16c0637affadf263b7f766b0541dffa?openFiles=controllers.application.js%2C

**Comment by leoeuclids** [comment]
Adding a format type seems to solve the issue.

`validator('format', { type: 'email' })`

**Comment by stephanebruckert** [comment]
It does solve the issue, thanks @leoeuclids! 

Still, the format validator itself works without specifying the type, which means we shouldn't have to specify it

**Comment by offirgolan** [comment]
@stephanebruckert apologies for such a delayed response! Are you still running into this issue?
