### ISSUE TITLE
Inverse of a validator?

### ISSUE THREAD

**Issue by tarponjargon** [offirgolan/ember-cp-validations#548]
I am using your username-available customer validator example (from embermap video) with e-mail address (as username) for account registration, and that works well.

I have a "forgot password" form where email is required. I want to check if the account exists before submitting.  I'm wondering, is there a way for me to invert the username-available validator (like perhaps a `computed.not` somewhere)?  Otherwise I'll need to create a username-exists custom validator that is the same code except with true/false logic reversed.

**Comment by offirgolan** [comment]
@tarponjargon unfortunately not. You can extract the common code and use it in both validators or you can have one extend the other.

**Comment by offirgolan** [comment]
Update:

I was thinking about this and I think a better solution would be just to pass your validator an option.

```
validator('username-exists', { inverse: true });
```

Then you can handle both cases depending on the option passed in and can then only have a single validator. 😄

**Comment by tarponjargon** [comment]
Ah! so maybe that in combination with something like?

	//username-exists
	validate(value) {
		return this.get('store').queryRecord('user', {
			email: value
		}).then(result => {
			if (result.get('email')) {
				if (get(options, 'inverse')) { // username-available logic
					return "Account already exists! Try logging in."
				} else {
					return true; //username-exists logic
				}		
			} else {
				if (get(options, 'inverse')) { // username-available logic
					return true;
				} else {
					return "No account exists for that e-mail!" //username-exists logic
				}	
			}
		})
	}
