### ISSUE TITLE
Dynamically disable validation for a form

### ISSUE THREAD

**Issue by erichonkanen** [offirgolan/ember-cp-validations#549]
### Environment

- Ember Version: 2.16.2
- Ember CLI Version: 2.16.2
- Ember CP Validations Version: 3.5.0

### Steps to Reproduce
I have the following in `app/validations/change-password.js`
```
import EmberObject, { computed, get, set, setProperties } from '@ember/object';
import {
    buildValidations,
    validator
} from 'ember-cp-validations';
import Mixin from '@ember/object/mixin';

const Validations = buildValidations({
    'passwordObj.current_password': [
        validator('presence', {
            disabled: computed.not('component.editPasswordMode'),
            presence: true
        })
    ],
...

export default Mixin.create(Validations);
```
The issue I'm having is that I need this fields validations to be disabled/turned off if a property on the parent component is set. In other words, if the user did not click "change password" button on our parent form edit, we want to exclude those fields/validations, likewise include them if they did choose to edit the password.

Currently this doesn't work or I can't seem to get it to work so I'm wondering if I'm missing something or it's not possible? I should say that it needs to be bound to the value so if a user toggles the key, the "disabled" state adjusts with it.

Here is how I hacked the component into the "model" on the parent component:
```
     set(this. {
                    passwordObj: {
                        component: this,
                        current_password: get(user, 'current_password'),
                        password: get(user, 'password'),
                        confirm_password: get(user, 'confirm_password')
                    },
```

**Comment by offirgolan** [comment]
I'm not sure what `component` is in this context:

```
disabled: computed.not('component.editPasswordMode')
```

But it should either be `model.editPasswordMode` or `model.component.editPasswordMode`

**Comment by erichonkanen** [comment]
got it working thanks!
