### ISSUE TITLE
conditional validator based on context

### ISSUE THREAD

**Issue by tarponjargon** [offirgolan/ember-cp-validations#551]
Not really an issue, just a question.  Tried on [stackoverflow](https://stackoverflow.com/questions/47489829/ember-cp-validations-conditional-validator) but didn't get any takers...Let me know if there is a better venue for questions.

Is it possible to add a validator based on context?  Like, if the user is authenticated (with ember-simple-auth) or my route name?

The problem I am trying to solve...

I have a basic `email` model that has typical validations on the model itself. When that model is being used in the context of a user account, I want an additional validator to be active (a `username-exists` validator, used to tell if they are trying to update their email address to one that already exists on another account - as email is used as the login).

My email model:

```
import DS from 'ember-data';
import { validator, buildValidations } from 'ember-cp-validations';

const { attr } = DS;

const Validations = buildValidations({
    email: {
        validators: [
            validator('presence', { presence: true, description: 'E-Mail'}),
            validator('format', {
                type: 'email'
            }),
            validator('length', {
                max: 200,
            })
        ]
    },
});

export default DS.Model.extend(Validations, {
    email: attr('string'),
    optin: attr('boolean', { defaultValue: false })
});
```

I already have a `username-exists` custom validator. I just can't figure out how to add that validation _conditionally_.

The simplest solution would be adding the validated with a disabled option that keeps it disabled unless a condition is met.

```
validator('username-available', {
    debounce: 300,
    disabled: computed.bool(what is the dependent key??)
})   
```

But I have no idea what the dependent key would be. I don't think the route name or ESA session service are available in the model definition or where the validators are defined (if on the component itself). I'd probably have to look at a lower level - like at the raw cookies.

I think I am probably missing something obvious ;)

**Comment by offirgolan** [comment]
I would go about it a different way. Your validator has container access which means you can inject the session service into it. 

You can add a custom option like `disabledIfAuthenticated`.

```js
validator('username-available', {
    debounce: 300,
    disabledIfAuthenticated: true
});
```

And then you can refer to it via your validator as such:

```js
// validators/username-available.js

BaseValidator.extend({
  session: inject.service(),

  validate(value, options, model, attribute) {
    if (this.get('session.isAuthenticated') && options.get('disabledIfAuthenticated')) {
      return true;  
    }

    // ...
  }
});
```

**Comment by tarponjargon** [comment]
Perfect- thank you so much!

**Comment by offirgolan** [comment]
Np! 😸
