### ISSUE TITLE
Validate model that doesn't have fields

### ISSUE THREAD

**Issue by ankitmadhwani24** [offirgolan/ember-cp-validations#552]
### Environment

- Ember Version: 
- Ember CLI Version: 2.16
- Ember CP Validations Version: > 3.0

Hi

i am using cp validation for validating my model 
Right now i have 

const validations = buildValidations({

 name1: validator('presence', {
   description: 'name',
   presence: true,
   ignoreBlank: true,
   message: 'name cannot be left blank'
 }),
name2: validator('presence', {
description: 'name',
presence: true,
ignoreBlank: true,
message: 'name cannot be left blank'
}),
})

and my model is having 
export default Model.extend(validations , {
 name1: attr('number'),
});

I have only name1 in my model but cp validation not validating my model

**Comment by offirgolan** [comment]
@ankitmadhwani24 can you recreate your issue in an Ember Twiddle?

**Comment by ankitmadhwani24** [comment]
HI
please check
**https://ember-twiddle.com/741952a5d8f7558e41560f49cfafad68?openFiles=templates.application.hbs%2C**

i have only one attribute in my model but and i have 2 fields in 

**const validation**

and in my {{v-get helper}} i m getting false 

please tell what i m doing wrong

**Comment by rinoldsimon** [comment]
@ankitmadhwani24 you should write validation in controller or component for fields which don't exist in the Ember model. Working [twiddle](https://ember-twiddle.com/f511289a1e6131a5b2bfe4514cb1c2ca). Kindly check it and let me know.

and you should use **model=this** for **name2** field in your hbs

**Comment by ankitmadhwani24** [comment]
@rinoldsimon Thanks Its work for me 

Thanks a lot
