### ISSUE TITLE
Further examples for manual validation

### ISSUE THREAD

**Issue by timiyay** [offirgolan/ember-cp-validations#56]
I'm exploring `ember-cp-validations` for form validation in my Ember app. Our use case is similar to your demo:

- no validation message to be shown at first
- only validate each field after `focus-out`

I'm able to use the methods like `isValid` and `isDirty` to partially solve the problem, but these are bound  values, and show up as soon as the user starts typing in a field.

How do I prevent the validations being run, until I do something like `validateSync()`?

Ideally, I'd love to see the code for the demo app, and have it added to the docs as a real-world example.

Thanks for all your work on the project.

**Comment by offirgolan** [comment]
You can check out the code for the demo app [here](https://github.com/offirgolan/ember-cp-validations/tree/master/tests/dummy/app). I would take a look at the [validated-input component](https://github.com/offirgolan/ember-cp-validations/blob/master/tests/dummy/app/components/validated-input.js) which solves most of your use-cases.

**Comment by timiyay** [comment]
@offirgolan Brillant. Thanks for the info. Sorry to open a GH issue for this - I trawled the codebase base but didn't recognise the demo app code when I saw it.

**Comment by offirgolan** [comment]
No worries! Thanks for reaching out :smile_cat:
