### ISSUE TITLE
Add disabled option to belongs-to

### ISSUE THREAD

**Issue by fran-worley** [offirgolan/ember-cp-validations#565]
Say you have a case where a contact has an optional address toggled by a boolean property `hasAddress` it would be super cool to be able to disable the belongs-to error link for this record entirely.

I know there are other ways of handling this, but it struck me that a disabled option would be quite a neat solution here, and in keeping with the other validations options.

**Comment by offirgolan** [comment]
@fran-worley this is [already possible](http://offirgolan.github.io/ember-cp-validations/docs/modules/Common%20Options.html#disabled).

**Comment by fran-worley** [comment]
You sir have just made my morning! (why oh why did I forget to put `model.property` in my computed when I tried this earlier??)!
