### ISSUE TITLE
[Question] Using a debounce for a promise-based validation

### ISSUE THREAD

**Issue by dasnixon** [offirgolan/ember-cp-validations#57]
I have a validation that makes a `GET` request to my server to check if a resource already exists in the system. What is the best approach for a `debounce`? I don't want to make a zillion requests to my API. I tried a few things to no avail. Maybe the debounce logic should just live outside the scope of the validation? To me it feels like I should handle this where the actual request occurs. Hopefully someone can point me in the right direction, thanks!

````
import Ember from 'ember';
import BaseValidator from 'ember-cp-validations/validators/base';

const { isPresent } = Ember;

export default BaseValidator.extend({
  validate(value, options, _model, attribute) {
    const adapter = this.container.lookup('adapter:unique-resource');
    return adapter.checkUniqueness(attribute, value, options.endpoint).then(function () {
      return true;
    }).catch(() => {
      const errorMessage = isPresent(options.message) ? options.message : this._defaultMessage(attribute);
      return this.createErrorMessage('invalid', value, { message: errorMessage });
    });
  },

  _defaultMessage(attribute) {
    return `${attribute} has already been taken`;
  }
});
````

**Comment by offirgolan** [comment]
If your attribute is bound to an input I would put my debounce on the input value binding. 

Lets say my validated attribute is `foo`, then instead of binding my input to `foo`, you can bind to temporary property and debounce that. 

```handlebars
{{input value=rawFooValue}}
```

```javascript
export default Ember.Component.extend({
  rawFooValue: null,

  onFooChange: Ember.observer('rawFooValue', function() {
    Ember.run.debounce(this, this._setFoo, 500, false);
  }),

  _setFoo() {
    this.set('foo', this.get('rawFooValue')); // This will now trigger your validation rules
  }
})
```

Hope that helps! You can take a look [here](https://github.com/offirgolan/ember-cp-validations/blob/master/tests/dummy/app/components/validated-input.js#L39) for a more detailed example

**Comment by dasnixon** [comment]
Makes sense, thanks for the feedback. Thought maybe there was some more elegant solution :smile_cat:

**Comment by offirgolan** [comment]
Hmmm it might be useful to have a debounce option in the validator options. Ill explore this more :smile:

**Comment by dasnixon** [comment]
Sweet, I might play around a little, I'll let you know what I find. I'll re-open this since it _could_ be useful

**Comment by dasnixon** [comment]
@offirgolan thanks for implementing!

**Comment by offirgolan** [comment]
No problem :smile_cat: Thanks for the idea!
