### ISSUE TITLE
DEPRECATION: ember-cli-babel 5.x has been deprecated

### ISSUE THREAD

**Issue by AMS777** [offirgolan/ember-cp-validations#575]
After installing `ember-cp-validations` in an Ember.js 3.0 project, following error appears when running the server:

> DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6.0

### Environment

- Ember Version: 3.0.0
- Ember CLI Version: 3.0.0
- Ember CP Validations Version: 3.5.2

### Steps to Reproduce
In the Ember project install `ember-cp-validations`:
```
ember install ember-cp-validations
```
After that run an Ember command like:
```
ember -v
```
or:
```
ember s
```

**Comment by maxwondercorn** [comment]
This also affects 2.17 - 2.18 if you're using yarn.  There seems to be a mismatch in versions.  

The package.json in the repro has a dependency on ember-require-module: 0.2.0 which has the updated ember-cli-babel.  But the download from NPM still lists ember-require-module: 0.1.2 which has the outdated version of ember-cli-babel.

Interesting that the package.json in the repro is still version 3.5.1 while the npm version is 3.5.2.  A mixup in the commit/release process, I'd guess.

**Comment by offirgolan** [comment]
v3.5.2 was released from the 3.x branch since master is going to soon released as `4.0.0-beta.0` which upgrades a bunch of dependencies and removes legacy support for older ember version.

**Comment by offirgolan** [comment]
Resolved by #576. Released in `v4.0.0-beta.0`.

**Comment by AMS777** [comment]
Installed and tested. No more error messages. Everything seems to work correctly.

Thank you, @offirgolan

**Comment by offirgolan** [comment]
Sweet! Thanks for testing @AMS777 😸
