### ISSUE TITLE
Debounced Validations

### ISSUE THREAD

**Issue by offirgolan** [offirgolan/ember-cp-validations#58]
In regards to #57, it might be useful from a UX perspective to have an option to debounce validations. This would also be needed for custom ajax dependent validations. This will definitely need to be explored a little more but a simple definition can look something like this: 

```javascript
var Validations = buildValidations({
  foot: validator('custom-ajax', {
    debounce: 500
  })
});
```

@blimmer @stefanpenner any thoughts?

**Comment by jamesdixon** [comment]
This would be great. :+1:

**Comment by stefanpenner** [comment]
is it debouncing we want or throttle?

**Comment by stefanpenner** [comment]
It seems like we actually want tighter integration with various events, focusOut etc. Having a bunch of async validations on a form the user can fill out quickly results in this strange laziness. 

I suspect some combination of better event hooks, and debounce is what we would like to see. (maybe this doesn't preclude standalone debounce)

**Comment by ajgordo** [comment]
I'm curious if there is any kind of workaround for forcing validation on focusOut right now. Using the validated-input component as an reference I want to add to it a validate check when it loses focus. I see you can do that on the model, but I want to see if you can do it within the component itself?

**Comment by stefanpenner** [comment]
> I'm curious if there is any kind of workaround for forcing validation on focusOut right now.

I would love for this to be easy. I think @offirgolan and me have chatted about it a few times.

**Comment by jamesdixon** [comment]
@ajgordo not sure if this helps as I'm using [ember-paper](https://github.com/miguelcobain/ember-paper) for my component library, but I modified `validated-input` like so to get validation working on focusOut:

```javascript
// validated-input.js
import Ember from 'ember';

const {
  computed,
  defineProperty,
  run
} = Ember;

export default Ember.Component.extend({
  model: null,
  value: null,
  rawInputValue: null,
  type: 'text',
  textarea: false,
  valuePath: '',
  placeholder: '',
  label: '',
  attributeValidation: null,
  showError: false,

  isValid: computed.oneWay('attributeValidation.isValid'),

  isInvalid: computed.oneWay('attributeValidation.isInvalid'),

  didInitAttrs() {
    this._super(...arguments);
    const valuePath = this.get('valuePath');
    defineProperty(this, 'attributeValidation', computed.oneWay(`model.validations.attrs.${valuePath}`));
    defineProperty(this, 'value', computed.alias(`model.${valuePath}`));
  },

  actions: {

    validate() {
      this.set('showError', this.get('isInvalid'));
    }
  }
});
```
```handlebars
// validated-input.hbs

{{paper-input
  textarea=textarea
  type=type
  label=label
  placeholder=placeholder
  value=value
  focus-out=(action 'validate')
}}

<div class="input-error">
  {{#if showError}}
    <div class="error">
      {{v-get model valuePath 'message'}}
    </div>
  {{/if}}
</div>
```

**Comment by offirgolan** [comment]
I think the solution provided by @jamesdixon is pretty solid. I honestly dont think that this library has any business in providing hooks for `focusOut` `focusIn` and so on since they are component only based events. In the context of this addon, all we have access to when validating is the object at hand, anything beyond that should be a separate addon. I think that the `validated-input` component is a good start and can be used to create a form library around this validation library.

Nonetheless, I will keep working on features to support various UX requirements (if they are in the context of this addon) :smile_cat: 

cc @blimmer

**Comment by ajgordo** [comment]
Thanks for the info. My circumstance was a little different, but I was able to get what I needed thanks to the information provided.

**Comment by offirgolan** [comment]
This is now in master. Will release it in a couple days.

**Comment by offirgolan** [comment]
Tagged and released with `v2.2.0`

**Comment by jamesdixon** [comment]
:+1:

**Comment by dodeja** [comment]
@offirgolan I think the validated-input example is good, especially after the updates. Don't necessarily think it needs to a component and part of this library but would be good to include in the docs.
