### ISSUE TITLE
Custom Validator - Errors & Warnings

### ISSUE THREAD

**Issue by mschwenk** [offirgolan/ember-cp-validations#581]
### Environment

- Ember Version: 2.14.1
- Ember CLI Version: 2.11.0
- Ember CP Validations Version: 3.5.1

### Steps to Reproduce/My Issue

I wrote a custom validator for our validation messages coming from the server. It works well.
I get up to n messages and combine them to one string. Unfortunately not all messages I get are errors that should prevent my model from saving. Some of them are simple warnings. 

I need to separate them to handle them right in ember. Is there a way to set the `isWarning` property according to one boolean value I get from the messages of the server? 

Another solution I could think of is to write two custom validations to handle errors and warnings separately. But this would mean mostly duplicate code and doubled requests. 

My code currently looks like this: 

```
const ValidateMds = BaseValidator.extend({
  api: Ember.inject.service(),

  validate(value, options , model) {
    let mds = options.mds;
    let message = "";

    if(Ember.isPresent(value) && !Ember.isEmpty(mds)) {
        return this.get("api").request('validations/product/validate', JSON.stringify(model)).then((validations) => {
          let mdsMessages = validations.validationMessages;
          for (let i=0; i < mdsMessages.length; i++) {
            let code = mdsMessages[i].code;
            let preventSave = mdsMessages[i].preventSave;
            if (mds.indexOf(code) > -1) {
              options.isWarning = !preventSave;
              let msg = mdsMessages[i].msg;
              message += '<span class="mdsMsg" data-mds="' + code + '">' + msg + '</span>';
            }
          }
          return !Ember.isEmpty(message) ? message : true;
        });
      }
    } else {
      return true;
    }
});
```

I would appreciate any help :) 
thx Mel

**Comment by panthony** [comment]
Same situation here, I have a custom validator which uses an API endpoint and this endpoint can return either an error or a warning.

I'd rather not duplicate the logic and do the call twice so it would be nice to be able to (re)-specify the severity after the validation.

**Comment by panthony** [comment]
@mschwenk After digging out how `isWarning` is handled it turns out you can handle this use case. Not sure If it introduce a sneaky bug somewhere but it looks like ok.

Here's my validator:

```js
import BaseValidator from 'ember-cp-validations/validators/base';

export default BaseValidator.extend({

  async validate(value, options, model, attribute) {
    const response = await model.validateAttribute(attribute, value);

    if (response.valid) {
      return true;
    }

    const isWarning = response.severity === 'warning';

    return {
      [isWarning ? 'warningMessage' : 'message']: response.message,
      isValid: isWarning
    };
  }

});
```

**Comment by offirgolan** [comment]
> All I need is a way to set the messages to the right array - warning or error.

I'm not sure what you mean by this. Can you give me some more context on what exactly you're trying to achieve?

**Comment by mschwenk** [comment]
@offirgolan  I think it was all said in my original post on April 9th. But I try to sum up my issue:

I have a custom validator - some of my validation gets done on server side. I get a bunch of messages back, all with a property `preventSave` set. `preventSave` can either be true (so it is an actual error) or false (then it is a warning). But currently all my messages get bubbled up as errors. 

I updated my code above as followed: 

```
return this.get("api").request('validations/product/validate', JSON.stringify(queryableModel)).then((validations) => {
          //let product = validations.product;
          let mdsMessages = validations.validationMessages;
          for (let i=0; i < mdsMessages.length; i++) {
            let code = mdsMessages[i].code;
            if (mds.indexOf(code) > -1) {
              let preventSave = mdsMessages[i].preventSave;
              let msg = mdsMessages[i].msg;
              let validationMessage = msg;

              // enhance options with isWarning state
              options.isWarning = !preventSave;

              return validationMessage;
            }
          }
          return true;
        });
```

I enhance the options with `isWarning` dynamically. But this does not seem to work, as I still get those messages in the errorMessages array.

**So, is there a way to update the options dynamically in a custom validator?** All I figured out is that `isWarning` can be set on init. But I don't want to run this custom validator twice in case some of the messages might be warnings.

**Comment by panthony** [comment]
@mschwenk What was wrong with my [solution](https://github.com/offirgolan/ember-cp-validations/issues/581#issuecomment-391636533)?

Didn't it work?

**Comment by mschwenk** [comment]
@panthony sorry, no, unfortunately not. I am using an older version of cp-validations. What is your environment?

**Comment by mschwenk** [comment]
@offirgolan do you have any idea on this?

**Comment by offirgolan** [comment]
The solution @panthony provided should work just fine. It would have been possible from the same release as the warning messages.

**Comment by mschwenk** [comment]
@offirgolan  thx. then I should give it another try.

**Comment by mschwenk** [comment]
Thx for your support here :) @offirgolan  
I figured it out with the solution @panthony provided

I'm closing this issue as it is resolved ;)
