### ISSUE TITLE
How to validate date is a real date when format is valid?

### ISSUE THREAD

**Issue by GCheung55** [offirgolan/ember-cp-validations#610]
With the `date` validator, how can I return a message that the date is invalid but the format is valid?

For example, with a date string '2018-02-30', the following validator would display a `wrongDateFormat` error message instead of `date` error message.

```javascript
{
    date: validator('date', {
        format: 'YYYY-MM-DD'
    })
}
```

**Comment by offirgolan** [comment]
Fixed and released in `v4.0.0-beta.3`.
