### ISSUE TITLE
Bump ember-validations in the 3.x Series?

### ISSUE THREAD

**Issue by jherdman** [offirgolan/ember-cp-validations#611]
### Environment

- Ember Version: 3.4
- Ember CLI Version: 3.4
- Ember CP Validations Version: 3.5.4

### Steps to Reproduce

Install the above, witness the deprecation warning for Babel.

### Request

Would you be amenable to a PR upgrading ember-validations in the 3.x branch to bump ember-validations? I'd love to resolve the Babel 5 deprecation warning whilst version 4 is being worked out.

**Comment by jherdman** [comment]
I'd like to bump this issue. This has been holding us back on updating Ember versions for quite some time.

**Comment by offirgolan** [comment]
@jherdman a PR is always welcome. I've been using `v4.0.0-beta` in production for a while now and its stable. You're welcome to switch over to that as well instead of trying to fix the 3.x branch.

**Comment by jherdman** [comment]
We're using the 4.0-beta now and all seems to be well.

@offirgolan my apologies, I wasn't a good open source citizen on this one. I'll do better next time.

**Comment by offirgolan** [comment]
No worries at all 😄
