### ISSUE TITLE
DEPRECATION: Using `Ember.NAME_KEY` is deprecated

### ISSUE THREAD

**Issue by rwwagner90** [offirgolan/ember-cp-validations#620]
```
DEPRECATION: Using `Ember.NAME_KEY` is deprecated, override `.toString` instead [deprecation id: ember-name-key-usage]
```

### Environment

- Ember Version: 3.8.0-beta.1
- Ember CLI Version: 3.8.0-beta.1
- Ember CP Validations Version: 4.0.0-beta.5

### Steps to Reproduce

Just use with an Ember app on 3.8

**Comment by offirgolan** [comment]
Fixed in `v4.0.0-beta.6`
