### ISSUE TITLE
Ember.NAME_KEY is deprecated

### ISSUE THREAD

**Issue by urbany** [offirgolan/ember-cp-validations#626]
Hi, in the latest ember release (3.8.0) NAME_KEY was deprecated:
```
DEPRECATION: Using `Ember.NAME_KEY` is deprecated, override `.toString` instead [deprecation id: ember-name-key-usage]
```

Currently being used here: https://github.com/offirgolan/ember-cp-validations/blob/69c31e689416cb79b86191968a60b06a89b9ba99/addon/validations/factory.js#L146

**Comment by mabab** [comment]
Hi, please fix the deprecated in stable version.
