### ISSUE TITLE
I can't install ember-cp-validations with i18n

### ISSUE THREAD

**Issue by villander** [offirgolan/ember-cp-validations#627]
### Environment

- Ember Version: 3.8.0
- Ember CLI Version: 3.8.0
- Ember CP Validations Version: v4.0.0-beta.6

### Steps to Reproduce

I can't install ember-cp-validations =/

```
web_app git:(PAY-176/refactor-validation-system) ember install ember-cp-validations
ember-i18n has been deprecated in favor of ember-intl
Invalid Version: undefined


Stack Trace and Error Report: /var/folders/0v/jpdg1flj3qscvbvt728pgt8c0000gn/T/error.dump.b35eaa0f0b58ecb1738dae42d9c245d2.log
```

**Comment by villander** [comment]
cc: @offirgolan

**Comment by offirgolan** [comment]
Im not sure why the install is failing. This package has no dependency on `ember-i18n` or `ember-intl`. Can you provide a reproduction of this in a dummy app?

**Comment by villander** [comment]
this was a bug with npm install in ember-cli 2.18.0
