### ISSUE TITLE
`v-get` AST transform is preventing `ember-cli-babel` from parallelizing

### ISSUE THREAD

**Issue by Turbo87** [offirgolan/ember-cp-validations#628]
`ember-cli-babel` and `ember-cli-htmlbars-inline-precompile` are able to parallelize their workload using `workerpool`. For that the plugin configurations need to be serializable and addons that register HTMLBars AST plugins need to slightly change the code to enable it.

One implementation example is https://github.com/rwjblue/ember-angle-bracket-invocation-polyfill/pull/45. Once we do the same thing for this addon here parallelizing should work fine.

```
DEBUG=ember-cli-htmlbars-inline-precompile* DEBUG_LEVEL=debug ember b
```
☝️ will enable debug output and show whether the transform was parallelizable or not

/cc @rwjblue

**Comment by olleolleolle** [comment]
@Turbo87 Is this Issue now closable?

**Comment by Turbo87** [comment]
yeah, sorry, #629 has fixed that AFAICT
