### ISSUE TITLE
Broken with Ember 3.10.0

### ISSUE THREAD

**Issue by stopfstedt** [offirgolan/ember-cp-validations#640]
### Environment

- Ember Version: 3.10.0
- Ember CLI Version: 3.10.0
- Ember CP Validations Version: 4.0.0-beta.8

### Steps to Reproduce

```
npx ember-cli-update --to=3.10.0
npm install
npm test
```

Fails with error message: `EmberObject.create no longer supports defining computed properties. Define computed properties using extend() or reopen() `

refs #635

**Comment by patocallaghan** [comment]
FYI this issue has started happening again with the Ember 3.13 beta but I have a fix here https://github.com/offirgolan/ember-cp-validations/pull/653
