### ISSUE TITLE
generated mocha tests include chai, despite our app not using chai

### ISSUE THREAD

**Issue by efx** [offirgolan/ember-cp-validations#647]
### Environment

- Ember CP Validations Version: (symlinked master as of 4115834)

### Steps to Reproduce

1. `ember g validator-test my-validator`
2. In a project that uses `ember-mocha`, but not `chai`, it includes chai because of the [blueprint](https://github.com/offirgolan/ember-cp-validations/blob/master/blueprints/validator-test/mocha-files/tests/unit/validators/__name__-test.js#L1).

It would be nice to introspect the project dependencies if it has chai. I wonder how ember-mocha does this right now? Couldn't find the example blueprints in ember-cli from a quick check.

**Comment by Turbo87** [comment]
>  I wonder how ember-mocha does this right now?

ember-mocha itself does not have any testing blueprints, but ember and ember-data both also assume that if you use mocha then you will also use chai.

**Comment by efx** [comment]
I'll close this then. I had forgotten about that default behavior. It seems best to address that separately as a feature request to ember-mocha, rather than here.
