### ISSUE TITLE
[ember-source 3.13] using a computed property in the `before` key for a validator throws error

### ISSUE THREAD

**Issue by efx** [offirgolan/ember-cp-validations#661]
### Environment

- Ember Version: 3.13
- Ember CLI Version: ~3.12.0
- Ember CP Validations Version: 4.0.0-beta.9

### Steps to Reproduce
1. clone the following repository and run `yarn test`: https://github.com/efx/cp-validations-test

Specifically using the [`alias` computed within a validation object](https://github.com/efx/cp-validations-test/blob/master/app/models/user.js#L9) breaks with ember-source. The ember-source assertion is [in core_object.js](https://github.com/emberjs/ember.js/blame/v3.13.0/packages/%40ember/-internals/runtime/lib/system/core_object.js#L86).

The failing logic occurs in
https://github.com/offirgolan/ember-cp-validations/blob/2e901724390172d3b9584aec69696e2f8e28fc29/addon/-private/options.js#L26

If you pause execution it seems to happen since `options.before` is a `COMPUTED_DECORATOR`?
<img width="1240" alt="Screen Shot 2019-09-20 at 14 07 39" src="https://user-images.githubusercontent.com/472721/65348868-24d24d80-dbb0-11e9-91c7-7aa30a888c13.png">

**Comment by patocallaghan** [comment]
@efx I believe this currently open PR will fix the issue https://github.com/offirgolan/ember-cp-validations/pull/653

**Comment by efx** [comment]
@patocallaghan thank you for pointing that out and fixing the issue! I'll test that PR in our application today.

**Comment by efx** [comment]
Looks like @GavinJoyce has also started to fix for 3.13 in #662

**Comment by st-h** [comment]
Just ran into this and it seems it also occurs when the validation rule includes the `disabled` option. At least, when I remove that, the error no longer occurs.

**Comment by efx** [comment]
Verified that https://github.com/offirgolan/ember-cp-validations/tree/v4.0.0-beta.10 fixes this issue. Probably via #668
