### ISSUE TITLE
V-GET is not a helper error

### ISSUE THREAD

**Issue by chrisfernandes102** [offirgolan/ember-cp-validations#676]
### Environment

- Ember Version: 3.0
- Ember CLI Version: 3.17.0
- Ember CP Validations Version: 3.5.2

### Steps to Reproduce
Have an ember 3.0 application that has ember-cp-validations installed, I wrote a an ember addon that also has cp-validations installed. My application consumes my custom addon, v-get seems to work in my ember application but not in my ember addon. Any idea of what this could be?

@offirgolan

**Comment by chrisfernandes102** [comment]
@rwjblue

**Comment by jonchay** [comment]
Did you resolve this? I'm experiencing the same issue as well with glimmer components.

**Comment by chrisfernandes102** [comment]
@jonchay Hey Jonathan, I did - putting `ember-cp-validations` in the `dependencies` seemed to fix the issue for me.

**Comment by jonchay** [comment]
I dug in a little in this, looks like the error is caused by the registering `htmlbars-ast-plugin` for `v-get` but it does not apply to glimmer templates. Should we re-open this issue?
