### ISSUE TITLE
V-get helper doesn't work for the relationship

### ISSUE THREAD

**Issue by AmilKey** [offirgolan/ember-cp-validations#71]
V-get helper doesn't work for the relationship, for example http://offirgolan.github.io/ember-cp-validations/docs/validators/belongs-to/index.html

```
{{v-get model 'details.firstName' 'message'}}
{{v-get model 'details.lastName' 'message'}}
```

it returns nothing

**Comment by offirgolan** [comment]
Try
```hbs
{{v-get model.details 'firstName' 'message'}}
{{v-get model.details 'lastName' 'message'}}
```

**Comment by AmilKey** [comment]
@offirgolan yes, it's works
But why does it is not work for `{{v-get model valuePath 'message'}}` where `valuePath='details.lastName'` ?

**Comment by offirgolan** [comment]
Which version of Ember are you on?

**Comment by offirgolan** [comment]
This doesnt work for relationships indeed. The reason behind it is as follows

```hbs
{{v-get model 'firstName' 'message'}}
```

converts to `model.validations.attrs.firstName.message`

but if you have a relationship

```hbs
{{v-get model 'details.firstName' 'message'}}
```

that converts to `model.validations.attrs.details.firstName.message`

where really, it should be located in `model.validations.attrs.details.attrs.firstName.message`. The only solution is as I mentioned above (to have your model as model.details).

**Comment by AmilKey** [comment]
@offirgolan thanks for the explanation!

**Comment by offirgolan** [comment]
No problem! Glad to help :smile:

**Comment by stefanpenner** [comment]
might be a good idea for this to be called out in the docs (if not already)
