### ISSUE TITLE
number Validator - allowBlank/allowString and zero length value

### ISSUE THREAD

**Issue by pjmeadmtu** [offirgolan/ember-cp-validations#73]
I have a number validator that allows blanks and allows strings, but when there's a zero length value an error message displays.  It doesn't appear that it allows blanks.  Below is my validator with options:

```javascript

const blankGte0 = validator('number', {
  gte: 0,
  allowBlank: true,
  allowString: true,
  count() {
    return this.options.gte;
  }
});

```

**Comment by offirgolan** [comment]
What version are you on?

**Comment by pjmeadmtu** [comment]
I was using the previous v2.1.0.  Upgrading resolved this issue.
