### ISSUE TITLE
Support owners instead of container in Ember 2.3

### ISSUE THREAD

**Issue by offirgolan** [offirgolan/ember-cp-validations#74]
Reference: http://emberjs.com/blog/2015/11/16/ember-2-2-released.html#toc_introducing-owners-and-deprecating-containers

**Comment by rwjblue** [comment]
Other addon updates:

* https://github.com/emberjs/data/pull/3912
* https://github.com/ef4/liquid-fire/pull/388
* https://github.com/jamesarosen/ember-i18n/pull/336

ember-test-helpers updates included in 0.4.16 (from https://github.com/switchfly/ember-test-helpers/pull/118 and https://github.com/switchfly/ember-test-helpers/pull/119).

**Comment by offirgolan** [comment]
Awesome! Thanks for the addon and the starting point Rob!
