### ISSUE TITLE
Applying multiple separate regex validations possible?

### ISSUE THREAD

**Issue by rox163** [offirgolan/ember-cp-validations#75]
I have 2 different regex validation options available as utils for my password field. The user can use one or both validations in the model. In the example below we want to have special characters and numbers in the password. I am seeing weird behaviour when applying multiple regex like this - 
```
validationsPassword: [
		validator('presence', true),
		//problem combining regex checks
		validator('format', {
		    regex: /(?=.*[!@#$%\^&*)(+=._-])/g,
		    message: "Must contain special characters"
	        }),
		validator('format', {
		    regex: /\d/g,
		    message: "Must contain digits"
	        }),
		validator('length', {min: 6})
	]
```

When I put in 'a4$' for example in the field, after typing the '$', it shows the Must contain digits error. After entering another number, it says 'The field is invalid'
How can I apply these regex validators separately, on the same field?

**Comment by offirgolan** [comment]
Can you change your digits regex to `/(?=.*\d)/g`?

**Comment by rox163** [comment]
That seems to have fixed one issue! The Must Contain Digits error doesn't keep reappearing. 
After that however I just see The field is invalid. I should see something about the minimum length till I hit 6 chars, but no such luck.

**Comment by rox163** [comment]
Yes that has fixed it! Much appreciated!

**Comment by offirgolan** [comment]
No problem! Glad it worked :smile_cat:
