### ISSUE TITLE
Validation in components only

### ISSUE THREAD

**Issue by ajgordo** [offirgolan/ember-cp-validations#77]
Using the example code I am trying to create a component that does all it's own validation, but can't quite get it right.
In reality I am looking at creating some input boxes that have the validation baked in to them where they take a property and not a model.

Is this possible, and can you provide any kind of example on how this may work?

Thanks in advance.

**Comment by offirgolan** [comment]
Im not sure I follow exactly. Can you elaborate a little more?

**Comment by ajgordo** [comment]
Sorry, a bit of a poorly worded question.

I'm looking at extending validated-input and adding validation directly to it. 

So what I'm really looking to do is leave validated-input how it is, and create a new component that extends validated-input and has the validation baked in to it, rather than getting it from a model.

Does that make better sense?

**Comment by offirgolan** [comment]
This creates validation rules on the bound `value` property that the input is bound to. Not tested but it should work :relaxed:

```js
import Ember from 'ember';
import ValidateInput from './validated-input'
import { validator, buildValidations } from 'ember-cp-validations';

var Validations = buildValidations({
  value: [
    validator('presence', true),
    validator('length', {
      max: 15
    })
  ]
});

export default ValidateInput.extend(Validations, {
  init() {
    this._super(...arguments);
    defineProperty(this, 'attributeValidation', computed.oneWay(`validations.attrs.value`));
  }
});
```

**Comment by ajgordo** [comment]
I actually just came up with nearly the same approach too!
I'm now getting an error that the v-get helper is not found but am still looking in to why (if you happen to know off hand then please let me know :-))
Thanks for the help, it is starting to make sense now.

**Comment by offirgolan** [comment]
Thats because of [this](https://github.com/offirgolan/ember-cp-validations/blob/master/tests/dummy/app/templates/components/validated-input.hbs#L10)

You need to change that to `{{v-get this 'value' 'message'}}`

**Comment by ajgordo** [comment]
Yeah, not sure that's it.
In keeping with the theme of not changing my base so that it could be used in it's original state is someone wanted I have set model to this and valuePath to value, but the error continues.
It says the helper can't be found so it might be something else.

**Comment by offirgolan** [comment]
If you have `validated-input` component with its own template and now you `x-validated-input` component with the changes mentioned above, just create a `x-validated-input` template as well with the new v-get changes.

**Comment by ajgordo** [comment]
Actually the issue was that I needed to have ember-cp-validations as a dependency instead of as devDependency.
I'll all good now, thanks for the help

**Comment by offirgolan** [comment]
Ah gotcha. Glad to help :D

**Comment by rox163** [comment]
I am working on a similar issue. Trying to apply validation on a component instead of using a separate model. This helps isolate my form component. 
What would the hbs template look like for this example? I seem to have to pass 'model=this' as an attr in the component hbs.

**Comment by offirgolan** [comment]
If you have a form component with username, email and password and validations on that component itself then this should do the trick. 

```hbs
<form>
  {{validated-input model=this valuePath='username' placeholder='Username'}}
  {{validated-input type='password' model=this valuePath='password' placeholder='Password'}}
  {{validated-input model=this valuePath='email' placeholder='Email'}}
</form>
```
