### ISSUE TITLE
How to clear a validated field but not show the presence error message?

### ISSUE THREAD

**Issue by rox163** [offirgolan/ember-cp-validations#80]
I have to implement a Clear button for my form. So this would clear all the input fields and clear any validation error messages as well, specifically the presence one. I've implemented the validations on the field components, not as a separate model. How can I go about this?

**Comment by offirgolan** [comment]
@rox163 if you give me a couple hours, Ill hopefully be able to get this into the next build.

**Comment by rox163** [comment]
That would be awesome. Thanks!

**Comment by offirgolan** [comment]
Great! Im gonna close this issue in favor of #81.
