### ISSUE TITLE
Clear error messages

### ISSUE THREAD

**Issue by offirgolan** [offirgolan/ember-cp-validations#81]
In reference to #80 

There should be a way to clear errors with the ability to clear errors for a specific type(s).

- [x] `clearErrors()`
- [x] `clearErrors(['presence', 'length'])`

**Comment by offirgolan** [comment]
I was able to approach this in a much simpler way that doesnt require any change for this library. I created a demo app to illustrate this

https://github.com/offirgolan/clear-cp-demo

Feel free to clone, `npm i && bower i` then `ember s` to see it in action. The demo is based on the demo app of this library but with a reset functionality. To see the changes I made, you can look at [this commit](https://github.com/offirgolan/clear-cp-demo/commit/0b22306da87396c0a7388150862c04b182ae3d40)

**Comment by frank06** [comment]
I can't seem to find any connection between the "reset functionality" in the sample app (which overrides a component and is pretty contrived using `didValidate`) and why `clearErrors` or similar have not been implemented.

In a component I have a property called `current` which backs a form. It is a fragment, created via `this.store.createFragment`. When `current` is saved, it's sent up via an action. Until here validations work perfectly well. Then, `current` is then reset to a brand-new fragment.  When that happens all blank fields now show validation errors (presence).

I need a way to tell `ember-cp-validations` that the model/fragment is a new, untouched one. That it should not attempt to validate until the user tries to make a selection/change. So, how can I do that? Thanks!

**Comment by escobera** [comment]
I'm needing this as well. @offirgolan What is the current way to achieve this behaviour?
