### ISSUE TITLE
Validation without messages

### ISSUE THREAD

**Issue by chadian** [offirgolan/ember-cp-validations#84]
Is it possible to have validations done without a message being included? In this case the messages array would not contain a value for the invalid property.

**Comment by offirgolan** [comment]
You should be able to do 

```js
validator('length', { min: 1, message: '' });
```

**Comment by chadian** [comment]
I think this returns the default message, but I will have to confirm.

**Comment by offirgolan** [comment]
Any luck?

**Comment by offirgolan** [comment]
Just tried this myself, you would have to pass a string with a space

`validator('length', { min: 1, message: ' ' });`
