### ISSUE TITLE
checking an arbitrary (Ember.)Object while in a test

### ISSUE THREAD

**Issue by lindem** [offirgolan/ember-cp-validations#85]
I am trying to do some custom validation for objects pulled in while the test environment runs (ember-qunit). It's built like this: 

````javascript
module('test arbitrary object', {
  this.application = startApp();
  this.container = this.application.__container__;
});

test('it works', function(assert) {
  // make a validation mixin
  const Validations = buildValidations({
    a: [validator('presence', true)]
  });
  /* theObject usually comes from somewhere else, this is just for illustration */
  const theObject = Ember.Object.extend(Validations, {
    a: 5
  }).create();
  // validate, check, whatever
});
````

I still get  `<(unknown mixin):ember230> is missing a container.` and don't know how to properly pass in the container in this case (but I do have one, it's in `this.container` in the test function scope). Is it at all possible?

**Comment by offirgolan** [comment]
When you create your `theObject`, you're gonna have to pass in the container as well.

```js
test('it works', function(assert) {
  // ...
  const theObject = Ember.Object.extend(Validations, {
    a: 5,
    container: this.container
  }).create();
  // ...
});
```

Hope that helps :smile_cat:

**Comment by lindem** [comment]
Thanks for clearing that up. Maybe the documentation could be even clearer in where this must be passed in (I know it's in there, but somehow, I didn't get the idea). 

Also: What if the arbitrary object had a property named 'container' which was to be validated?

**Comment by lindem** [comment]
Also, I discovered that my beforeEach somehow didn't do what I expected it to do; a working minimal example is now 

````javascript
test('it works', function(assert) {
  const container = startApp().__container__;
  const Validations = buildValidations({
    a: [validator('presence', true)]
  });
  const theObject = Ember.Object.extend(Validations, {
    a: 5,
    container
  }).create();
  const {validations} = theObject.validateSync();
  assert.strictEqual(validations.get('isValid'), true);
});
````

**Comment by offirgolan** [comment]
A workaround for all this container setup is to just use `moduleFor` from `ember-qunit`

```js
import { moduleFor, test } from 'ember-qunit';

moduleFor('foo', 'Integration | Object | theObject', {
  integration: true,
});

test('it works', function(assert) {
  const container = this.get('container');
  const Validations = buildValidations({
    a: [validator('presence', true)]
  });
  const theObject = Ember.Object.extend(Validations, {
    a: 5,
    container
  }).create();
  const {validations} = theObject.validateSync();
  assert.strictEqual(validations.get('isValid'), true);
});
```

In this case, `foo` doesnt actually exist, but the container is setup for you so there is no need to do much prep.
