### ISSUE TITLE
validators of statically created objects can't access custom Messages object  

### ISSUE THREAD

**Issue by ramybenaroya** [offirgolan/ember-cp-validations#86]
In validators of statically created objects `this.errorMessages` points to the default `ember-cp-validations/validators/messages` instead of `app/validators/messages`

For example:
```javascript
// app/validators/messages.js
export default Messages.extend({
  example: "example error message"
});
```

```javascript
// models/user.js
var Validations = buildValidations({
  username: [
     validator(function(){
        return this.errorMessages.getMessageFor('example', {});
     })
  ]
});
export default Ember.Object.extend(Validations, {
  username: null
});
```

```javascript
// routes/index.js
import User from '../models/user';
export default Ember.Route.extend({
  model() {
    var options = { username: 'John' };
    Ember.setOwner(options, Ember.getOwner(this));
    return User.create(options)
  }
});
```

```hbs
{{!-- /app/templates/index.hbs --}}
{{v-get model 'username' 'message'}}
```

The output will be `"undefined is invalid"` instead of `"example error message"`.   
This is because the default message type is `invalid`.

**Comment by offirgolan** [comment]
Ah I know what the issue is. Ill open a PR with the fix in a little bit. Thanks for pointing this issue out!

**Comment by offirgolan** [comment]
Waiting on rwjblue/ember-getowner-polyfill#1 before this can be resolved.

**Comment by offirgolan** [comment]
@ramybenaroya please upgrade to `v2.1.4`. Should solve this problem :smile_cat:

**Comment by ramybenaroya** [comment]
@offirgolan Thanks for all your hard work and for this great addon!

**Comment by offirgolan** [comment]
Np :smiley_cat: Feel free to reach out if any other issues come up!
