### ISSUE TITLE
Default Messages Not Found

### ISSUE THREAD

**Issue by jherdman** [offirgolan/ember-cp-validations#87]
I'm installing in an Ember 2.2 application with a simple validations mixin:

```javascript
// app/mixins/my-validations.js
import { validator, buildValidations } from 'ember-cp-validations';
export default buildValidations({
  value: validator('presence', { presence: true }, dependentKeys: ['someOtherProp'])
});

// app/models/my-model.js
import Validations from 'student-app/mixins/activity-element-validations';

export default DS.Model.extend(Validations. {
  value: computed('dependentKey', function() { // blah blah blah
```

The following error is displayed when running my test suite: "Cannot read property 'create' of undefined", which points to this line: https://github.com/offirgolan/ember-cp-validations/blob/44c8595ec4debfcfa88694d8f75980e8631a059c/addon/validators/base.js#L63

The value of `errorMessages` is undefined at this point. I've followed in the install instructions to the letter. Hardcoding a string message does not work either.

**Comment by jherdman** [comment]
Sample app https://github.com/jherdman/ecp-validations-87

**Comment by offirgolan** [comment]
I believe this is a duplicate of #86. Should be fixed within the next day or two :smile:

**Comment by jherdman** [comment]
That's awesome! Can't wait to try it out.

**Comment by offirgolan** [comment]
@jherdman please upgrade to `v2.1.4`. Should solve this problem :smile_cat:

**Comment by jherdman** [comment]
Worked like a charm! Many thanks :cake:
