### ISSUE TITLE
Validating Nested Properties

### ISSUE THREAD

**Issue by jamesdixon** [offirgolan/ember-cp-validations#91]
Hi,

Great library!

Is it possible to validate nested properties of an object when those properties aren't defined explicitly on the model?

For example, I have a field that returns a JSON object for `address` that contains `street`, `city`, `state` and `zipcode` properties. I've attempted to build validations for each of those properties, but no luck. I've also tried creating a computed alias in the model to reference those specific properties, but again, no luck. Any suggestion on how I might accomplish this?

Cheers,
James

**Comment by offirgolan** [comment]
Im not sure I follow, can you give me some sample code?

**Comment by jamesdixon** [comment]
Sorry, was on the way out the door and should have just waited to provide a proper example.

Anyways, as I mentioned I have an `address` attribute in my model that's returned by the API as an object and might return something like so:

```javascript
{ 
  street: '111 lala lane',
  city: 'doeville',
  state: 'MN',
  zipcode: '12345'
}
```

I'd like to be able to validate each of those properties individually. I tried something like the following, but was unsuccessful:

```javascript
// model.js
import Ember from 'ember';
import DS from 'ember-data';
import {
  validator, buildValidations
}
from 'ember-cp-validations';

const Validations = buildValidations({
  'address.street': validator('presence', true),
  'address.city': validator('presence', true),
  'address.state': validator('presence', true)
  'address.zipcode': validator('presence', true)
});

export default DS.Model.extend(Validations, {
  address: DS.attr('json', {
    defaultValue: () => {
      return {
        street: null,
        zipcode: null,
        city: null,
        country: 'United States'
      }
    }
  })
```

```handlebars
// template.hbs
            {{paper-input label="Mobile" value=user.phoneNumbers.mobile}}
            {{#if (v-get user 'phoneNumbers.mobile' 'isInvalid')}}
              <div class="error">
                {{v-get user 'phoneNumbers.mobile' 'message'}}
              </div>
            {{/if}}
```

I also tried using a computed alias in the model to reference the individual properties of that `address` field and then validating against that alias, but again was unsuccessful.

Let me know if this makes sense now -- hopefully I'm just missing something obvious :)

Cheers,
James

**Comment by offirgolan** [comment]
I think the easiest solution would be to make the address a model relationship via `belongsTo`

```js
//models/foo.js
const Validations = buildValidations({
  'address': validator('belongs-to')
});
export default DS.Model.extend(Validations, {
  address: DS.belongsTo('address', {async: false})
})
```

```js
//models/address.js
const Validations = buildValidations({
  'street': validator('presence', true),
  'city': validator('presence', true),
  'state': validator('presence', true)
  'zipcode': validator('presence', true)
});

export default DS.Model.extend(Validations, {
  street: DS.attr('string')
  // ...
})
```

```js
//serialzers/foo.js
export default DS.RESTSerializer.extend(DS.EmbeddedRecordsMixin, {
  attrs: {
    address: { embedded: 'always' },
  }
});
```

**Comment by jamesdixon** [comment]
@offirgolan thanks for the feedback. Unfortunately, this solution doesn't appear to work for me. First, I'm using JSON API and from [this thread](https://github.com/emberjs/data/issues/3720), it doesn't appear that `JSONAPISerializer` supports Embedded Records. That probably explains why my user model is filled with `undefined`s when attempting to use the `EmbeddedRecordsMixin` in a custom serializer.

I also tried using the [ember-data-model-fragments](https://github.com/lytics/ember-data-model-fragments) addon to handle these nested JSON documents, but again, the validators didn't work. 

Any other suggestions on how this might work? Given that dealing with nested JSON documents isn't that uncommon, I believe this won't be the first time this comes up. That said, more than willing to work on a solution with you.

Thanks!

**Comment by jamesdixon** [comment]
@offirgolan ok, so the issue is resolved. It was a mistake on my part: although I wasn't able to use the `EmbeddedRecordsMixin`, using `ember-data-model-fragments` is essentially the same thing. My mistake was that when using `v-get`, I was still passing in the base model rather than passing in `model.address`. Since `address` is now a separate model with its own validations, I needed to make sure `v-get` could access the validation properties.

Appreciate your help and pointing me in the right direction!

Cheers.

**Comment by offirgolan** [comment]
Glad I was able to kinda sorta help and that it all works now. Happy
holidays! 😁

On Sunday, December 20, 2015, James Dixon <notifications@github.com> wrote:

> @offirgolan <https://github.com/offirgolan> ok, so the issue is resolved.
> It was a mistake on my part: although I wasn't able to use the
> EmbeddedRecordsMixin, using ember-data-model-fragments is essentially the
> same thing. My mistake was that when using v-get, I was still passing in
> the base model rather than passing in model.address. Since address is now
> a separate model with its own validations, I needed to make sure v-get
> could access the validation properties.
>
> Appreciate your help and pointing me in the right direction!
>
> Cheers.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/offirgolan/ember-cp-validations/issues/91#issuecomment-166161201>
> .
>


-- 
Thanks,
Offir Golan

**Comment by TheCrazyDigitalPainter** [comment]
Could you please share the final code I've got the same issue
