### ISSUE TITLE
How to validate an ember-data model object

### ISSUE THREAD

**Issue by opiedog** [offirgolan/ember-cp-validations#97]
Sorry if my terminology is incorrect but I'm still learning Ember.

I have a model like this:
export default DS.Model.extend(Validations, {
  location: DS.belongsTo('location', { async: true }),
  ...
}

In my current (pre ember-cp-validations) code I validate that the location object has a valid ID like this:
      if (!adjustment.get('location.id') || !utils.isGuid(adjustment.get('location.id'))) {
        errors.pushObject('A location is required.');
      }
In our solution, a location is valid only if it has a non-null ID property and if that property is a GUID.

Is there a way to do that with your cool ember-cp-validations framework? I'm using it successfully for number and string types, but I'm not sure how to use it with foreign-key object types.

Thanks!

**Comment by offirgolan** [comment]
You will have to use the [belongs-to validator](http://offirgolan.github.io/ember-cp-validations/docs/classes/Belongs%20To.html) on the `location` attribute.

```js
// This will be the model you were talking about
var Validations = buildValidations({
 location: validator('belongs-to')
});

export default DS.Model.extend(Validations, {
  location: DS.belongsTo('location', { async: true }),
  //...
});
```

```js
// models/location.js
var Validations = buildValidations({
 id: validator((value) => { 
   if(!value || !utils.isGuid(value)) return 'A location is required';
   return true;
  })
});

export default DS.Model.extend(Validations, {
  // ...
});
```

When validating `id`, you can choose to just use a function or create a [custom validator](http://offirgolan.github.io/ember-cp-validations/docs/classes/Custom.html)

**Comment by opiedog** [comment]
Thanks, this was very helpful!
